(function(g){var window=this;'use strict';var gP=function(N){N.publish("cardstatechange",N.Of()&&N.Jk()?1:0)},cW=function(N,p){var S=g.eA(p),O=S?p:arguments;
for(S=S?0:1;S<O.length;S++){if(N==null)return;N=N[O[S]]}return N},vTt=function(N){var p=g.Uh(N);
N=g.aS(N);return new g.yx(p.x,p.y,N.width,N.height)},BXq=function(N,p,S){var O=O===void 0?{}:O;
var P;return P=g.za(N,p,function(){g.Er(P);S.apply(N,arguments)},O)},rP=function(N){N=g.t8(N);
delete FF[N];g.rD(FF)&&no&&no.stop()},ETY=function(){no||(no=new g.k6(function(){zgs()},20));
var N=no;N.isActive()||N.start()},zgs=function(){var N=g.IH();
g.mR(FF,function(p){$pG(p,N)});
g.rD(FF)||ETY()},M9=function(N,p,S,O){g.jl.call(this);
if(!Array.isArray(N)||!Array.isArray(p))throw Error("Start and end parameters must be arrays");if(N.length!=p.length)throw Error("Start and end points must be the same length");this.B=N;this.j=p;this.duration=S;this.K=O;this.coords=[];this.progress=this.N=0;this.G=null},$pG=function(N,p){p<N.startTime&&(N.endTime=p+N.endTime-N.startTime,N.startTime=p);
N.progress=(p-N.startTime)/(N.endTime-N.startTime);N.progress>1&&(N.progress=1);N.N=1E3/(p-N.G);N.G=p;JsY(N,N.progress);N.progress==1?(N.T=0,rP(N),N.onFinish(),N.kx()):N.isPlaying()&&N.rT()},JsY=function(N,p){typeof N.K==="function"&&(p=N.K(p));
N.coords=Array(N.B.length);for(var S=0;S<N.B.length;S++)N.coords[S]=(N.j[S]-N.B[S])*p+N.B[S]},mpY=function(N,p){g.Ad.call(this,N);
this.coords=p.coords;this.x=p.coords[0];this.y=p.coords[1];this.z=p.coords[2];this.duration=p.duration;this.progress=p.progress;this.fps=p.N;this.state=p.T},Ko=function(N,p,S,O,P){M9.call(this,p,S,O,P);
this.element=N},Upt=function(N,p,S,O,P){if(p.length!=2||S.length!=2)throw Error("Start and end points must be 2D");
Ko.call(this,N,p,S,O,P)},Hmd=function(N){return Math.pow(N,3)},iml=function(N){return 3*N*N-2*N*N*N},a6y=function(N){g.e.call(this);
this.B=N||window;this.T=[]},Yr=function(N){return N.baseUrl||null},G7=function(N,p){return g.sz(g.a2(N,p),function(S){return!!S})},Qly=function(N,p,S){function O(bX){var I=bX.hovercardButton;
if(!I)return null;I=I.subscribeButtonRenderer;if(!I)return null;var A=W(I.unsubscribedButtonText),k=W(I.subscribedButtonText);if(I.subscribed){var v=W(I.subscriberCountWithUnsubscribeText);var w=W(I.subscriberCountText)}else v=W(I.subscriberCountText),w=W(I.subscriberCountWithSubscribeText);var Zb=null;if(bX.signinEndpoint){Zb=cW(bX,"signinEndpoint","webNavigationEndpointData","url");if(!Zb){var Tf,bG;Zb=(bG=g.t((Tf=I.signInEndpoint)==null?void 0:Tf.commandMetadata,g.Jk))==null?void 0:bG.url}if(!Zb)return null}return A&&
(k||Zb)?{subscribed:I.subscribed,subscribeText:A,subscribeCount:v,unsubscribeText:k,unsubscribeCount:w,enabled:I.enabled,signinUrl:Zb,classic:bX.useClassicSubscribeButton}:null}
function P(bX){if(bX){var I=[],A=bX.videoId;A&&I.push("v="+A);(A=bX.playlistId)&&I.push("list="+A);(bX=bX.startTimeSeconds)&&I.push("t="+bX);return"/watch?"+I.join("&")}}
function W(bX){if(!bX)return null;var I=bX.simpleText;return I?I:bX.runs?g.a2(bX.runs,function(A){return A.text}).join(""):null}
p=p.endscreenElementRenderer;if(!p)return null;var X=p.style,l=p.endpoint||{},b=null,h=null,x=!1,y=null,V=null,L=null,T=null,E=!1,m=null,H=null,Q=null,n=null,K=null,d=null;if(X==="VIDEO")g.t(l,g.GU)?b=g.t(l,g.GU).url:(d=g.t(l,g.PC),b=P(d)),h=!1,y=N,p.thumbnailOverlays?(x=p.thumbnailOverlays[0].thumbnailOverlayTimeStatusRenderer,V=W(x.text),x=x.style==="LIVE"):V=W(p.videoDuration);else if(X==="PLAYLIST")g.t(l,g.GU)?b=g.t(l,g.GU).url:(d=g.t(l,g.PC),b=P(d)),h=!1,y=N,L=W(p.playlistLength);else if(X===
"CHANNEL"){if(E=cW(l,"browseEndpoint","browseId"))T=E,b="/channel/"+T;h=!1;y="new";(E=!!p.isSubscribe)?m=O(p):H=W(p.subscribersText)}else X==="WEBSITE"?((Q=cW(l,"urlEndpoint","url"))&&(b=Q),h=!0,y="new",Q=p.icon.thumbnails[0].url):X==="CREATOR_MERCHANDISE"&&(p.productPrice&&(n=W(p.productPrice)),p.additionalFeesText&&(K=W(p.additionalFeesText)),(h=cW(l,"urlEndpoint","url"))&&(b=h),h=!0,y="new");N=cW(p,"title","accessibility","accessibilityData","label");var D=p.endpoint?p.endpoint.clickTrackingParams:
null,u="";if(p.metadata){var oH=W(p.metadata);oH&&(u=oH)}return{id:"element-"+S,type:X,title:W(p.title),metadata:u,callToAction:W(p.callToAction),Go:p.image,iconUrl:Q,left:Number(p.left),width:Number(p.width),top:Number(p.top),aspectRatio:Number(p.aspectRatio),startMs:Math.floor(Number(p.startMs)),endMs:Math.floor(Number(p.endMs)),videoDuration:V,xV:x,playlistLength:L,channelId:T,subscribeButton:m,subscribersText:H,isSubscribe:E,targetUrl:b||null,EK:h,sessionData:D?{itct:D}:null,Usv:y,ir:N?N:null,
isPlaceholder:p.isPlaceholder,impressionUrls:G7(p.impressionUrls||[],Yr),hj:G7(p.hovercardShowUrls||[],Yr),clickUrls:G7(l.loggingUrls||[],Yr),visualElement:g.$k(p.trackingParams),productPrice:n,additionalFeesText:K,watchEndpoint:d||null}},gT0=function(N,p){var S={startMs:Math.floor(Number(N.startMs)),
impressionUrls:G7(N.impressionUrls||[],Yr),elements:G7(N.elements||[],function(O,P){return Qly(p,O,P)})};
N.trackingParams&&(S.visualElement=g.$k(N.trackingParams));return S},csl=function(N){g.dg.call(this,N);
this.G=this.endscreen=null;this.T={};this.N={};this.K=this.X=null;this.Y=[];this.B=null;this.u_=!0;this.j=0;N=N.J();this.W=g.gN(N)||g.Fg(N);this.events=new g.Ke(this);g.C(this,this.events);this.events.C(this.player,g.f7("creatorendscreen"),this.onCueRangeEnter);this.events.C(this.player,g.ls("creatorendscreen"),this.onCueRangeExit);this.events.C(this.player,"resize",this.I4);this.events.C(window,"focus",this.Pkj);this.load();var p=g.Xo("STYLE");(g.kB("HEAD")[0]||document.body).appendChild(p);this.addOnDisposeCallback(function(){g.si(p)});
p.sheet&&(p.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),p.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},FNG=function(N){return N.player.getVideoData().JF?"current":N.W?"new":"current"},dP=function(N){return N.player.J().playerStyle==="creator-endscreen-editor"},nTy=function(N){var p=N.player.getVideoData(),S=p.videoId;
N.G&&N.G.abort();S={method:"POST",onFinish:function(P){var W=N.G=null;P.status===200&&(P=P.responseText,P.substring(0,3)===")]}"&&(P=P.substring(3),W=JSON.parse(P),W=gT0(W,FNG(N))));eF(N,W)},
urlParams:{v:S},withCredentials:!0};N.W&&(S.urlParams.ptype="embedded");var O=p.S7;O&&(S.postParams={ad_tracking:O});if(p=g.bC6(p))if(p=g.GN(p),p=g.Mj(p))N.G=g.m3(p,S)},eF=function(N,p,S){S=S===void 0?!0:S;
N.player.WD("creatorendscreen");N.X&&(N.X.dispose(),N.X=null,N.K.dispose(),N.K=null);for(var O=g.z(Object.values(N.T)),P=O.next();!P.done;P=O.next())P.value.dispose();N.T={};N.N={};N.Y.length>0&&(N.Y.forEach(function(l){l.dispose()}),N.Y.length=0);
N.j=0;if((N.endscreen=p)&&p.elements){S&&rsy(N);S=[];O=new g.WY(p.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});S.push(O);N.player.J().B||(N.X=new g.R({S:"div",Z:"ytp-ce-shadow"}),g.IB(N.player,N.X.element,4),N.K=new g.Oa(N.X,200));for(O=0;O<p.elements.length;++O){P=p.elements[O];var W=M$t(N,P);if(W){N.T[P.id]=W;N.N[P.id]=P;g.IB(N.player,W.element,4);var X=new g.WY(P.startMs,P.endMs,{id:"ytp-ce-element-"+P.id,namespace:"creatorendscreen"});S.push(X);KNq(N,W,P)}else g.rO(new g.wp("buildEndscreenElement null",
P))}N.player.cD(S);N.I4()}},rsy=function(N){var p=g.m7(),S=g.UP();
S&&p&&N.endscreen.visualElement&&g.kc(g.Rm)(void 0,S,p,N.endscreen.visualElement)},M$t=function(N,p){var S=null;
switch(p.type){case "VIDEO":N={S:"div",Ky:["ytp-ce-element","ytp-ce-video"],V:{tabindex:"0","aria-label":p.ir||"","aria-hidden":"true"},L:[{S:"div",Z:"ytp-ce-element-shadow"},{S:"div",Z:"ytp-ce-covering-image",V:Co(p)},{S:"div",Z:"ytp-ce-covering-shadow-top"},{S:"a",Z:"ytp-ce-covering-overlay",V:{href:Av(N,p.targetUrl),tabindex:"-1"},L:[{S:"div",Ky:["ytp-ce-video-title","ytp-webkit-ellipsis"],V:{dir:g.VZ(p.title||"")},l_:p.title},{S:"div",Z:p.xV?"ytp-ce-live-video-duration":"ytp-ce-video-duration",
l_:p.videoDuration||void 0}]}]};S=new g.R(N);break;case "PLAYLIST":N={S:"div",Ky:["ytp-ce-element","ytp-ce-playlist"],V:{tabindex:"0","aria-label":p.ir||"","aria-hidden":"true"},L:[{S:"div",Z:"ytp-ce-element-shadow"},{S:"div",Z:"ytp-ce-covering-image",V:Co(p)},{S:"div",Z:"ytp-ce-covering-shadow-top"},{S:"a",Z:"ytp-ce-covering-overlay",V:{href:Av(N,p.targetUrl),tabindex:"-1"},L:[{S:"div",Ky:["ytp-ce-playlist-title","ytp-webkit-ellipsis"],V:{dir:g.VZ(p.title||"")},l_:p.title},{S:"div",Z:"ytp-ce-playlist-count",
L:[{S:"div",Z:"ytp-ce-playlist-icon"},{S:"div",Z:"ytp-ce-playlist-count-text",l_:p.playlistLength||void 0}]}]}]};S=new g.R(N);break;case "CHANNEL":S={S:"div",Ky:["ytp-ce-element","ytp-ce-channel",p.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],V:{tabindex:"0","aria-label":p.ir||"","aria-hidden":"true"},L:[{S:"div",Z:"ytp-ce-element-shadow"},{S:"div",Z:"ytp-ce-expanding-overlay",L:[{S:"div",Z:"ytp-ce-expanding-overlay-hider"},{S:"div",Z:"ytp-ce-expanding-overlay-background"},{S:"div",Z:"ytp-ce-expanding-overlay-content",
L:[{S:"div",Z:"ytp-ce-expanding-overlay-body",L:[{S:"div",Z:"ytp-ce-expanding-overlay-body-padding",L:[{S:"a",Ky:["ytp-ce-channel-title","ytp-ce-link"],V:{href:Av(N,p.targetUrl),target:"_blank",tabindex:"-1",dir:g.VZ(p.title||"")},l_:p.title},p.subscribeButton?{S:"div",Z:"ytp-ce-subscribe-container",L:[{S:"div",Z:"ytp-ce-channel-subscribe"}]}:"",p.subscribersText?{S:"div",Z:"ytp-ce-channel-subscribers-text",l_:p.subscribersText}:"",p.metadata?{S:"div",Ky:["ytp-ce-channel-metadata","yt-ui-ellipsis",
"yt-ui-ellipsis-3"],l_:p.metadata}:""]}]}]}]},{S:"div",Z:"ytp-ce-expanding-image",V:Co(p)}]};S=new g.R(S);var O=g.NL(document,"div","ytp-ce-channel-subscribe",S.element)[0];if(p.subscribeButton&&p.channelId){g.WF(O,"ytp-ce-subscribe-button");if(N.player.J().B){var P=null;var W=p.sessionData.itct}else P="endscreen",W=null;P=new g.zG(p.subscribeButton.subscribeText,p.subscribeButton.subscribeCount,p.subscribeButton.unsubscribeText,p.subscribeButton.unsubscribeCount,!!p.subscribeButton.enabled,!!p.subscribeButton.classic,
p.channelId,!!p.subscribeButton.subscribed,P,W,N.player,!1);O.appendChild(P.element);N.Y.push(P)}break;case "WEBSITE":N={S:"div",Ky:["ytp-ce-element","ytp-ce-website"],V:{tabindex:"0","aria-label":p.ir||"","aria-hidden":"true"},L:[{S:"div",Z:"ytp-ce-element-shadow"},{S:"div",Z:"ytp-ce-expanding-overlay",L:[{S:"div",Z:"ytp-ce-expanding-overlay-hider"},{S:"div",Z:"ytp-ce-expanding-overlay-background"},{S:"div",Z:"ytp-ce-expanding-overlay-content",L:[{S:"div",Z:"ytp-ce-expanding-overlay-body",L:[{S:"div",
Z:"ytp-ce-expanding-overlay-body-padding",L:[{S:"div",Z:"ytp-ce-website-title",V:{dir:g.VZ(p.title||"")},l_:p.title},{S:"div",Z:"ytp-ce-website-metadata",l_:p.metadata},{S:"a",Ky:["ytp-ce-website-goto","ytp-ce-link"],V:{href:Av(N,p.targetUrl),target:"_blank",tabindex:"-1"},l_:p.callToAction}]}]}]}]},{S:"div",Z:"ytp-ce-expanding-image",V:Co(p)},{S:"div",Z:"ytp-ce-expanding-icon",V:YMG(p.iconUrl)}]};S=new g.R(N);break;case "CREATOR_MERCHANDISE":S="",p.productPrice&&(S={S:"div",Z:"ytp-ce-merchandise-price-container",
L:[{S:"div",Z:"ytp-ce-merchandise-price",l_:p.productPrice}]},p.additionalFeesText&&S.L.push({S:"div",Z:"ytp-ce-merchandise-additional-fees",l_:p.additionalFeesText})),N={S:"div",Ky:["ytp-ce-element","ytp-ce-merchandise"],V:{tabindex:"0","aria-label":p.ir||"","aria-hidden":"true"},L:[{S:"div",Z:"ytp-ce-element-shadow"},{S:"div",Z:"ytp-ce-expanding-overlay",L:[{S:"div",Z:"ytp-ce-expanding-overlay-hider"},{S:"div",Z:"ytp-ce-expanding-overlay-background"},{S:"div",Z:"ytp-ce-expanding-overlay-content",
L:[{S:"div",Z:"ytp-ce-expanding-overlay-body",L:[{S:"div",Z:"ytp-ce-expanding-overlay-body-padding",L:[{S:"div",Z:"ytp-ce-merchandise-title",V:{dir:g.VZ(p.title||"")},l_:p.title},S,{S:"div",Z:"ytp-ce-merchandise-metadata",l_:p.metadata},{S:"a",Ky:["ytp-ce-merchandise-goto","ytp-ce-link"],V:{href:Av(N,p.targetUrl),target:"_blank",tabindex:"-1"},l_:p.callToAction}]}]}]}]},{S:"div",Z:"ytp-ce-expanding-image",V:Co(p)},{S:"div",Z:"ytp-ce-merchandise-invideo-cta-container",L:[{S:"div",Z:"ytp-ce-merchandise-invideo-cta",
l_:p.callToAction||void 0}]}]},S=new g.R(N)}p.isPlaceholder&&g.WF(S.element,"ytp-ce-placeholder");return S},Co=function(N){if(N.Go)var p=N.Go.thumbnails;
return YMG(p?p[p.length-1].url:null)},YMG=function(N){return N?{style:"background-image: url("+N+")"}:{}},KNq=function(N,p,S){function O(b){b&&(p.listen("blur",function(){b.style.display!="none"&&N.u_&&b.focus()}),p.C(b,"focus",W),p.C(b,"blur",X))}
function P(b){N.j+=b;N.j>0?(g.WF(p.element,"ytp-ce-force-expand"),tv(N,S.id,!0)):(g.fE(p.element,"ytp-ce-force-expand"),g.fE(p.element,"ytp-ce-element-hover"),tv(N,S.id,!1))}
function W(){P(1)}
function X(){P(-1)}
p.listen("mouseenter",function(){GgE(N,p,S)});
p.listen("mouseleave",function(){dpY(N,p,S)});
N.player.J().B||p.listen("click",function(){g.WF(p.element,"ytp-ce-element-hover")});
p.listen("click",function(b){egC(N,S,b)});
p.listen("keypress",function(b){egC(N,S,b)});
p.listen("focus",function(){GgE(N,p,S)});
p.listen("blur",function(){dpY(N,p,S)});
p.listen("touchstart",function(){GgE(N,p,S)});
var l=g.pW("ytp-ce-expanding-overlay-hider",p.element);l&&p.C(l,"touchstart",function(b){b.stopPropagation();g.fE(p.element,"ytp-ce-element-hover");g.fE(p.element,"ytp-ce-force-expand")});
p.listen("keydown",function(b){N.u_=b.keyCode===9&&!b.shiftKey});
O(g.pW("ytp-sb-subscribe",p.element));O(g.pW("ytp-sb-unsubscribe",p.element));p.listen("focus",W);p.listen("blur",X)},egC=function(N,p,S){if(p.targetUrl&&(!S||S.type!=="keypress"||S.keyCode===13)){for(var O=S.target;O&&!g.PF(O,"ytp-ce-element");){g.PF(O,"subscribe-label")&&CHB(N,p);
if(g.PF(O,"ytp-ce-channel-subscribe"))return;O=O.parentElement||null}if(!O||g.PF(O,"ytp-ce-element-hover")){S.preventDefault();S.stopPropagation();if(O=N.T[p.id])dpY(N,O,p),O.element.blur();if(S.ctrlKey||S.metaKey||p.Usv==="new")CHB(N,p),N.player.sendVideoStatsEngageEvent(17,void 0),N.player.pauseVideo(),S=g.GN(Av(N,p.targetUrl)),S=g.Mj(S),g.Ro(S,void 0,p.sessionData);else{var P=g.wN(N.player.J())||N.player.getVideoData().JF,W=function(){var X=Av(N,p.targetUrl),l=p.sessionData,b=p.watchEndpoint,h=
g.OB(X);P&&h&&(h.v||h.list)?N.player.P_(h.v,l,h.list,!1,void 0,b||void 0):g.wo(X,l)};
CHB(N,p,function(){N.player.sendVideoStatsEngageEvent(17,W)})}}}},Av=function(N,p){N=N.player.J();
if(p){if(p.startsWith("//"))return N.protocol+":"+p;if(p.startsWith("/"))return g.py(N)+p}else return"";return p},GgE=function(N,p,S){g.PF(p.element,"ytp-ce-element-hover")||(S.type==="VIDEO"||S.type==="PLAYLIST"?g.WF(p.element,"ytp-ce-element-hover"):N.player.J().B?(new g.k6(function(){g.WF(p.element,"ytp-ce-element-hover")},200)).start():g.WF(p.element,"ytp-ce-element-hover"),uc(N,S.hj),tv(N,S.id,!0))},dpY=function(N,p,S){g.fE(p.element,"ytp-ce-element-hover");
g.fE(p.element,"ytp-ce-force-expand");tv(N,S.id,!1)},tv=function(N,p,S){N.X&&(S?N.K.show():N.K.hide());
for(var O=g.z(Object.keys(N.T)),P=O.next();!P.done;P=O.next())P=P.value,P!==p&&g.bS(N.T[P].element,"ytp-ce-element-shadow-show",S)},uc=function(N,p,S){function O(){W||(P++,P===p.length&&(X.stop(),S&&S()))}
if(!p||p.length===0||dP(N))S&&S();else{p=AsQ(N,p);var P=0,W=!1,X=new g.k6(function(){W=!0;S&&S()},1E3,N);
X.start();for(N=0;N<p.length;N++)g.tC(p[N],O)}},CHB=function(N,p,S){uc(N,p.clickUrls,S);
(N=g.UP())&&p.EK&&g.Pn(N,p.visualElement)},AsQ=function(N,p){var S=N.player.getVideoData().clientPlaybackNonce;
N=N.player.getCurrentTime().toFixed(2);S={CPN:S,AD_CPN:S,MT:N};N=[];for(var O=0;O<p.length;O++)N.push(t$f(p[O],S));return N},t$f=function(N,p){return N.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(S){var O=unescape(S);
O=O.substring(1,O.length-1);return p[O]?escape(p[O]):S})},ubR=function(N){return typeof N==="string"?N:""},wP=function(N,p,S){for(var O in p)if(p[O]===N)return N;
return S},wXE=function(N,p,S,O){this.value=N;
this.target=p;this.showLinkIcon=S;this.T=O},RV=function(N){return N.value?N.value:null},IV=function(N){if(!N)return null;
var p=g.GN(ubR(N.value));p=g.Mj(p);if(!p)return null;var S=wP(N.target,RgQ,"current");if(S==null)N=null;else{var O=N.show_link_icon;N=new wXE(p,S,O==="true"||O==="false"?O==="true":!0,N.pause_on_navigation!=null?N.pause_on_navigation:!0)}return N},I6t=function(N,p,S){this.type=N;
this.trigger=p;this.url=S},kgf=function(N){if(!N)return null;
var p=wP(N.type,Dpf),S=wP(N.trigger,ZmB);N=N.url;N=Array.isArray(N)&&N.length?N[0]:N;N=IV(N?N:null);return p?new I6t(p,S,N):null},qME=function(N,p,S,O,P){this.id=N;
this.type=p;this.style=S;this.data=P;this.action=O||[]},Nbf=function(N,p){return g.tR(N.action,p)},pUY=function(N,p){this.context=N;
this.T=p},o1Y=function(N){return N.customMessage?Dy("div","iv-card-message",N.customMessage):""},Zy=function(N,p){N="background-image: url("+N+");";
var S=[];p&&S.push(p);return{S:"div",Z:"iv-card-image",V:{style:N},L:S}},Scq=function(N){if(!N.metaInfo||N.metaInfo.length===0)return"";
var p=[];N=g.z(N.metaInfo);for(var S=N.next();!S.done;S=N.next())p.push(Dy("li","",S.value));return{S:"ul",Z:"iv-card-meta-info",L:p}},Dy=function(N,p,S){p?typeof p==="string"?p={"class":p}:Array.isArray(p)&&(p={"class":p.join(" ")}):p={};
p.dir=g.VZ(S);return{S:N,V:p,l_:S}},Owl=function(N){if(!N.customMessage)return"";
var p=["iv-card-action","iv-card-primary-link"],S={};N.jy&&(p.push("iv-card-action-icon"),S.style="background-image: url("+N.jy+");");S.dir=g.VZ(N.customMessage);var O=[{S:"span",l_:N.customMessage}];N.showLinkIcon&&(O.push("\u00a0"),O.push({S:"span",Z:"iv-card-link-icon"}));return{S:"div",Ky:p,V:S,L:O}},kr=function(N,p,S,O){if(O){p=g.z(p);
for(var P=p.next();!P.done;P=p.next())N.T(P.value,O,S.id,S.sessionData,S.kN.click,5)}},PoB=function(N,p){this.merchant=N;
this.price=p},WeC=function(N){var p;
(p=N)&&!(p=N.length>1?N.charAt(0)==="/"&&N.charAt(1)!=="/":N==="/")&&(p=N.replace(/^(https?:)?\/\//,"").split("/",1),p=!p||p.length<1||!p[0]?[]:p[0].toLowerCase().split(".").reverse(),p=p[0]==="com"&&p[1]==="youtube"||p[0]==="be"&&p[1]==="youtu");return p?N.indexOf("/redirect?")===-1:!1},XUd=function(N,p){return p?p:WeC(N)?"current":"new"},q9=function(N,p){g.e.call(this);
var S=this;this.element=N;this.context=p;this.WP=!1;this.Np=new Map;this.vP=new Map;this.context.D.addEventListener(g.f7("annotations_module"),function(O){(O=S.Np.get(O))&&O.apply(S)});
this.context.D.addEventListener(g.ls("annotations_module"),function(O){(O=S.vP.get(O))&&O.apply(S)})},NM=function(N,p,S,O,P,W,X){N.context.T.listen(p,"click",function(l){N.S2(S,O,P,W||[],X||0,l)});
N.context.T.listen(p,"touchstart",function(){N.WP=!1});
N.context.T.listen(p,"touchmove",function(){N.WP=!0})},f80=function(N){var p;
return((p=g.t(N,g.GU))==null?0:p.url)?g.t(N,g.GU).url:(N=g.t(N,g.PC))&&N.videoId?(p="/watch?v="+N.videoId,N.playlistId&&(p+="&list="+N.playlistId),N.index&&(p+="&index="+N.index),N.startTimeSeconds&&(p+="&t="+N.startTimeSeconds),p):null},pS=function(N,p,S){return{cW:(N.impressionLoggingUrlsV2s||[]).map(function(O){return O.baseUrl||""}),
click:(S.loggingUrls||[]).map(function(O){return O.baseUrl||""}),
close:(p.dismissLoggingUrlsV2s||[]).map(function(O){return O.baseUrl||""}),
Ch:(p.impressionLoggingUrlsV2s||[]).map(function(O){return O.baseUrl||""}),
lq:(p.clickLoggingUrlsV2s||[]).map(function(O){return O.baseUrl||""})}},l8q=function(N,p,S){q9.call(this,p,S);
var O=this;this.D=N;this.eventId=null;this.kR=this.i_=this.KI=this.X=this.isInitialized=!1;this.cards=[];this.Vd=this.Y=this.Qd=this.K=this.jS=this.T=null;this.u_=[];this.zk=this.j=this.tF=this.xO=null;this.N=0;this.eS=new g.k6(function(){},S.aj.d9?4E3:3E3);
g.C(this,this.eS);this.Ly=new g.k6(function(){});
g.C(this,this.Ly);this.py=new pUY(S,function(P,W,X,l,b,h){NM(O,P,W,X,l,b,h)});
this.W=new g.R({S:"div",Z:"iv-drawer",V:{id:"iv-drawer"},L:[{S:"div",Z:"iv-drawer-header",V:{"aria-role":"heading"},L:[{S:"span",Z:"iv-drawer-header-text"},{S:"button",Ky:["iv-drawer-close-button","ytp-button"],V:{"aria-label":"Hide cards",tabindex:"0"}}]},{S:"div",Z:"iv-drawer-content"}]});g.C(this,this.W);this.G=this.W.element;this.Ij=new g.Oa(this.W,330);g.C(this,this.Ij);this.wF=g.pW("iv-drawer-header-text",this.G);this.B=g.pW("iv-drawer-content",this.G);this.addCueRange(0,S.videoData.lengthSeconds*
1E3,"",function(){O.KI&&oc(O,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(O.KI=O.X)&&SO(O)});
this.rH=new g.Ke(this);g.C(this,this.rH);this.D.addEventListener("videodatachange",this.Nk.bind(this))},bw0=function(N,p){p=p.data;
p.autoOpenMs&&N.addCueRange(p.autoOpenMs,0x8000000000000,"",function(){oc(N,"YOUTUBE_DRAWER_AUTO_OPEN")});
p.autoCloseMs&&N.addCueRange(p.autoCloseMs,0x8000000000000,"",function(){SO(N)});
var S=p.headerText;g.xY(N.wF,S);N.Y&&N.Y.setAttribute("title",S);p.eventId&&(N.eventId=p.eventId);N.xO=g.$k(p.trackingParams);N.j=g.$k(p.closeTrackingParams);N.tF=g.$k(p.iconTrackingParams)},jwY=function(N,p){var S=p.cardId?p.cardId:"cr:"+N.N,O=N.D.J().experiments.yd("enable_error_corrections_infocard_web_client");
if(!p.content&&p.teaser.simpleCardTeaserRenderer&&O){var P=p.teaser.simpleCardTeaserRenderer,W=p.icon?p.icon.infoCardIconRenderer:null;p={id:S,timestamp:N.N,type:"simple",teaserText:g.vn(P.message),teaserDurationMs:Number(p.cueRanges[0].teaserDurationMs),startMs:Number(p.cueRanges[0].startCardActiveMs),autoOpen:!!p.autoOpen,sessionData:{},sponsored:!1,kN:{},L4:null,Cn:P.trackingParams?g.$k(P.trackingParams):null,tF:W&&W.trackingParams?g.$k(W.trackingParams):null,imageUrl:"",displayDomain:null,showLinkIcon:!1,
jy:null,title:"",customMessage:"",url:null,onClickCommand:P.onTapCommand||null};OV(N,p)}else{var X;if((X=p.content)==null?0:X.simpleCardContentRenderer){if(!p.cueRanges.length)return;W=(P=p.content)==null?void 0:P.simpleCardContentRenderer;P=p.teaser.simpleCardTeaserRenderer;var l=p.icon?p.icon.infoCardIconRenderer:null;p={id:S,timestamp:N.N,type:"simple",teaserText:g.vn(P.message),teaserDurationMs:Number(p.cueRanges[0].teaserDurationMs),startMs:Number(p.cueRanges[0].startCardActiveMs),autoOpen:!!p.autoOpen,
sessionData:P3(N,S,p,W),sponsored:!1,kN:pS(W,P,W.command),L4:W.trackingParams?g.$k(W.trackingParams):null,Cn:P.trackingParams?g.$k(P.trackingParams):null,tF:l&&l.trackingParams?g.$k(l.trackingParams):null,imageUrl:W3(W.image.thumbnails,290).url,displayDomain:W.displayDomain?g.vn(W.displayDomain):null,showLinkIcon:!!W.showLinkIcon,jy:null,title:W.title?g.vn(W.title):"",customMessage:W.callToAction?g.vn(W.callToAction):"",url:g.t(W.command,g.GU).url?IV({pause_on_navigation:!N.context.videoData.isLivePlayback,
target:"new",value:g.t(W.command,g.GU).url}):null,onClickCommand:null};OV(N,p)}else{var b;if((b=p.content)==null?0:b.collaboratorInfoCardContentRenderer){if(!p.cueRanges.length)return;P=(W=p.content)==null?void 0:W.collaboratorInfoCardContentRenderer;W=p.teaser.simpleCardTeaserRenderer;l=p.icon?p.icon.infoCardIconRenderer:null;p={id:S,timestamp:N.N,type:"collaborator",teaserText:g.vn(W.message),teaserDurationMs:Number(p.cueRanges[0].teaserDurationMs),startMs:Number(p.cueRanges[0].startCardActiveMs),
autoOpen:!!p.autoOpen,sessionData:P3(N,S,p,P),sponsored:!1,kN:pS(P,W,P.endpoint),L4:P.trackingParams?g.$k(P.trackingParams):null,Cn:W.trackingParams?g.$k(W.trackingParams):null,tF:l&&l.trackingParams?g.$k(l.trackingParams):null,channelId:g.t(P.endpoint,g.mv).browseId,customMessage:P.customText?g.vn(P.customText):null,profileImageUrl:W3(P.channelAvatar.thumbnails,290).url,title:P.channelName?g.vn(P.channelName):"",metaInfo:[P.subscriberCountText?g.vn(P.subscriberCountText):""],url:IV({pause_on_navigation:!N.context.videoData.isLivePlayback,
target:"new",value:g.t(P.endpoint,g.mv).canonicalBaseUrl?g.t(P.endpoint,g.mv).canonicalBaseUrl:"/channel/"+g.t(P.endpoint,g.mv).browseId}),onClickCommand:null};OV(N,p)}else{var h;if((h=p.content)==null?0:h.playlistInfoCardContentRenderer){if(!p.cueRanges.length)return;P=(l=p.content)==null?void 0:l.playlistInfoCardContentRenderer;W=p.teaser.simpleCardTeaserRenderer;l=p.icon?p.icon.infoCardIconRenderer:null;p={id:S,timestamp:N.N,type:"playlist",teaserText:g.vn(W.message),teaserDurationMs:Number(p.cueRanges[0].teaserDurationMs),
startMs:Number(p.cueRanges[0].startCardActiveMs),autoOpen:!!p.autoOpen,sessionData:P3(N,S,p,P),sponsored:!1,kN:pS(P,W,P.action),L4:P.trackingParams?g.$k(P.trackingParams):null,Cn:W.trackingParams?g.$k(W.trackingParams):null,tF:l&&l.trackingParams?g.$k(l.trackingParams):null,I8:W3(P.playlistThumbnail.thumbnails,258).url,customMessage:P.customMessage?g.vn(P.customMessage):null,playlistVideoCount:g.vn(P.playlistVideoCount),title:P.playlistTitle?g.vn(P.playlistTitle):"",metaInfo:[P.channelName?g.vn(P.channelName):
"",P.videoCountText?g.vn(P.videoCountText):""],url:IV({pause_on_navigation:!N.context.videoData.isLivePlayback,target:"new",value:f80(P.action)}),onClickCommand:null};OV(N,p)}else{var x;if((x=p.content)==null?0:x.videoInfoCardContentRenderer){if(!p.cueRanges.length)return;var y;P=(y=p.content)==null?void 0:y.videoInfoCardContentRenderer;W=p.teaser.simpleCardTeaserRenderer;l=p.icon?p.icon.infoCardIconRenderer:null;p={id:S,timestamp:N.N,type:"video",teaserText:g.vn(W.message),teaserDurationMs:Number(p.cueRanges[0].teaserDurationMs),
startMs:Number(p.cueRanges[0].startCardActiveMs),autoOpen:!!p.autoOpen,sessionData:P3(N,S,p,P),sponsored:!1,kN:pS(P,W,P.action),L4:P.trackingParams?g.$k(P.trackingParams):null,Cn:W.trackingParams?g.$k(W.trackingParams):null,tF:l&&l.trackingParams?g.$k(l.trackingParams):null,I8:W3(P.videoThumbnail.thumbnails,258).url,videoDuration:P.lengthString?g.vn(P.lengthString):null,customMessage:P.customMessage?g.vn(P.customMessage):null,title:P.videoTitle?g.vn(P.videoTitle):"",metaInfo:[P.channelName?g.vn(P.channelName):
"",P.viewCountText?g.vn(P.viewCountText):""],isLiveNow:!!P.badge,url:IV({pause_on_navigation:!N.context.videoData.isLivePlayback,target:"new",value:f80(P.action)}),onClickCommand:null};OV(N,p)}}}}}N.N++},W3=function(N,p){for(var S=-1,O=-1,P=0;P<N.length;P++){if(N[P].height===p||N[P].width===290)return N[P];
((N[P].height||0)<p||(N[P].width||0)<290)&&(S<0||(N[S].height||0)<(N[P].height||0)||(N[S].width||0)<(N[P].width||0))?S=P:((N[P].height||0)>=p||(N[P].width||0)>=290)&&(O<0||(N[O].height||0)>(N[P].height||0)||(N[O].width||0)>(N[P].width||0))&&(O=P)}return N[O>=0?O:S]},P3=function(N,p,S,O){return{feature:S.feature?S.feature:"cards",
src_vid:N.context.videoData.videoId,annotation_id:p,ei:N.context.videoData.eventId||"",itct:O.trackingParams||""}},hDC=function(N,p){if(p=swV(N,p))p===N.T&&(N.T=null),N.D.removeCueRange(p.je.id),g.si(p.s7),g.I0(N.cards,p),N.VQ(),XO(N)},oc=function(N,p,S){if(!N.X){N.Ij.show();
N.jS=new g.k6(function(){g.WF(N.context.D.getRootNode(),g.Cz.IV_DRAWER_OPEN)},0);
N.jS.start();N.rH.C(N.B,"mousewheel",function(X){N.eS.start();X.preventDefault();X=X||window.event;var l=0;X.type=="MozMousePixelScroll"?l=0==(X.axis==X.HORIZONTAL_AXIS)?X.detail:0:window.opera?l=X.detail:l=X.wheelDelta%120==0?"WebkitTransform"in document.documentElement.style?window.chrome&&navigator.platform.indexOf("Mac")==0?X.wheelDeltaY/-30:X.wheelDeltaY/-1.2:X.wheelDelta/-1.6:X.wheelDeltaY/-3;if(X=l)N.B.scrollTop+=X});
N.X=!0;var O=g.UP();O&&N.xO&&N.j&&g.Ss(O,[N.xO,N.j]);p={TRIGGER_TYPE:p};for(var P=g.z(N.cards),W=P.next();!W.done;W=P.next())W=W.value,W.Wp||(W.Wp=!0,xjY(N.context.logger,W.je.kN.cW,p)),O&&g.Ss(O,[W.je.L4]);gP(N.D);S&&(N.K=new g.k6(function(){N.Qd=N.Y;N.Vd.focus()},330),N.K.start())}},SO=function(N){N.X&&(N.Ij.hide(),g.aR(N.rH),g.fE(N.context.D.getRootNode(),g.Cz.IV_DRAWER_OPEN),N.X=!1,gP(N.D),N.K&&N.K.stop(),N.K=new g.k6(function(){N.Qd&&(N.Qd.focus(),N.Qd=null)},330),N.K.start())},n1t=function(N){g.Xi(N.fI(),
[g.Cz.STOP_EVENT_PROPAGATION,
"iv-drawer-manager"]);g.IB(N.D,N.G,5);N.hp();N.Y=g.pW("ytp-cards-button",N.D.getRootNode());N.Vd=g.pW("iv-drawer-close-button",N.G);N.isInitialized=!0},rLy=function(N){N.u_.push(g.lV("iv-teaser-shown",N.vO,N));
N.u_.push(g.lV("iv-teaser-hidden",N.Rf,N));N.u_.push(g.lV("iv-teaser-clicked",N.nj,N));N.kR=!0},M5V=function(N,p){var S;
return p.onClickCommand&&((S=g.t(p.onClickCommand,g.prQ))==null?void 0:S.targetId)==="engagement-panel-error-corrections"?(N.zk=p,!0):!1},Ke0=function(N,p){N.zk=p;
var S=N.D.getVideoData();if(!S)return!1;S=g.$A(S);if(S==null?0:S.markersMap)for(var O,P=0;((O=S)==null?void 0:O.markersMap.length)>P;P++){var W=void 0,X=(W=S)==null?void 0:W.markersMap[P];if(X.key==="ERROR_CORRECTION_MARKERS"&&(W=void 0,(X=(W=X.value)==null?void 0:W.markers)&&X.length>0))return O=void 0,p.startMs=((O=g.t(X[0],g.d9s))==null?void 0:O.timeRangeStartMillis)||0,N.zk=null,!0}return!1},OV=function(N,p){if(!M5V(N,p)||Ke0(N,p)){var S=YcC(N,p);
if(S){var O={je:p,s7:S.element,Wp:!1};if(p.onClickCommand)N.D.U("web_infocards_teaser_show_logging_fix")&&(N.kR||rLy(N),hDC(N,p.id),S=N.findLastIndex(O),g.pJ(N.cards,S,0,O));else{N.isInitialized||n1t(N);hDC(N,p.id);var P=N.findLastIndex(O);g.pJ(N.cards,P,0,O);S.Rj(N.B,P);N.VQ()}p.autoOpen?N.addCueRange(p.startMs,0x8000000000000,p.id,function(){N.X||(N.T=O,XO(N),GNB(N,O),oc(N,"YOUTUBE_DRAWER_AUTO_OPEN",!1))}):(S=N.context.D.getCurrentTime()*1E3,S<5E3&&S>p.startMs&&djl(N,O),N.addCueRange(p.startMs,
p.startMs+1,p.id,function(){djl(N,O)}),XO(N))}}},YcC=function(N,p){switch(p.type){case "simple":N=N.py;
var S=p.displayDomain?{S:"div",Z:"iv-card-image-text",l_:p.displayDomain}:void 0;var O=Owl(p);S={S:"div",Ky:["iv-card"],L:[{S:"a",Z:"iv-click-target",V:{href:p.url?RV(p.url)||"":""},L:[Zy(p.imageUrl,S),{S:"div",Z:"iv-card-content",L:[Dy("h2",void 0,p.title),O]}]}]};S=new g.R(S);kr(N,g.q1("iv-click-target",S.element),p,p.url);p=S;break;case "collaborator":N=N.py;S={S:"div",Ky:["iv-card","iv-card-channel"],L:[{S:"a",Ky:["iv-click-target"],V:{href:RV(p.url)||"","data-ytid":p.channelId},L:[Zy(p.profileImageUrl),
{S:"div",Z:"iv-card-content",L:[o1Y(p),{S:"h2",Z:"iv-card-primary-link",l_:p.title},Scq(p)]}]}]};S=new g.R(S);kr(N,g.q1("iv-click-target",S.element),p,p.url);p=S;break;case "playlist":N=N.py;S={S:"div",Ky:["iv-card","iv-card-playlist"],L:[{S:"a",Z:"iv-click-target",V:{href:RV(p.url)||""},L:[Zy(p.I8,{S:"div",Z:"iv-card-image-overlay",L:[{S:"span",Z:"iv-card-playlist-video-count",l_:p.playlistVideoCount}]}),{S:"div",Z:"iv-card-content",L:[o1Y(p),Dy("h2","iv-card-primary-link",p.title),Scq(p)]}]}]};
S=new g.R(S);kr(N,g.q1("iv-click-target",S.element),p,p.url);p=S;break;case "productListing":N=N.py;var P=p.offers.length!=0;S=["iv-card"];O="";var W=Owl(p);P&&(S.push("iv-card-product-listing"),O="iv-card-primary-link",W=p.offers[0],P=[],W.price&&P.push({S:"div",Z:"iv-card-offer-price",l_:W.price}),W.merchant&&P.push({S:"div",Z:"iv-card-offer-merchant",l_:W.merchant}),W={S:"div",L:P});P=p.url?RV(p.url)||"":"";S={S:"div",Ky:S,V:{tabindex:"0"},L:[{S:"a",Ky:["iv-card-image","iv-click-target"],V:{style:"background-image: url("+
p.imageUrl+");",href:P,"aria-hidden":"true",tabindex:"-1"}},{S:"div",Z:"iv-card-content",L:[p.sponsored?{S:"div",Z:"iv-card-sponsored",L:["Sponsored",{S:"div",Z:"iv-ad-info-container",L:[{S:"div",Z:"iv-ad-info",l_:"{{adInfo}}"},{S:"div",Z:"iv-ad-info-icon-container",L:[{S:"div",Z:"iv-ad-info-icon"},{S:"div",Z:"iv-ad-info-callout"}]}]}]}:"",{S:"a",Z:"iv-click-target",V:{href:P},L:[Dy("h2",O,p.title),W]}]}]};S=new g.R(S);O=g.Xo("span");g.xY(O,"You are seeing this product because we think it is relevant to the video. Google may be compensated by the merchant.");
S.YK(O,"adInfo");kr(N,g.q1("iv-click-target",S.element),p,p.url);p=S;break;case "video":N=N.py;O=p.videoDuration?{S:"span",Z:"iv-card-video-duration",l_:p.videoDuration}:void 0;W=p.isLiveNow?{S:"span",Ky:["yt-badge","yt-badge-live"],l_:"LIVE NOW"}:null;P={S:"div",Ky:["iv-card","iv-card-video"],L:[{S:"a",Z:"iv-click-target",V:{href:((S=p.url)==null?void 0:RV(S))||""},L:[Zy(p.I8,O),{S:"div",Z:"iv-card-content",L:[o1Y(p),Dy("h2","iv-card-primary-link",p.title),Scq(p),W]}]}]};S=new g.R(P);kr(N,g.q1("iv-click-target",
S.element),p,p.url);p=S;break;default:return null}return p},eDf=function(N){if(N.T)return N.T.je.type==="productListing";
if(N.D.U("enable_wn_infocards")){var p;return!((p=N.cards)==null||!p.length)&&g.QK(N.cards,function(S){return S.je.type==="productListing"})}return g.QK(N.cards,function(S){return S.je.type==="productListing"})},XO=function(N){g.bS(N.D.getRootNode(),"ytp-cards-shopping-active",eDf(N))},djl=function(N,p){if(!g.PF(N.D.getRootNode(),"ytp-cards-teaser-shown")){if(N.T!==p){var S=g.UP(),O=N.T?N.T.je.tF:N.tF;
S&&O&&g.OU(S,[O]);N.T=p;XO(N)}(S=N.isInitialized&&N.fI().style.display=="none")||(S=N.context.D.getPlayerState(),O=S===0&&N.context.D.getCurrentTime()===0,S=!(S===1||S===3||O));S||p.je.teaserDurationMs&&N.D.Kt(!0,{teaserText:p.je.teaserText,durationMs:p.je.teaserDurationMs,onClickCommand:p.je.onClickCommand});N.Ly.isActive()||((!N.X||!N.eS.isActive()&&N.i_)&&GNB(N,p),N.Ly.start(910+p.je.teaserDurationMs))}},GNB=function(N,p){N.W.Oa?(p=new M9([0,
N.B.scrollTop],[0,p.s7.offsetTop],600,iml),N.context.X.listen(p,"animate",function(S){N.B.scrollTop=S.y}),N.context.X.listen(p,"finish",function(S){N.B.scrollTop=S.y}),p.play()):(N.W.Ea(!0),N.B.scrollTop=p.s7.offsetTop,N.W.Ea(!1))},fS=function(N){return N.T&&N.T.je?N.T.je:N.cards[0]&&N.cards[0].je?N.cards[0].je:null},swV=function(N,p){return g.tR(N.cards,function(S){return S.je.id===p})},lk=function(N,p,S){q9.call(this,N,p);
this.annotation=S;this.isActive=!1},CoR=function(N){var p=N.annotation.data;
"start_ms"in p&&"end_ms"in p&&N.addCueRange(Number(p.start_ms),Number(p.end_ms),N.annotation.id,function(){N.show()},function(){N.hide()})},bk=function(N,p,S){lk.call(this,N,p,S);
this.B=null;this.j=!1;this.X=null;this.G=!1;this.T=this.N=this.K=null},AL0=function(N,p){var S=S===void 0?0:S;
var O=vTt(p).width;g.JE(p,O);S=new Upt(p,[O,p.offsetTop],[O-O-S,p.offsetTop],200,Hmd);g.C(N,S);N.context.X.listen(S,"begin",function(){g.Qx(p,!0)});
S.play()},wUE=function(N,p){if(p.channel_name){var S=N.createElement({S:"div",
Ky:["iv-branding-context-name"],l_:p.channel_name}),O=N.createElement({S:"div",Ky:["iv-branding-context-subscribe"]}),P=p.standalone_subscribe_button_data;P&&(N.T=new g.zG(P.subscribeText,P.subscribeCount,P.unsubscribeText,P.unsubscribeCount,!!P.enabled,!!P.classic,p.channel_id,!!P.subscribed,P.feature,p.session_data.itct,N.context.D,!1),N.T.Rj(O));var W=N.createElement({S:"div",Ky:["iv-branding-context-subscribe-caret"]}),X=N.createElement({S:"div",Ky:["branding-context-container-inner"]});X.appendChild(W);
X.appendChild(S);X.appendChild(O);g.Qx(X,!1);var l=N.createElement({S:"div",Ky:["branding-context-container-outer"]});l.appendChild(X);g.TP(l,"right",p.image_width+"px");g.l9(N.fI(),l);N.X=new g.k6(function(){t5V(N,X,l)},500);
g.C(N,N.X);N.context.T.listen(N.fI(),"mouseover",function(){ujG(N,X,l,W,p.image_height)});
N.context.T.listen(N.fI(),"mouseout",function(){N.X.start()})}},ujG=function(N,p,S,O,P){N.X.stop();
if(!N.G){var W=g.aS(p);N.T||(p.style.width=g.$g(W.width,!0),S.style.width=g.$g(W.width,!0));g.TP(O,"top",W.height-Math.max(Math.min(W.height,P)/2+10,20)+"px");g.TP(O,"right","1px");N.G=!0;g.Qx(p,!0);N.K=new g.k6(function(){g.WF(this.fI(),"iv-branding-active")},0,N);
N.K.start()}},t5V=function(N,p,S){g.fE(N.fI(),"iv-branding-active");
N.N=new g.k6(function(){g.Qx(p,!1);N.T||(S.style.width=g.$g(0,!0))},250);
N.N.start();N.G=!1},RDY=function(N,p,S,O,P,W,X){this.T=N;
this.X=p;this.aj=S;this.videoData=O;this.logger=P;this.D=W;this.B=X},I8Y=function(N,p,S){lk.call(this,N,p,S);
var O=this;this.Y=this.isCollapsed=this.W=!1;this.N=5E3;this.B=this.X=this.T=this.G=null;this.j=this.createElement({S:"div",Ky:["iv-promo-contents"]});this.K=new g.k6(function(){O.T.setAttribute("aria-hidden","true");g.Qx(O.X,!1);g.Qx(O.B,!0)},700,this);
g.C(this,this.K)},Zwf=function(N){var p=N.annotation.data;
if(N.annotation.style==="cta")var S=6;else if(N.annotation.style==="video"||N.annotation.style==="playlist")S=7;N.N=p.collapsedelay_ms||N.N;var O=["iv-promo","iv-promo-inactive"];N.fI().setAttribute("aria-hidden","true");N.fI().setAttribute("aria-label","Promotion");N.fI().tabIndex=0;var P=N.annotation.MQ(),W=p.image_url;if(W){var X=N.createElement({S:"div",Ky:["iv-promo-img","iv-click-target"]});W=N.createElement({S:"img",V:{src:W,"aria-hidden":"true"}});X.appendChild(W);p.video_duration&&!p.is_live?
(W=N.createElement({S:"span",Z:"iv-promo-video-duration",l_:p.video_duration}),X.appendChild(W)):p.playlist_length&&(W=N.createElement({S:"span",Z:"iv-promo-playlist-length",l_:p.playlist_length.toString()}),X.appendChild(W));P&&NM(N,X,P,N.annotation.id,p.session_data,void 0,S)}P?(W=N.createElement({S:"a",Z:"iv-promo-txt"}),g.e5(W,RV(P)),N.T=W):N.T=N.createElement({S:"div",Z:"iv-promo-txt"});switch(N.annotation.style){case "cta":case "website":var l=N.createElement({S:"p",L:[{S:"strong",l_:p.text_line_1}]});
var b=N.createElement({S:"p",L:[{S:"span",Z:"iv-promo-link",l_:p.text_line_2}]});if(W=p.text_line_3){O.push("iv-promo-website-card-cta-redesign");var h=N.createElement({S:"button",Ky:["iv-promo-round-expand-icon","ytp-button"]});W=N.createElement({S:"button",Ky:["iv-button","iv-promo-button"],L:[{S:"span",Z:"iv-button-content",l_:W}]});var x=N.createElement({S:"div",Z:"iv-promo-button-container"});x.appendChild(W);P&&NM(N,N.fI(),P,N.annotation.id,p.session_data,void 0,S)}g.WF(N.T,"iv-click-target");
P&&NM(N,N.T,P,N.annotation.id,p.session_data,void 0,S);break;case "playlist":case "video":l=N.createElement({S:"p",L:[{S:"span",l_:p.text_line_1}]}),b=N.createElement({S:"p",L:[{S:"strong",l_:p.text_line_2}]}),p.is_live&&(l=b,b=N.createElement({S:"span",Ky:["yt-badge","iv-promo-badge-live"],l_:"LIVE NOW"})),g.WF(N.T,"iv-click-target"),P&&NM(N,N.T,P,N.annotation.id,p.session_data,void 0,S),O.push("iv-promo-video")}l&&N.T.appendChild(l);b&&N.T.appendChild(b);N.j.appendChild(N.T);x&&N.j.appendChild(x);
S=N.createElement({S:"div",Z:"iv-promo-actions"});N.B=N.createElement({S:"button",Ky:["iv-promo-expand","ytp-button"]});N.B.title="Expand";N.context.T.listen(N.B,"click",function(y){Djs(N,5E3,y)});
S.appendChild(N.B);g.Qx(N.B,!1);N.context.T.listen(N.fI(),"mouseover",N.g1,N);N.context.T.listen(N.fI(),"mouseout",N.sK,N);N.context.T.listen(N.fI(),"touchend",function(y){Djs(N,5E3,y)});
N.X=N.createElement({S:"button",Ky:["iv-promo-close","ytp-button"]});N.X.title="Close";N.context.T.listen(N.X,"click",N.annotation.style==="cta"&&p.text_line_3?N.kX:N.zt,N);S.appendChild(N.X);g.Xi(N.fI(),O);X&&(g.l9(N.fI(),X),h&&X.appendChild(h));g.l9(N.fI(),N.j);g.l9(N.fI(),S)},Djs=function(N,p,S){S.stopPropagation();
kNY(N);qcQ(N,p);N.T.focus()},NDd=function(N){N.isCollapsed||N.Y||N.G||(g.WF(N.fI(),"iv-promo-collapsed"),N.isCollapsed=!0,N.K.start())},kNY=function(N){N.K.stop();
N.isCollapsed&&(g.lS(N.fI(),["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),N.isCollapsed=!1,N.T&&N.T.removeAttribute("aria-hidden"),g.Qx(N.B,!1),g.Qx(N.X,!0))},qcQ=function(N,p){N.G||(N.G=g.ck(function(){pxV(this);
NDd(this)},p,N))},pxV=function(N){N.G&&(g.M6.clearTimeout(N.G),N.G=null)},oBl=function(N){this.D=N},xjY=function(N,p,S){p&&(S?jO(N,p.map(function(O){return g.rs(O,S)})):jO(N,p))},jO=function(N,p,S,O){var P=1,W=void 0,X=-1;
if(S){var l=!1;W=function(){P--;P||l||(clearTimeout(X),l=!0,S())};
X=setTimeout(function(){l=!0;S()},1E3)}p=g.z(p||[]);
for(var b=p.next();!b.done;b=p.next())b=b.value,P++,g.tC(b,W);O&&(P++,O!==0&&N.D.sendVideoStatsEngageEvent(O,W))},SmE=function(N){g.dg.call(this,N);
var p=this;this.u_=this.Y=!1;this.loadNumber=0;this.N={};this.logger=new oBl(this.player);this.G=new g.Ke(this);this.K=this.j=null;this.events=new g.Ke(this);this.s$=this.W=this.T=null;this.zk=[];g.C(this,this.G);this.G.C(this.player,"onVideoAreaChange",function(){p.publish("onVideoAreaChange")});
this.G.C(this.player,"onHideControls",function(){p.publish("onHideControls")});
this.G.C(this.player,"onShowControls",function(){p.publish("onShowControls")});
this.G.C(this.player,"resize",function(O){p.publish("resize",O)});
this.G.C(this.player,"presentingplayerstatechange",function(O){p.publish("presentingplayerstatechange",O)});
this.subscribe("presentingplayerstatechange",this.oy,this);this.subscribe("resize",this.EH,this);this.player.J().i_.subscribe("vast_info_card_add",this.xi,this);g.C(this,this.events);this.py=this.createElement({S:"div",Z:"video-custom-annotations"});this.B=new g.R({S:"div",Ky:["ytp-player-content","ytp-iv-player-content"]});g.C(this,this.B);g.IB(this.player,this.B.element,4);this.B.hide();this.X=new g.R({S:"div",Ky:["ytp-iv-video-content"]});g.C(this,this.X);N=this.createElement({S:"div",Z:"video-annotations"});
N.appendChild(this.py);this.X.element.appendChild(N);this.bI()&&this.load();var S=this.createElement({S:"style"});(g.kB("HEAD")[0]||document.body).appendChild(S);this.addOnDisposeCallback(function(){g.si(S)});
if(N=S.sheet)N.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),N.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),N.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),N.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),N.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),N.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),N.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),N.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),N.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),N.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},OBE=function(N){N=N.createElement({S:"div",
Ky:["annotation","annotation-type-custom"]});g.Qx(N,!1);return N},P2q=function(N,p){p=!p.isCued()&&!g.Z(p,1024);
N.B.Ea(p);N.X.Ea(p)},WRG=function(N,p,S){N.Y=!0;
N.K=g.m3(p,S)},Xxq=function(N,p){for(var S={},O=g.z(p.attributes),P=O.next();!P.done;P=O.next())P=P.value,S[P.name]=P.nodeValue;
for(O=0;O<p.childNodes.length;O++)if(P=p.childNodes[O],g.Cs(P)&&P.nodeType==1){if(S[P.tagName])var W=S[P.tagName];else if(P.tagName==="data"){P.childNodes.length>0&&(W=P.childNodes[0].nodeValue,S[P.tagName]=typeof W==="string"?W.trim():W);continue}else W=[],S[P.tagName]=W;P&&P.tagName==="TEXT"?P.childNodes.length===1&&P.childNodes[0].nodeType===3?W.push(P.childNodes[0].nodeValue):W.push(""):P&&W.push(Xxq(N,P))}return S},jYC=function(N){var p=N.player.getVideoData();
if(p.Np){var S=N.player.J().i_.get(p.videoId);if(S){var O={format:"XML",urlParams:{},method:"POST",withCredentials:!0,onFinish:function(P,W,X){P=N.loadNumber;W=p.videoId;N.loaded&&N.loadNumber===P&&N.player.getVideoData().videoId===W&&(X=g.xw(X)&&X.responseXML?X.responseXML:null)&&f_G(N,X)}};
g.pR()&&(O.onFinish=l_t(N,O.onFinish));O.postParams={ic_only:"1"};bBG(O,S);N.Y=!0;g.m3(p.Np,O)}}},bBG=function(N,p){N.method="POST";
N.postParams=N.postParams||{};p.Tv&&(N.postParams.ic_coll=p.Tv);p.gk&&(N.postParams.ic_xml=p.gk);p.fV&&(N.postParams.ic_track=p.fV)},sYQ=function(N){var p=new g.R({S:"div"});
g.Qx(p.element,!1);var S=new l8q(N.player,p.element,sV(N));g.C(S,p);p.Rj(N.B.element);S.wf();return S},x1Q=function(N,p){var S,O;
if(p=(S=p.getWatchNextResponse())==null?void 0:(O=S.cards)==null?void 0:O.cardCollectionRenderer)N.u_=!0,hvl(N,p),p.headerText&&N.s$&&(S=g.vn(p.headerText),N.s$.setAttribute("title",S))},sV=function(N){if(!N.W){var p=new a6y(N);
g.C(N,p);var S=new g.an(N);g.C(N,S);N.W=new RDY(p,S,N.player.J(),N.player.getVideoData(),N.logger,N.player,N.NK)}return N.W},f_G=function(N,p){var S=!1,O=p.getElementsByTagName("annotations");
if(O&&!(O.length<1)&&(O=O[0].getAttribute("itct"))){var P=g.UP();if(P){var W=g.m7();W&&g.kc(g.wO)(void 0,P,W,[g.$k(O)])}}p=p.getElementsByTagName("annotation");for(O=0;O<p.length;O++){W=Xxq(N,p[O]);P=null;try{if(W){var X=W.id,l=/.+/;var b=typeof X==="string"&&l!=null&&X!=null&&X.match(l)?X:"";var h=wP(W.type,y6t),x=wP(W.style,VtV),y=ubR(W.data),V=y.length!==0?JSON.parse(y):{};var L=W.action;W=kgf;if(L==null)var T=null;else if(g.eA(L)){l=[];for(var E=g.z(L),m=E.next();!m.done;m=E.next()){var H=W(m.value);
H&&l.push(H)}T=l}else{var Q=W(L);T=Q?[Q]:[]}P=b&&h?new qME(b,h,x,T,V):null}else P=null}catch(oH){}if(P)if(P.type==="branding"||P.type==="promotion"){W=N;l=P;var n=OBE(W),K=null;switch(l.type){case "branding":if(W.player.J().Fl)break;W.B.element.appendChild(n);K=new bk(n,sV(W),l);break;case "promotion":g.IB(W.player,n,4),K=new I8Y(n,sV(W),l)}K&&K.wf();if(W=K)g.C(N,W),N.N[P.id]=W}else if(P.type==="card"||P.type==="drawer"){N.T||(N.T=sYQ(N),g.C(N,N.T));if(P.type==="card"){n=N.T;var d=(S=P)&&S.data&&
S.data.card_type;P=S.data;if(d)switch(W=P.tracking||{},W={cW:W.impression,click:W.click,close:W.close,Ch:W.teaser_impression,lq:W.teaser_click},l=P.tracking_params||{},K=null,d){case "collaborator":S={id:S.id,timestamp:P.timestamp||0,type:P.card_type,teaserText:P.teaser_text,teaserDurationMs:P.teaser_duration_ms,startMs:P.start_ms,autoOpen:P.auto_open||!1,sessionData:P.session_data||{},sponsored:P.sponsored||!1,kN:W,L4:l.card?g.$k(l.card):null,Cn:l.teaser?g.$k(l.teaser):null,tF:l.icon?g.$k(l.icon):
null,channelId:P.channel_id,customMessage:P.custom_message?P.custom_message:null,profileImageUrl:P.image_url,title:P.title,metaInfo:P.meta_info,url:IV({pause_on_navigation:P.pause_on_navigation,target:P.target||"new",value:P.url}),onClickCommand:null};OV(n,S);break;case "playlist":S={id:S.id,timestamp:P.timestamp||0,type:P.card_type,teaserText:P.teaser_text,teaserDurationMs:P.teaser_duration_ms,startMs:P.start_ms,autoOpen:P.auto_open||!1,sessionData:P.session_data||{},sponsored:P.sponsored||!1,kN:W,
L4:l.card?g.$k(l.card):null,Cn:l.teaser?g.$k(l.teaser):null,tF:l.icon?g.$k(l.icon):null,I8:P.image_url,playlistVideoCount:P.playlist_video_count,customMessage:P.custom_message?P.custom_message:null,title:P.title,metaInfo:P.meta_info,url:IV({pause_on_navigation:P.pause_on_navigation,target:P.target||"new",value:P.url}),onClickCommand:null};OV(n,S);break;case "productListing":P.signin_url&&(K=IV({target:"current",value:P.signin_url}));d=[];for(var D=P.offers||[],u=0;u<D.length;u++)d.push(new PoB(g.Wx(D[u].merchant),
g.Wx(D[u].price)));S={id:S.id,timestamp:P.timestamp||0,type:P.card_type,teaserText:P.teaser_text,teaserDurationMs:P.teaser_duration_ms,startMs:P.start_ms,autoOpen:P.auto_open||!1,sessionData:P.session_data||{},sponsored:P.sponsored||!1,kN:W,L4:l.card?g.$k(l.card):null,Cn:l.teaser?g.$k(l.teaser):null,tF:l.icon?g.$k(l.icon):null,imageUrl:P.image_url,displayDomain:P.display_domain?P.display_domain:null,showLinkIcon:!!P.show_link_icon,jy:P.button_icon_url?P.button_icon_url:null,title:P.title,customMessage:P.custom_message?
P.custom_message:null,url:IV({pause_on_navigation:P.pause_on_navigation,target:P.target||"new",value:P.url}),U__:K,PWm:P.signin_title?P.signin_title:void 0,D_b:P.signin_message?P.signin_message:void 0,offers:d,onClickCommand:null};OV(n,S);break;case "simple":S={id:S.id,timestamp:P.timestamp||0,type:P.card_type,teaserText:P.teaser_text,teaserDurationMs:P.teaser_duration_ms,startMs:P.start_ms,autoOpen:P.auto_open||!1,sessionData:P.session_data||{},sponsored:P.sponsored||!1,kN:W,L4:l.card?g.$k(l.card):
null,Cn:l.teaser?g.$k(l.teaser):null,tF:l.icon?g.$k(l.icon):null,imageUrl:P.image_url,displayDomain:P.display_domain?P.display_domain:null,showLinkIcon:!!P.show_link_icon,jy:P.button_icon_url?P.button_icon_url:null,title:P.title,customMessage:P.custom_message?P.custom_message:null,url:IV({pause_on_navigation:P.pause_on_navigation,target:P.target||"new",value:P.url}),onClickCommand:null};OV(n,S);break;case "video":S={id:S.id,timestamp:P.timestamp||0,type:P.card_type,teaserText:P.teaser_text,teaserDurationMs:P.teaser_duration_ms,
startMs:P.start_ms,autoOpen:P.auto_open||!1,sessionData:P.session_data||{},sponsored:P.sponsored||!1,kN:W,L4:l.card?g.$k(l.card):null,Cn:l.teaser?g.$k(l.teaser):null,tF:l.icon?g.$k(l.icon):null,I8:P.image_url,videoDuration:P.video_duration||null,customMessage:P.custom_message?P.custom_message:null,title:P.title,metaInfo:P.meta_info,isLiveNow:!!P.is_live_now,url:IV({pause_on_navigation:P.pause_on_navigation,target:P.target||"new",value:P.url}),onClickCommand:null},OV(n,S)}}else bw0(N.T,P);S=!0}}S&&
(gP(N.player),N.EH())},hvl=function(N,p){var S=!1;
N.T||(N.T=sYQ(N),g.C(N,N.T));for(var O=g.z(p.cards||[]),P=O.next();!P.done;P=O.next())P=P.value,P.cardRenderer&&(jwY(N.T,P.cardRenderer),S=!0);if(S){var W;(W=N.player.getVideoData())!=null&&g.pv(W)||(S=N.T,O=p.headerText?g.vn(p.headerText):"",g.xY(S.wF,O),S.Y&&S.Y.setAttribute("title",O),S.context.videoData.eventId&&(S.eventId=S.context.videoData.eventId),S.xO=p.trackingParams?g.$k(p.trackingParams):null,S.j=p.closeButton.infoCardIconRenderer.trackingParams?g.$k(p.closeButton.infoCardIconRenderer.trackingParams):
null,S.tF=p.icon.infoCardIconRenderer.trackingParams?g.$k(p.icon.infoCardIconRenderer.trackingParams):null,N.EH());gP(N.player)}},LRs=function(N,p,S,O,P){if(!N.player.J().Fl){var W=[];
p.navigationEndpoint&&g.t(p.navigationEndpoint,g.mv)&&g.t(p.navigationEndpoint,g.mv).browseId&&W.push(new I6t("openUrl","click",new wXE("/channel/"+g.t(p.navigationEndpoint,g.mv).browseId,"new",!0,!0)));var X=p.watermark.thumbnails[0];O={channel_name:p.channelName,end_ms:p.endTimeMs,image_height:X.height,image_type:1,image_url:X.url,image_width:X.width,is_mobile:!1,session_data:{annotation_id:S,ei:P,feature:"iv",itct:p.trackingParams,src_vid:O},start_ms:p.startTimeMs};if(p.subscribeButton&&g.t(p.subscribeButton,
g.Un)){O.channel_id=g.t(p.subscribeButton,g.Un).channelId;var l;p=g.t(p.subscribeButton,g.Un);X=P=null;p.subscribed?(p.subscriberCountWithUnsubscribeText&&(P=g.vn(p.subscriberCountWithUnsubscribeText)),p.subscriberCountText&&(X=g.vn(p.subscriberCountText))):(p.subscriberCountText&&(P=g.vn(p.subscriberCountText)),p.subscriberCountWithSubscribeText&&(X=g.vn(p.subscriberCountWithSubscribeText)));var b,h=((b=g.t((l=p.signInEndpoint)==null?void 0:l.commandMetadata,g.Jk))==null?void 0:b.url)||"";l={subscribeText:g.vn(p.unsubscribedButtonText),
subscribeCount:P||"",unsubscribeText:g.vn(p.subscribedButtonText),unsubscribeCount:X||"",enabled:p.enabled||!1,classic:!1,subscribed:p.subscribed||!1,feature:"iv",signInUrl:h};O.standalone_subscribe_button_data=l}W=new qME(S,"branding","branding",W,O);l=OBE(N);N.B.element.appendChild(l);W=new bk(l,sV(N),W);W.wf();g.C(W,W);N.N[S]=W}},l_t=function(N,p){return function(){var S=g.U_.apply(0,arguments);
N.wH()||N.zk.push(g.tY.ju(function(){p.apply(null,g.J(S))}))}},TDC=function(N){return N==="annotation-editor"||N==="live-dashboard"};
g.d3.prototype.Kt=g.SA(35,function(N,p){var S=g.pA(this.zB());S&&S.Kt(N,p)});
var FF={},no=null;g.Db(M9,g.jl);g.f=M9.prototype;g.f.getDuration=function(){return this.duration};
g.f.play=function(N){if(N||this.T==0)this.progress=0,this.coords=this.B;else if(this.isPlaying())return!1;rP(this);this.startTime=N=g.IH();this.isPaused()&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.G=this.startTime;this.progress||this.qL();this.Du("play");this.isPaused()&&this.Du("resume");this.T=1;var p=g.t8(this);p in FF||(FF[p]=this);ETY();$pG(this,N);return!0};
g.f.stop=function(N){rP(this);this.T=0;N&&(this.progress=1);JsY(this,this.progress);this.onStop();this.kx()};
g.f.pause=function(){this.isPlaying()&&(rP(this),this.T=-1,this.Du("pause"))};
g.f.BP=function(){this.T==0||this.stop(!1);this.Du("destroy");M9.WG.BP.call(this)};
g.f.destroy=function(){this.dispose()};
g.f.rT=function(){this.Du("animate")};
g.f.Du=function(N){this.dispatchEvent(new mpY(N,this))};
g.Db(mpY,g.Ad);g.Db(Ko,M9);Ko.prototype.X=function(){};
Ko.prototype.rT=function(){this.X();Ko.WG.rT.call(this)};
Ko.prototype.kx=function(){this.X();Ko.WG.kx.call(this)};
Ko.prototype.qL=function(){this.X();Ko.WG.qL.call(this)};
g.Db(Upt,Ko);Upt.prototype.X=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};g.B(a6y,g.e);g.f=a6y.prototype;g.f.listen=function(N,p,S,O){S=(0,g.uX)(S,O||this.B);N=g.za(N,p,S);this.T.push(N);return N};
g.f.Um=function(N,p,S,O){S=(0,g.uX)(S,O||this.B);N=BXq(N,p,S);this.T.push(N);return N};
g.f.xK=function(N){g.Er(N);g.I0(this.T,N)};
g.f.removeAll=function(){g.Er(this.T);this.T.length=0};
g.f.BP=function(){this.removeAll();g.e.prototype.BP.call(this)};g.B(csl,g.dg);g.f=csl.prototype;g.f.load=function(){g.dg.prototype.load.call(this);if(!dP(this)){var N=g.jWy(this.player.getVideoData());N?(N=gT0(N,FNG(this)),eF(this,N,!1)):nTy(this)}};
g.f.unload=function(){eF(this,null);this.G&&(this.G.abort(),this.G=null);g.dg.prototype.unload.call(this)};
g.f.E$=function(N,p){return dP(this)?N==="loadCustomEndscreenRenderer"?(N=gT0(p,"new"),eF(this,N),!0):null:null};
g.f.getOptions=function(){return dP(this)?["loadCustomEndscreenRenderer"]:[]};
g.f.I4=function(){if(this.endscreen&&this.endscreen.elements){var N=this.player.getVideoContentRect();if(N&&N.width!==0&&N.height!==0){var p=this.player.getPlayerSize();if(p&&p.width!==0&&p.height!==0){var S=N.width/N.height;var O=0;for(var P=-1,W=0;W<vBs.length;W++){var X=Math.abs(p.width-vBs[W]);if(P===-1||O>=X)P=W,O=X}O=BDY[P];this.X&&g.TP(this.X.element,"outline-width",Math.max(p.width,p.height)+"px");for(p=0;p<this.endscreen.elements.length;++p)if(W=this.endscreen.elements[p].id,P=this.T[W],
X=this.N[W],P&&X){var l=X.width*S/X.aspectRatio,b=Math.round(X.width*N.width);W=Math.round(l*N.height);var h=N.left+Math.round(X.left*N.width),x=N.top+Math.round(X.top*N.height);g.iR(P.element,b,W);g.JE(P.element,h,x);g.lS(P.element,zvs);b>256||W>256?g.WF(P.element,"ytp-ce-large-round"):b>96||W>96?g.WF(P.element,"ytp-ce-medium-round"):g.WF(P.element,"ytp-ce-small-round");g.lS(P.element,EB0);b=X.left+X.width/2;X=X.top+l/2;g.WF(P.element,b<=.5&&X<=.5?"ytp-ce-top-left-quad":b>.5&&X<=.5?"ytp-ce-top-right-quad":
b<=.5&&X>.5?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.lS(P.element,BDY);g.WF(P.element,O);(P=g.NL(document,"div","ytp-ce-expanding-overlay-body",P.element)[0])&&g.TP(P,"height",W+"px")}}}}};
g.f.onCueRangeEnter=function(N){if(this.endscreen)if(N.getId()==="ytp-ce-in-endscreen")uc(this,this.endscreen.impressionUrls),(N=g.UP())&&this.endscreen.visualElement&&g.ob(N,this.endscreen.visualElement),this.B&&(g.WF(this.B,"ytp-ce-element-show"),this.B.removeAttribute("aria-hidden"));else{N=N.getId().substring(15);var p=this.T[N],S=this.N[N];g.WF(p.element,"ytp-ce-element-show");p.element.removeAttribute("aria-hidden");p=this.player.getRootNode();g.WF(p,"ytp-ce-shown");uc(this,S.impressionUrls);
(p=g.UP())&&g.ob(p,S.visualElement);this.player.J().j&&this.player.YO("endscreenelementshown",N)}};
g.f.onCueRangeExit=function(N){if(N.getId()==="ytp-ce-in-endscreen")this.B&&(g.fE(this.B,"ytp-ce-element-show"),this.B.setAttribute("aria-hidden","true"));else{N=N.getId().substring(15);var p=this.T[N];g.fE(p.element,"ytp-ce-element-show");p.element.setAttribute("aria-hidden","true");p=this.player.getRootNode();g.fE(p,"ytp-ce-shown");this.player.J().j&&this.player.YO("endscreenelementhidden",N)}};
g.f.Pkj=function(N){var p=this;N.target===window&&(new g.k6(function(){for(var S=g.z(Object.values(p.T)),O=S.next();!O.done;O=S.next())g.lS(O.value.element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
g.f.Ea=function(N){for(var p=g.z(Object.values(this.T)),S=p.next();!S.done;S=p.next())S=S.value,N?S.element.setAttribute("hidden",""):S.element.removeAttribute("hidden")};
g.f.WuP=function(N){this.B&&this.player.getRootNode().removeChild(this.B);N&&(g.WF(N,"ytp-ce-hide-button-container"),this.B=N,g.IB(this.player,this.B,4))};
var vBs=[346,426,470,506,570,640,853,1280,1920],BDY="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),EB0=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"],zvs=["ytp-ce-small-round","ytp-ce-medium-round","ytp-ce-large-round"];var RgQ={cEH:"current",S0b:"new"};var Dpf={CLOSE:"close",Nno:"openUrl",SUBSCRIBE:"subscribe"},ZmB={b7p:"click",CLOSE:"close",And:"hidden",K2S:"rollOut",iwv:"rollOver",oSB:"shown"};qME.prototype.MQ=function(){var N=Nbf(this,function(p){return p.type==="openUrl"&&p.url!=null});
return N?N.url:null};
var VtV={yuo:"anchored",BS:"branding",CHANNEL:"channel",dbv:"cta",Fbk:"highlightText",IWm:"label",PLAYLIST:"playlist",POPUP:"popup",tsC:"speech",SUBSCRIBE:"subscribe",Vsj:"title",VIDEO:"video",bSv:"website"},y6t={BS:"branding",i7j:"card",O3C:"drawer",aWH:"highlight",kQb:"marker",F2P:"promotion",TEXT:"text",OlC:"widget"};g.B(q9,g.e);g.f=q9.prototype;g.f.addCueRange=function(N,p,S,O,P){N=new g.WY(N,p,{id:S,namespace:"annotations_module"});O&&this.Np.set(N,O);P&&this.vP.set(N,P);this.context.D.cD([N],1)};
g.f.wf=function(){this.context.B.subscribe("resize",this.VQ,this)};
g.f.fI=function(){return this.element};
g.f.S2=function(N,p,S,O,P,W){if(this.WP)return!1;W&&(W.stopPropagation(),W.preventDefault());this.navigate(N,S,O,P);return!1};
g.f.show=function(){};
g.f.hide=function(){};
g.f.destroy=function(){g.si(this.fI())};
g.f.VQ=function(){};
g.f.navigate=function(N,p,S,O){var P=this,W=RV(N);if(W){var X=XUd(W,N.target),l=function(){N.T&&P.context.D.pauseVideo();var b=P.context.videoData.JF||!1,h=g.OB(W||"");b&&h&&(h.v||h.list)?P.context.D.P_(h.v,p,h.list,!1):g.Ro(W||"",X==="current"?"_top":void 0,p)};
X==="new"&&(l(),l=null);jO(this.context.logger,S,l,O);WeC(W)||(S=g.UP(),O=p.itct,S&&O&&g.Pn(S,g.$k(O)))}};
g.f.BP=function(){this.Np.clear();this.vP.clear();g.e.prototype.BP.call(this)};
g.f.createElement=function(N){N=new g.R(N);g.C(this,N);return N.element};g.B(l8q,q9);g.f=l8q.prototype;g.f.Nk=function(){this.zk&&OV(this,this.zk)};
g.f.isAvailable=function(){var N;if(N=!!this.cards.length)(N=this.D.getRootNode())?(N=g.aS(N),N=173<N.width&&173<N.height):N=!1;return N};
g.f.VQ=function(){var N=this.isAvailable();g.Qx(this.fI(),N);g.bS(this.context.D.getRootNode(),g.Cz.IV_DRAWER_ENABLED,N);gP(this.D)};
g.f.destroy=function(){this.D.Kt(!1);try{this.D.getRootNode().removeChild(this.G)}catch(N){}g.bV(this.u_);g.aR(this.rH);this.jS&&this.jS.dispose();this.K&&this.K.dispose();q9.prototype.destroy.call(this)};
g.f.hp=function(){var N=this;this.context.T.listen(g.pW("iv-drawer-close-button",this.G),"click",this.Er,this);this.context.T.listen(this.B,"touchend",function(){N.eS.start()});
this.context.T.listen(this.B,"scroll",this.M0,this);this.context.B.subscribe("onHideControls",function(){N.i_=!0});
this.context.B.subscribe("onShowControls",function(){N.i_=!1});
this.context.B.subscribe("onVideoAreaChange",function(){N.i_=g.PF(N.D.getRootNode(),"ytp-autohide")});
this.u_.push(g.lV("iv-button-shown",this.fA,this));this.u_.push(g.lV("iv-button-hidden",this.X1,this));rLy(this)};
g.f.findLastIndex=function(N){if(this.cards.length===0)return 0;var p=g.uG(this.cards,function(S){return N.je.startMs>S.je.startMs||N.je.startMs===S.je.startMs&&N.je.timestamp>=S.je.timestamp?!0:!1});
return p===-1?0:p+1};
g.f.Er=function(){if(this.X){jO(this.context.logger,fS(this).kN.close);var N=g.UP();N&&this.j&&g.Pn(N,this.j);SO(this)}};
g.f.M0=function(){g.bS(this.G,"iv-drawer-scrolled",this.B.scrollTop>0)};
g.f.fA=function(){var N=g.UP(),p=fS(this);p=p?p.tF:this.tF;N&&p&&g.Ss(N,[p])};
g.f.X1=function(){var N=g.UP(),p=fS(this);p=p?p.tF:this.tF;N&&p&&g.OU(N,[p])};
g.f.vO=function(){var N=fS(this);jO(this.context.logger,N.kN.Ch);var p=g.UP();if(p&&N)if(this.D.U("web_infocards_teaser_show_logging_fix")){var S=[];N.Cn&&S.push(N.Cn);N.tF&&S.push(N.tF);S.length>0&&g.Ss(p,S)}else g.Ss(p,[N.Cn,N.tF])};
g.f.Rf=function(){var N=g.UP(),p=fS(this);N&&p&&g.OU(N,[p.Cn])};
g.f.nj=function(N){var p=fS(this),S=g.UP();this.T?N?(N=this.context.logger,jO(N,p.kN.lq),N.D.sendVideoStatsEngageEvent(4,void 0),S&&p.Cn&&g.Pn(S,p.Cn)):(N=this.context.logger,jO(N,p.kN.lq),N.D.sendVideoStatsEngageEvent(4,void 0),S&&p.tF&&g.Pn(S,p.tF)):(N=this.context.logger,jO(N,p.kN.lq),N.D.sendVideoStatsEngageEvent(4,void 0),S&&this.tF&&g.Pn(S,this.tF))};g.B(lk,q9);lk.prototype.wf=function(){q9.prototype.wf.call(this);CoR(this)};
lk.prototype.show=function(){q9.prototype.show.call(this);var N=g.UP(),p=this.annotation.data;N&&p&&(p=p.session_data)&&g.Ss(N,[g.$k(p.itct)])};
lk.prototype.hide=function(){q9.prototype.hide.call(this);var N=g.UP(),p=this.annotation.data;N&&p&&(p=p.session_data)&&g.OU(N,[g.$k(p.itct)])};g.B(bk,lk);
bk.prototype.show=function(){if(!this.isActive){lk.prototype.show.call(this);if(!this.j){g.WF(this.fI(),"iv-branding");var N=this.annotation.data;this.B=this.createElement({S:"img",Ky:["branding-img","iv-click-target"],V:{"aria-label":"Channel watermark",src:N.image_url,width:N.image_width,height:N.image_height}});g.Qx(this.B,!1);var p=this.createElement({S:"button",Ky:["branding-img-container","ytp-button"]});p.appendChild(this.B);this.fI().appendChild(p);var S=this.annotation.MQ();S&&NM(this,p,
S,this.annotation.id,N.session_data);this.context.D.U("disable_branding_context")||wUE(this,N);this.j=!0}g.Qx(this.fI(),!0);this.isActive=!0;if(this.B){try{AL0(this,this.B)}catch(O){}g.WF(this.context.D.getRootNode(),"ytp-branding-shown");this.context.D.getRootNode().style.setProperty("--branding-image-width",this.B.getAttribute("width")+"px")}}};
bk.prototype.hide=function(){this.isActive&&(lk.prototype.hide.call(this),g.Qx(this.fI(),!1),this.isActive=!1,g.fE(this.context.D.getRootNode(),"ytp-branding-shown"))};
bk.prototype.destroy=function(){this.T&&(this.T.dispose(),this.T=null);g.fE(this.context.D.getRootNode(),"ytp-branding-shown");lk.prototype.destroy.call(this)};g.B(I8Y,lk);g.f=I8Y.prototype;g.f.show=function(){this.isActive||(lk.prototype.show.call(this),this.W||(Zwf(this),this.W=!0),g.Qx(this.fI(),!0),g.ck(function(){g.fE(this.fI(),"iv-promo-inactive")},100,this),this.fI().removeAttribute("aria-hidden"),this.isActive=!0,pxV(this),kNY(this),qcQ(this,this.N))};
g.f.hide=function(){this.isActive&&(g.WF(this.fI(),"iv-promo-inactive"),this.isActive=!1,this.fI().setAttribute("aria-hidden","true"))};
g.f.S2=function(N,p,S,O,P,W){return this.isCollapsed?!1:lk.prototype.S2.call(this,N,p,S,O,P,W)};
g.f.g1=function(N){this.Y=!0;Djs(this,500,N)};
g.f.sK=function(){this.Y=!1;NDd(this)};
g.f.zt=function(N){N.stopPropagation();this.hide()};
g.f.kX=function(N){N.stopPropagation();pxV(this);this.isCollapsed=!0;g.WF(this.fI(),"iv-promo-collapsed-no-delay");this.K.start()};
g.f.destroy=function(){this.K.dispose();lk.prototype.destroy.call(this)};g.B(SmE,g.dg);g.f=SmE.prototype;g.f.E$=function(N,p){if(!TDC(this.player.J().playerStyle))return null;switch(N){case "loadCustomAnnotationsXml":return(N=g.pX(p))&&f_G(this,N),!0;case "removeCustomAnnotationById":return p&&this.T&&(hDC(this.T,p),gP(this.player)),!0}return null};
g.f.getOptions=function(){return TDC(this.player.J().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.f.bI=function(){var N=this.player.J(),p=this.player.getVideoData(),S=N.annotationsLoadPolicy||p.annotationsLoadPolicy;return g.V8(p)||this.player.isMutedByEmbedsMutedAutoplay()?!1:S===1&&!p.yU||N.i_.get(p.videoId)||g.oB(p)||g.SP(p)?!0:!1};
g.f.EH=function(){if(this.X){var N=this.player.cP().getVideoContentRect(!0);g.iR(this.X.element,N.width,N.height);g.JE(this.X.element,N.left,N.top)}if(this.T){var p=this.player.Me();N=this.T;p=p.width;g.bS(N.G,"iv-drawer-small",p<=426);g.bS(N.G,"iv-drawer-big",p>=1280)}};
g.f.oy=function(N){P2q(this,N.state);g.Z(N.state,2)&&(this.Of()&&this.Jk()&&this.player.getPresentingPlayerType()!==2&&this.ih(!1),this.Kt(!1))};
g.f.load=function(){function N(X){var l=p.loadNumber;p.K=null;p.loaded&&p.loadNumber===l&&p.player.getVideoData().videoId===O&&(X=g.xw(X)&&X.responseXML?X.responseXML:null)&&(f_G(p,X),g.WF(p.player.getRootNode(),"iv-module-loaded"))}
var p=this;g.dg.prototype.load.call(this);P2q(this,this.player.getPlayerStateObject());this.loadNumber++;var S=this.player.getVideoData(),O=S.videoId;g.pR()&&(N=l_t(this,N));var P={format:"XML",onFinish:N,onError:function(){p.K=null},
urlParams:{}};S.isPharma&&(P.urlParams.pharma="1");P.method="POST";P.withCredentials=!0;var W=this.player.J().i_.get(O);W&&bBG(P,W);W=W&&(W.gk||W.Tv);if(!S.Xn||W)S.Np?WRG(this,S.Np,P):(this.j=function(){if(!p.Y)p.onVideoDataChange(P);var X=p.player.getVideoData();(X==null?0:g.pv(X))&&!p.u_&&x1Q(p,X)},this.player.addEventListener("videodatachange",this.j));
g.IB(this.player,this.X.element,4);this.EH();(W=g.oB(S))&&hvl(this,W);(W=g.SP(S))&&W.featuredChannel&&LRs(this,W.featuredChannel,W.annotationId||"branding",S.videoId||null,S.eventId||null);this.s$=g.pW("ytp-cards-button",this.player.getRootNode());g.pv(S)&&x1Q(this,S)};
g.f.onVideoDataChange=function(N){var p=this.player.getVideoData();p.Np&&WRG(this,p.Np,N)};
g.f.unload=function(){this.player.WD("annotations_module");for(var N=g.z(Object.keys(this.N)),p=N.next();!p.done;p=N.next())this.N[p.value].destroy();this.W=null;this.T&&(this.T.destroy(),this.T=null,gP(this.player));this.Y=!1;this.K&&(this.K.abort(),this.K=null);this.u_=!1;this.N={};this.B.hide();g.dg.prototype.unload.call(this);this.X.detach();this.j&&(this.player.removeEventListener("videodatachange",this.j),this.j=null)};
g.f.xi=function(N){N===this.player.getVideoData().videoId&&(this.loaded?jYC(this):this.load())};
g.f.Of=function(){var N;return((N=this.T)==null?void 0:N.isAvailable())||this.u_};
g.f.Jk=function(){return!!this.T&&this.T.X};
g.f.ih=function(N,p,S){p=p===void 0?!1:p;this.Of();this.T&&(N?S?oc(this.T,S,p):oc(this.T,"YOUTUBE_DRAWER_AUTO_OPEN",p):SO(this.T))};
g.f.Kt=function(N,p){this.player.publish(N?"cardsteasershow":"cardsteaserhide",p)};
g.f.BP=function(){this.player.J().i_.unsubscribe("vast_info_card_add",this.xi,this);g.fE(this.player.getRootNode(),g.Cz.IV_DRAWER_OPEN);for(var N=this.zk,p=g.tY,S=0,O=N.length;S<O;S++)p.aU(N[S]);this.zk.length=0;g.dg.prototype.BP.call(this)};
g.f.createElement=function(N){N=new g.R(N);g.C(this,N);return N.element};g.Gc("annotations_module",SmE);g.Gc("creatorendscreen",csl);})(_yt_player);
