(function(g){var window=this;'use strict';var m1Q=function(N,p,S){g.r(function(O){N.B=g.m3(p,S);g.Ls(O)})},hA=function(N){N.isActive()||N.start()},U1V=function(N,p){return p?N.captionsInitialState:"CAPTIONS_INITIAL_STATE_UNKNOWN"},HBy=function(N){return g.wN(N)||N.U("web_enable_caption_language_preference_stickiness")},iBd=function(N,p){var S=new g.bx;
S.languageCode=N.languageCode;S.languageName=N.languageName;S.name=N.name;S.displayName=N.displayName;S.kind=N.kind;S.isDefault=!1;S.T=N.T;S.isTranslateable=N.isTranslateable;S.vssId=N.vssId;S.url=N.url;S.translationLanguage=p;N.xtags&&(S.xtags=N.xtags);N.captionId&&(S.captionId=N.captionId);return S},a_Y=function(N,p){var S,O,P;
return g.r(function(W){if(W.B==1)return S=N+"|"+p,g.F(W,g.kH(),2);if(W.B!=3){O=W.T;if(!O)throw g.zB("gct");return g.F(W,g.ix(O),3)}P=W.T;return W.return(P.get("captions",S))})},QYE=function(N,p,S){a_Y(N,p).then(function(O){O&&S(O.trackData,new g.bx(O.metadata))})},FRV=function(N){if(!gBl.test(N))throw Error("'"+N+"' is not a valid hex color");
N.length==4&&(N=N.replace(c6t,"#$1$1$2$2$3$3"));N=N.toLowerCase();N=parseInt(N.slice(1),16);return[N>>16,N>>8&255,N&255]},nB0=function(){var N=void 0;
N=N===void 0?{}:N;var p="suggest_correction"in g.CKQ?g.CKQ.suggest_correction:"Edit caption";p=p||"";var S={},O;for(O in N){S={mU:S.mU};S.mU=O;var P=function(W){return function(){return String(N[W.mU])}}(S);
p=p.replace(new RegExp("\\$\\{"+S.mU+"\\}","gi"),P);p=p.replace(new RegExp("\\$"+S.mU,"gi"),P)}return p},r6y=function(){return g.n1("yt-player-caption-display-settings")},xF=function(){this.segments=[]},MtC=function(N,p){var S=g.SI(N.segments,p);
S>=0||S<0&&(-S-1)%2===1||(S=-S-1,S>0&&p-N.segments[S-1]===1&&S<N.segments.length&&N.segments[S]-p===1?(g.R0(N.segments,S),g.R0(N.segments,S-1)):S>0&&p-N.segments[S-1]===1?N.segments[S-1]=p:S<N.segments.length&&N.segments[S]-p===1?N.segments[S]=p:(g.pJ(N.segments,S,0,p),g.pJ(N.segments,S+1,0,p)))},KR0=function(N,p,S,O,P,W){g.e.call(this);
this.policy=N;this.player=p;this.u_=S;this.Y=O;this.K=P;this.W=W;this.G=new xF;this.N=-1;this.X=this.B=this.T=null;this.zk=0;this.j=new g.k6(this.YC,1E3,this);this.events=new g.Ke(this);g.C(this,this.j);g.C(this,this.events);this.events.C(p,"SEEK_COMPLETE",this.N$);this.N$();this.YC()},Ym0=function(N){return N.T&&N.T.rX?N.T.rX+N.player.ac()<N.player.getCurrentTime():!1},GqE=function(N,p){if(N.policy.uv&&N.player.SF()){var S=g.KI(p,N.policy,{});
S.set("pot",N.player.SF());S=S.MQ()}else S=g.KI(p,N.policy,{}).MQ();var O={format:"RAW",withCredentials:!0};if(N.policy.i_){O.method="POST";var P=p.G;P&&Object.keys(P).length>0?O.postBody=g.XE(P,g.It):O.postBody=(0,g.m8)([120,0])}N.K&&(O.responseType="arraybuffer");var W=++N.zk,X=(0,g.Hm)();N.X=g.a_(S,O,3,100).then(function(l){if(N.policy.gN&&W%100===1){var b=(0,g.Hm)();N.player.Tk("caprsp",{rn:W,ms:b-X,kb:(l.xhr.responseText.length/1024).toFixed()})}a:{l=l.xhr;N.wH();if(N.B){var h=!(N.K?l.response:
l.responseText)||l.status>=400;if(b=g.mS6(l)){l=g.KI(N.B,N.policy,{});N.B.Xk(l,b);GqE(N,N.B);break a}h?N.player.Tk("capfail",{status:l.status}):(N.player.hE().eb("fcb_r"),b=N.B.Eb[0].Mp,N.Y!=null&&N.N!==b&&(h=N.B.Eb[0],N.K?N.Y(l.response,(h.startTime+N.player.ac())*1E3):N.Y(l.responseText,(h.startTime+N.player.ac())*1E3),N.N=b))}N.B=null;N.X=null}}).IU(function(l){N.B=null;
N.X=null;var b;N.player.Tk("capfail",{rn:W,status:(b=l.xhr)==null?void 0:b.status})});
N.B=p;MtC(N.G,N.B.Eb[0].Mp)},yu=function(N,p){g.CG.call(this,p);
this.B=N;this.D=p;this.X=null;this.N=!1;this.j=g.H$(this.D.J())&&!this.B.isManifestless},evq=function(N,p){var S=[],O;
for(O in N.B.T)if(N.B.T.hasOwnProperty(O)){var P=N.B.T[O];if(g.tm(P,p||null)){var W=P.info.id,X=W,l="."+W,b="",h="";if(P=P.info.captionTrack)W=P.languageCode,X=P.displayName,l=P.vssId,b=P.kind,h=P.id;else{P=W;var x=g.XXB.get(P);x==null&&(x=d1s[P]||d1s[P.replace(/-/g,"_")],g.XXB.set(P,x));P=x;X=P||X}S.push(new g.bx({id:O,languageCode:W,languageName:X,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:l,kind:b,captionId:h}))}}return S},C2C=function(N,p){return p!=null&&p in N.B.T?N.B.T[p]:null},
A6Y=function(N,p,S){var O=[],P;
for(P in N.B.T)if(N.B.T.hasOwnProperty(P)){var W=N.B.T[P];if(g.tm(W,S||null)){var X=W.info.captionTrack;X&&X.languageCode===p&&O.push(W)}}return O.length?O[0]:null},Vu=function(N,p,S,O,P,W,X,l,b,h){var x=h.isInline()&&!0,y={};
Object.assign(y,p);Object.assign(y,N.params);Object.assign(y,S);var V={};Object.assign(V,p.k6);N.params.k6&&Object.assign(V,N.params.k6);Object.assign(V,S.k6);x&&(y.windowOpacity=.6,V.backgroundOpacity=0);y.k6=V;var L=y.o0===1,T=[{S:"span",Z:"captions-text",V:{style:"word-wrap: normal; display: block;"}}],E,m,H;(l=l.yd("caption_edit_on_hover")&&((E=h.getVideoData().getPlayerResponse())==null?void 0:(m=E.captions)==null?void 0:(H=m.playerCaptionsTracklistRenderer)==null?void 0:H.openTranscriptCommand))&&
T.unshift({S:"button",Z:"caption-edit",V:{tabindex:"0","aria-label":nB0()},L:[{S:"svg",V:{fill:"#e3e3e3",height:"100%",viewBox:"5 5 38 38",width:"100%"},L:[{S:"path",V:{d:"M9 39h2.2l24.25-24.25-1.1-1.1-1.1-1.1L9 36.8Zm-3 3v-6.4L35.4 6.2q.85-.85 2.12-.82 1.27.02 2.12.87L41.8 8.4q.85.85.85 2.1t-.85 2.1L12.4 42Zm33.5-31.55L37.45 8.4Zm-4.05 4.3-1.1-1.1-1.1-1.1 2.2 2.2Z"}}]}]});g.R.call(this,{S:"div",Z:"caption-window",V:{id:"caption-window-"+N.id,dir:L?"rtl":"ltr",tabindex:"0",lang:y.lang},L:T});var Q=
this;this.j=[];this.xO=!1;this.B=N;this.i_=this.Qd=null;this.playerWidth=W;this.playerHeight=X;this.Y=null;this.maxWidth=W*.96;this.maxHeight=X*.96;this.T=y;this.YR=S;this.zk=p;this.G=this.gH("captions-text");this.Pj=this.G.style.getPropertyValue("box-decoration-break")!==""||this.G.style.getPropertyValue("-webkit-box-decoration-break")!=="";this.jS=tty(O,P,W,X);this.J5=b;l&&(this.K=this.gH("caption-edit"),this.C(this.K,"click",function(){Q.J5()}));
this.type=0;this.vP=this.jS*u$l(V);this.kR=x;N=new g.hm(this.element,!0);g.C(this,N);N.subscribe("dragstart",this.jN,this);N.subscribe("dragmove",this.Nf,this);N.subscribe("dragend",this.bC,this);this.Ly=this.Ij=this.Vd=this.WP=0;N="";this.T.windowOpacity&&(N=FRV(this.T.windowColor),N="rgba("+N[0]+","+N[1]+","+N[2]+","+this.T.windowOpacity+")");p={"background-color":N,display:this.T.isVisible===!1?"none":"","text-align":wxt[this.T.textAlign]};this.Pj&&(p["border-radius"]=N?this.vP/8+"px":"");(this.X=
this.B.params.o0===2||this.B.params.o0===3)&&Rvt(this,this.element);g.TP(this.element,p);if(x){var n;(n=this.element.parentElement)==null||n.style.setProperty("--caption-window-color",N)}switch(this.T.gy){case 0:case 1:case 2:g.WF(this.element,"ytp-caption-window-top");break;case 6:case 7:case 8:g.WF(this.element,"ytp-caption-window-bottom")}},Rvt=function(N,p){var S="vertical-rl";
N.T.Xx===1&&(S="vertical-lr");g.xe&&(S=S==="vertical-lr"?"tb-lr":"tb-rl");g.TP(p,"-o-writing-mode",S);g.TP(p,"-webkit-writing-mode",S);g.TP(p,"writing-mode",S);g.TP(p,"text-orientation","upright");g.WF(p,"ytp-vertical-caption");N.B.params.o0===3&&(g.TP(p,"text-orientation",""),g.TP(p,"transform","rotate(180deg)"))},u$l=function(N){var p=1+.25*(N.fontSizeIncrement||0);
if(N.offset===0||N.offset===2)p*=.8;return p},I_y=function(N,p){var S={},O=p.background?p.background:N.T.k6.background;
if(p.backgroundOpacity!=null||p.background){var P=p.backgroundOpacity!=null?p.backgroundOpacity:N.T.k6.backgroundOpacity;O=FRV(O);S.background="rgba("+O[0]+","+O[1]+","+O[2]+","+P+")";N.Pj&&(S["box-decoration-break"]="clone",S["border-radius"]=N.vP/8+"px")}if(p.fontSizeIncrement!=null||p.offset!=null)S["font-size"]=N.jS*u$l(p)+"px";O=1;P=p.color||N.T.k6.color;if(p.color||p.textOpacity!=null)P=FRV(P),O=p.textOpacity==null?N.T.k6.textOpacity:p.textOpacity,P="rgba("+P[0]+","+P[1]+","+P[2]+","+O+")",
S.color=P,S.fill=P;var W=p.charEdgeStyle;W===0&&(W=void 0);if(W){P="rgba(34, 34, 34, "+O+")";var X="rgba(204, 204, 204, "+O+")";p.e5&&(X=P=p.e5);var l=N.jS/16/2,b=Math.max(l,1),h=Math.max(2*l,1),x=Math.max(3*l,1),y=Math.max(5*l,1);O=[];switch(W){case 4:for(;x<=y;x+=l)O.push(h+"px "+h+"px "+x+"px "+P);break;case 1:h=window.devicePixelRatio>=2?.5:1;for(W=b;W<=x;W+=h)O.push(W+"px "+W+"px "+P);break;case 2:O.push(b+"px "+b+"px "+X);O.push("-"+b+"px -"+b+"px "+P);break;case 3:for(x=0;x<5;x++)O.push("0 0 "+
h+"px "+P)}S["text-shadow"]=O.join(", ")}P="";switch(p.fontFamily){case 1:P='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';break;case 2:P='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:P='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:P='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:P='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';break;case 7:P=g.Ax()?
'"Carrois Gothic SC", sans-serif-smallcaps':'Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:P='"YouTube Noto", Roboto, Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}P&&(S["font-family"]=P);P=p.offset;P==null&&(P=N.T.k6.offset);switch(P){case 0:S["vertical-align"]="sub";break;case 2:S["vertical-align"]="super"}p.fontFamily===7&&(S["font-variant"]="small-caps");p.bold&&(S["font-weight"]="bold");p.italic&&(S["font-style"]="italic");p.underline&&(S["text-decoration"]=
"underline");p.jL&&(S.visibility="hidden");p.ET===1&&N.X&&(S["text-combine-upright"]="all",S["text-orientation"]="mixed",P=g.Dv||g.vm,N.B.params.o0===3?S.transform=P?"rotate(90deg)":"rotate(180deg)":P&&(S.transform="rotate(-90deg)"));if(p.G_===1||p.G_===2||p.G_===3||p.G_===4||p.G_===5)if(g.Dv)S["font-weight"]="bold";else switch(S["text-emphasis-style"]="filled circle",S["text-emphasis-color"]="currentcolor",S["webkit-text-emphasis"]="filled circle",p.G_){case 4:case 3:S["text-emphasis-position"]=
"under left";S["webkit-text-emphasis-position"]="under left";break;case 5:case 2:S["text-emphasis-position"]="over right",S["webkit-text-emphasis-position"]="over right"}return S},LS=function(N){N=N.split("px");
return N.length>0?(N=Number(N[0]))?N:0:0},D1q=function(N){N.Y=g.Xo("SPAN");
g.TP(N.Y,{display:"block"});g.WF(N.Y,"caption-visual-line");N.G.appendChild(N.Y)},ZBY=function(N,p){var S=g.Xo("SPAN");
g.TP(S,{display:"inline-block","white-space":"pre-wrap"});g.TP(S,I_y(N,p));S.classList.add("ytp-caption-segment");N.Y.appendChild(S);S.previousElementSibling&&(g.TP(S.previousElementSibling,{"border-top-right-radius":"0","border-bottom-right-radius":"0"}),g.TP(S,{"border-top-left-radius":"0","border-bottom-left-radius":"0"}));return S},kqE=function(N,p,S){N.xO=N.xO||!!S;
var O={};Object.assign(O,N.T.k6);Object.assign(O,S||p.T);Object.assign(O,N.YR.k6);(S=!N.Y)&&D1q(N);for(var P=N.Qd&&N.i_&&g.KB(O,N.i_)?N.Qd:ZBY(N,O),W=typeof p.text==="string",X=W?p.text.split("\n"):[p.text],l=0;l<X.length;l++){var b=l>0||!p.append,h=X[l];b&&!S?(D1q(N),P=ZBY(N,O)):b&&S&&(S=!1);h&&(P.appendChild(W?g.fW(h):h),W||h.tagName!=="RUBY"||h.childElementCount!==4||g.Dv||!g.BH(h.children[2],"text-emphasis")||(b=N.X?"padding-right":"padding-top",g.BH(h.children[2],"text-emphasis-position")&&(b=
N.X?"padding-left":"padding-bottom"),g.Se?g.TP(P,b,"1em"):g.TP(P,b,"0.5em")))}N.i_=O;N.Qd=P;N.j.push(p)},tty=function(N,p,S,O){var P=p/360*16;
p>=N&&(N=640,O>S*1.3&&(N=480),P=S/N*16);return P},NhC=function(){this.X=this.time=this.mode=this.B=0;
this.G=new qmY(this);this.K=new qmY(this);this.T=[];this.clear()},oYE=function(N,p,S){if(N===255&&p===255||!N&&!p)return{j7:N,
T0:p,result:0};N=pE0[N];p=pE0[p];if(N&128){var O;if(O=!(p&128))O=p,O=S.Uy()&&S.T0===O;if(O)return{j7:N,T0:p,result:1}}else if(p&128&&1<=N&&N<=31)return{j7:N,T0:p,result:2};return{j7:N,T0:p,result:3}},OWq=function(N,p,S,O){p===255&&S===255||!p&&!S?(++N.X===45&&N.reset(),N.G.B.clear(),N.K.B.clear()):(N.X=0,SiB(N.G,p,S,O))},P9Q=function(N,p){N.T.sort(function(P,W){var X=P.time-W.time;
return X===0?P.order-W.order:X});
for(var S=g.z(N.T),O=S.next();!O.done;O=S.next())O=O.value,N.time=O.time,O.type===0?OWq(N,O.Je,O.yM,p):O.type===1&&N.B&496&&SiB(N.K,O.Je,O.yM,p);N.T.length=0},TF=function(){this.type=0},v3=function(){this.state=this.T0=this.j7=0},Wsd=function(){this.timestamp=this.T=0},B3=function(N){this.K=N;
this.X=[];this.T=this.B=this.row=0;this.style=new TF;for(N=this.G=0;N<=15;N++){this.X[N]=[];for(var p=0;p<=32;p++)this.X[N][p]=new Wsd}},zF=function(N,p){if(N.style.type===3){for(var S=0,O=0,P=N.K.time+0,W="",X="",l=P,b=1;b<=15;++b){for(var h=!1,x=O?O:1;x<=32;++x){var y=N.X[b][x];
if(y.T!==0){S===0&&(S=b,O=x);h=String.fromCharCode(y.T);var V=y.timestamp;V<P&&(P=V);y.timestamp=l;X&&(W+=X,X="");W+=h;h=!0}if((y.T===0||x===32)&&h){X="\n";break}else if(O&&!h)break}if(S&&!h)break}W&&p.G(S,O,P,l,W)}else for(O=S=0,W=P=N.K.time+0,X=1;X<=15;++X)for(l="",b=1;b<=32;++b)if(x=N.X[X][b],y=x.T,y!==0&&(S===0&&(S=X,O=b),h=String.fromCharCode(y),V=x.timestamp,V<=P&&(P=V),l+=h,x.reset()),b===32||y===0)l&&p.G(S,O,P,W,l),P=W,l="",O=S=0},jCB=function(N,p){switch(N){case 0:return XEf[(p&127)-32];
case 1:return fMC[p&15];case 2:return lMQ[p&31];case 3:return bWt[p&31]}return 0},EV=function(N){return N.X[N.row][N.B]},$F=function(N,p,S){p>=2&&N.B>1&&(--N.B,EV(N).T=0);
var O=EV(N);O.timestamp=N.K.time+0;O.T=jCB(p,S);N.B<32&&N.B++},sCB=function(N,p,S,O){for(var P=0;P<O;P++)for(var W=0;W<=32;W++){var X=N.X[p+P][W],l=N.X[S+P][W];
X.T=l.T;X.timestamp=l.timestamp}},JA=function(N,p,S){for(var O=0;O<S;O++)for(var P=0;P<=32;P++)N.X[p+O][P].reset()},hWf=function(N){N.row=N.T>0?N.T:1;
N.B=1;JA(N,0,15)},xLq=function(N){this.X=N;
this.K=0;this.style=new TF;this.N=new B3(this.X);this.j=new B3(this.X);this.text=new B3(this.X);this.B=this.N;this.G=this.j;this.T=this.B},ydf=function(N,p,S){var O=N.B,P=!1;
switch(N.style.get()){case 4:case 1:case 2:N.style.get()===4&&O.T>0||(zF(O,S),hWf(N.B),hWf(N.G),O.row=15,O.T=p,P=!0)}N.style.set(3);N.T=O;N.T.style=N.style;N.X.mode=1<<O.G;P?O.B=1:O.T!==p&&(O.T>p?(zF(O,S),JA(O,O.row-O.T,p)):O.row<p&&(p=O.T),O.T=p)},Vey=function(N){N.style.set(1);
N.T=N.G;N.T.T=0;N.T.style=N.style;N.X.mode=1<<N.T.G},LsB=function(N){N.style.set(4);
N.T=N.text;N.T.style=N.style;N.X.mode=1<<N.T.G},qmY=function(N){this.T=N;
this.K=0;this.X=new xLq(this.T);this.N=new xLq(this.T);this.B=new v3;this.G=this.X},SiB=function(N,p,S,O){N.B.update();
p=oYE(p,S,N.B);switch(p.result){case 0:return;case 1:case 2:return}var P=p.j7;S=p.T0;if(32<=P||!P)N.T.mode&N.T.B&&(p=P,p&128&&(p=127),S&128&&(S=127),N=N.G.T,p&96&&$F(N,0,p),S&96&&$F(N,0,S),p!==0&&S!==0&&N.style.type===3&&zF(N,O));else if(P&16)a:if(!N.B.matches(P,S)&&(p=N.B,p.j7=P,p.T0=S,p.state=2,p=P&8?N.N:N.X,N.G=p,N.T.mode=1<<(N.K<<2)+(p.K<<1)+(p.style.type===4?1:0),(N.T.mode|1<<(N.K<<2)+(p.K<<1)+(p.style.type!==4?1:0))&N.T.B))if(S&64){O=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(P&7)<<1|S>>5&1];
N=S&16?((S&14)>>1)*4:0;S=p.T;switch(p.style.get()){case 4:O=S.row;break;case 3:if(O!==S.row){if(O<S.T&&(O=S.T,O===S.row))break;var W=1+S.row-S.T,X=1+O-S.T;sCB(S,X,W,S.T);p=W;P=S.T;X<W?(W=X+P-W,W>0&&(p+=W,P-=W)):(W=W+P-X,W>0&&(P-=W));JA(S,p,P)}}S.row=O;S.B=N+1}else switch(P&7){case 1:switch(S&112){case 32:$F(p.T,0,32);break a;case 48:S===57?(O=p.T,EV(O).T=0,O.B<32&&O.B++):$F(p.T,1,S&15)}break;case 2:S&32&&$F(p.T,2,S&31);break;case 3:S&32&&$F(p.T,3,S&31);break;case 4:case 5:if(32<=S&&S<=47)switch(S){case 32:Vey(p);
break;case 33:O=p.T;O.B>1&&(--O.B,EV(O).T=0);break;case 36:O=p.T;p=EV(O);for(N=0;N<=15;N++)for(S=0;S<=32;S++)if(O.X[N][S]===p){for(;S<=32;S++)O.X[N][S].reset();break}break;case 37:ydf(p,2,O);break;case 38:ydf(p,3,O);break;case 39:ydf(p,4,O);break;case 40:$F(p.T,0,32);break;case 41:p.style.set(2);p.T=p.B;p.T.T=0;p.T.style=p.style;p.X.mode=1<<p.T.G;break;case 42:O=p.text;O.T=15;O.style.set(4);hWf(O);LsB(p);break;case 43:LsB(p);break;case 44:N=p.B;switch(p.style.get()){case 1:case 2:case 3:zF(N,O)}JA(N,
0,15);break;case 45:b:{N=p.T;switch(p.style.get()){default:case 2:case 1:break b;case 4:if(N.row<15){++N.row;N.B=1;break b}break;case 3:}N.T<2&&(N.T=2,N.row<N.T&&(N.row=N.T));p=N.row-N.T+1;zF(N,O);sCB(N,p,p+1,N.T-1);JA(N,N.row,1)}break;case 46:JA(p.G,0,15);break;case 47:zF(p.B,O),p.G.updateTime(p.X.time+0),O=p.G,p.G=p.B,p.B=O,Vey(p)}break;case 7:switch(S){case 33:case 34:case 35:O=p.T,(O.B+=S&3)>32&&(O.B=32)}}},ThR=function(){},mG=function(N,p,S,O,P,W,X){W=W===void 0?!1:W;
X=X===void 0?null:X;g.WY.call(this,N,N+p,{priority:S,namespace:"captions"});this.windowId=O;this.text=P;this.append=W;this.T=X},BhB=function(N,p,S,O,P,W,X){var l=W[0],b=X[l.getAttribute("p")];
if(b.pg===1){var h=W[1],x=W[2];W=W[3];l.getAttribute("t");h.getAttribute("t");x.getAttribute("t");W.getAttribute("t");l.getAttribute("p");h.getAttribute("p");W.getAttribute("p");X=X[x.getAttribute("p")];l=vYY(l.textContent,h.textContent,x.textContent,W.textContent,X);return new mG(N,p,P,S,l,O,b)}switch(b.pg){case 9:case 10:b.G_=1;break;case 11:b.G_=2;break;case 12:b.G_=3;break;case 13:b.G_=4;break;case 14:b.G_=5}return new mG(N,p,P,S,l.textContent||"",O,b)},vYY=function(N,p,S,O,P){var W=g.Ax(),X=
W?g.Xo("DIV"):g.Xo("RUBY"),l=g.Xo("SPAN");
l.textContent=N;X.appendChild(l);N=W?g.Xo("DIV"):g.Xo("RP");N.textContent=p;X.appendChild(N);p=W?g.Xo("DIV"):g.Xo("RT");p.textContent=S;X.appendChild(p);S=P.pg;if(S===10||S===11||S===12||S===13||S===14)if(g.TP(p,"text-emphasis-style","filled circle"),g.TP(p,"text-emphasis-color","currentcolor"),g.TP(p,"webkit-text-emphasis","filled circle"),P.pg===11||P.pg===13)g.TP(p,"webkit-text-emphasis-position","under left"),g.TP(p,"text-emphasis-position","under left");S=!0;if(P.pg===4||P.pg===7||P.pg===12||
P.pg===14)g.TP(X,"ruby-position","over"),g.TP(X,"-webkit-ruby-position","before");else if(P.pg===5||P.pg===6||P.pg===11||P.pg===13)g.TP(X,"ruby-position","under"),g.TP(X,"-webkit-ruby-position","after"),S=!1;P=W?g.Xo("DIV"):g.Xo("RP");P.textContent=O;X.appendChild(P);W&&(O=S,g.TP(X,{display:"inline-block",position:"relative"}),W=X.firstElementChild.nextElementSibling,g.TP(W,"display","none"),W=W.nextElementSibling,g.TP(W,{"font-size":"0.5em","line-height":"1.2em","text-align":"center",position:"absolute",
left:"50%",transform:"translateX(-50%)",width:"400%"}),g.TP(X.lastElementChild,"display","none"),O?(g.TP(X,"padding-top","0.6em"),g.TP(W,"top","0")):(g.TP(X,"padding-bottom","0.6em"),g.TP(W,"bottom","0")));return X},UV=function(){g.e.apply(this,arguments)},H3=function(N,p,S,O,P){g.WY.call(this,N,N+p,{priority:S,
namespace:"captions"});this.id=O;this.params=P;this.T=[]},zWC=function(N){var p="_"+ik++;
return new H3(0,0x8000000000000,0,p,N)},ac=function(N){UV.call(this);
this.X=N;this.pens={};this.j={};this.Y={};this.G="_"+ik++;this.N={};this.B=this.T=null;this.K=!0},Qu=function(N,p){N=N.getAttribute(p);
if(N!=null)return Number(N)},gL=function(N,p){N=N.getAttribute(p);
if(N!=null)return N==="1"},c3=function(N,p){N=Qu(N,p);
return N!==void 0?N:null},nS=function(N,p){N=N.getAttribute(p);
if(N!=null)return FO.test(N),N},EYC=function(N,p){var S={},O=p.getAttribute("ws");
Object.assign(S,O?N.Y[O]:N.X);N=c3(p,"mh");N!=null&&(S.wr=N);N=c3(p,"ju");N!=null&&(S.textAlign=N);N=c3(p,"pd");N!=null&&(S.o0=N);N=c3(p,"sd");N!=null&&(S.Xx=N);N=nS(p,"wfc");N!=null&&(S.windowColor=N);p=Qu(p,"wfo");p!==void 0&&(S.windowOpacity=p/255);return S},$L0=function(N,p){var S={},O=p.getAttribute("wp");
O&&Object.assign(S,N.j[O]);N=c3(p,"ap");N!=null&&(S.gy=N);N=Qu(p,"cc");N!=null&&(S.kQ=N);N=Qu(p,"ah");N!=null&&(S.Qr=N);N=Qu(p,"rc");N!=null&&(S.K0=N);p=Qu(p,"av");p!=null&&(S.QF=p);return S},Jdf=function(N,p,S,O){var P={};
Object.assign(P,$L0(N,p));Object.assign(P,EYC(N,p));O?g.KB(P,N.X)?(O=N.G,P=N.X):O="_"+ik++:O=p.getAttribute("id")||"_"+ik++;N=Qu(p,"t")+S;p=Qu(p,"d")||0x8000000000000;if(P.o0===2||P.o0===3)S=P.K0,P.K0=P.kQ,P.kQ=S;return new H3(N,p,0,O,P)},rL=function(N){UV.call(this);
this.K=N;this.T=new Map;this.X=new Map;this.G=new Map;this.B=new Map},MM=function(N){N=g.LB(Math.round(N),0,16777215).toString(16).toUpperCase();
return"#000000".substring(0,7-N.length)+N},mLs=function(N,p,S,O,P){O===0&&(O=0x8000000000000);
var W={};p.wpWinPosId&&Object.assign(W,N.X.get(p.wpWinPosId));p.wsWinStyleId&&Object.assign(W,N.G.get(p.wsWinStyleId));N=p.rcRowCount;N!==void 0&&(W.K0=N);p=p.ccColCount;p!==void 0&&(W.kQ=p);if(W.o0===2||W.o0===3)p=W.K0,W.K0=W.kQ,W.kQ=p;return new H3(S,O,0,P,W)},KS=function(N,p,S){g.CG.call(this,N);
this.videoData=p;this.audioTrack=S;this.K=p.K6},YF=function(N,p,S,O,P,W,X,l,b,h){Vu.call(this,N,p,S,O,P,W,X,l,b,h);
this.type=1},GF=function(N,p,S){this.trackData=N;
this.N=S;this.version=this.K=this.X=this.byteOffset=0;this.B=[];this.T=new DataView(this.trackData)},dL=function(N){var p=N.byteOffset;
N.byteOffset+=1;return N.T.getUint8(p)},eO=function(N){var p=N.byteOffset;
N.byteOffset+=4;return N.T.getUint32(p)},CS=function(N,p){UV.call(this);
this.B=N;this.X=p;this.track=this.X.languageName==="CC3"?4:0;this.T=new NhC;this.T.B=1<<this.track},HWq=function(N){if(typeof N==="string")return!1;
N=new GF(N,8,0);return ULs(N)},ULs=function(N){if(!(N.byteOffset<N.T.byteLength)||eO(N)!==1380139777)return!1;
N.version=dL(N);if(N.version>1)return!1;dL(N);dL(N);dL(N);return!0},AA=function(N,p,S,O,P,W,X,l,b,h){Vu.call(this,N,p,S,O,P,W,X,l,b,h);
var x=this;this.type=2;this.py=[];this.u_=this.W=this.rH=0;this.eS=NaN;this.KI=0;this.Nt=null;this.Np=new g.k6(this.ZIP,433,this);this.K&&(h.createClientVe(this.K,this,167342),this.C(this.K,"click",function(){h.logClick(x.K)}),N=new g.hm(this.element,!0),g.C(this,N),N.subscribe("hoverstart",function(){h.logVisibility(x.K,!0)},this));
g.WF(this.element,"ytp-caption-window-rollup");g.C(this,this.Np);g.TP(this.element,"overflow","hidden")},iWd=function(N,p){if(!p)return"";
N.X&&N.B.params.Xx!==1&&(p*=-1);return"translate"+(N.X?"X":"Y")+"("+p+"px)"},aMQ=function(N){N.py=Array.from(document.getElementsByClassName("caption-visual-line"));
for(var p=N.B.params.K0,S=0,O=0,P=N.py.length-1;S<p&&P>-1;){var W=N.py[P];O+=N.X?W.offsetWidth:W.offsetHeight;S++;P--}N.W=O;p=Math;S=p.max;isNaN(N.eS)&&((O=N.T.kQ)?(P=g.Xo("SPAN"),g.xY(P,"\u2013".repeat(O)),g.TP(P,I_y(N,N.T.k6)),N.G.appendChild(P),N.eS=P.offsetWidth,N.G.removeChild(P)):N.eS=0);O=N.G;N.u_=S.call(p,N.eS,N.KI,(N.X?O.offsetHeight:O.offsetWidth)+1)},QCV=function(N,p){aMQ(N);
var S=N.py.reduce(function(W,X){return(N.X?X.offsetWidth:X.offsetHeight)+W},0);
S=N.W-S;if(S!==N.rH){var O=S>0&&N.rH===0,P=S<N.rH;p||isNaN(S)||O||!P||(g.WF(N.element,"ytp-rollup-mode"),g.q7(N.Np));g.TP(N.G,"transform",iWd(N,S));N.rH=S}aMQ(N)},gYt=function(N,p){g.CG.call(this,p);
this.B=N;this.D=p;this.logger=new g.sA("caps");this.X=this.N=this.j=null},cdG=function(N,p,S,O){N.logger.debug(function(){return"SABR captions data received for "+O});
N.j?N.N==null?N.logger.T(350058965,"Null loaded track meta data at captions data received"):S(p,N.N,(O+N.D.ac())*1E3):N.logger.T(350058965,"Null Representation at captions data received")},FsB=function(N,p){var S=[],O;
for(O in N.B.T)if(N.B.T.hasOwnProperty(O)){var P=N.B.T[O];if(g.tm(P,p||null)){var W=P.info.id,X=W,l="."+W,b="",h="";if(P=P.info.captionTrack)W=P.languageCode,X=P.displayName,l=P.vssId,b=P.kind,h=P.id;S.push(new g.bx({id:O,languageCode:W,languageName:X,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:l,kind:b,captionId:h}))}}return S},nY0=function(N,p){return p!=null&&p in N.B.T?N.B.T[p]:null},rdl=function(N,p,S){var O=[],P;
for(P in N.B.T)if(N.B.T.hasOwnProperty(P)){var W=N.B.T[P];if(g.tm(W,S||null)){var X=W.info.captionTrack;X&&X.languageCode===p&&O.push(W)}}return O.length?O[0]:null},MeQ=function(N,p){if(!N.U("html5_enable_sabr_live_captions")||N.T!=null&&g.H$(p.J())&&!N.T.isManifestless&&N.T.T.rawcc!=null||!N.Ua())return!1;
p=!!N.T&&N.T.isManifestless&&Object.values(N.T.T).some(function(S){return g.tm(S,"386")});
N=!!N.T&&!N.T.isManifestless&&g.a0_(N.T);return p||N},tA=function(){UV.call(this)},Ksf=function(N,p,S,O,P,W,X,l,b){switch(X.tagName){case "b":l.bold=!0;
break;case "i":l.italic=!0;break;case "u":l.underline=!0}for(var h=0;h<X.childNodes.length;h++){var x=X.childNodes[h];if(x.nodeType===3)x=new mG(p,S,O,P.id,x.nodeValue,W||h>0,g.rD(l)?void 0:l),b.push(x),P.T.push(x);else{var y={};Object.assign(y,l);Ksf(N,p,S,O,P,!0,x,y,b)}}},YiY=function(N){var p=N.split(":");
N=0;p=g.z(p);for(var S=p.next();!S.done;S=p.next())N=N*60+Number(S.value);return N*1E3},GbR=function(N,p,S,O){O=Object.assign({wr:0},O);
return new H3(N,p,S,"_"+ik++,O)},uk=function(N,p){g.e.call(this);
this.D=N;this.aj=p;this.T=null;this.B=this.D.S6();this.logger=new g.sA("caps")},eWy=function(N,p,S){if(typeof p==="string"||HWq(p))return[{trackData:p,
O6:S}];var O=new DataView(p);if(O.byteLength<=8||O.getUint32(4)!==1718909296)return[];var P=g.$Db(O);if(N.B&&P){var W=g.yzd(P),X=g.Vqh(P);P=P.Ty;W&&P&&N.B.ES(P,W,X)}N=g.Zg(O,1835295092);if(!N||!N.length||!N[0].size)return[];W=[];for(X=0;X<N.length;X++)P=N[X],P=new Uint8Array(p,P.dataOffset,P.size-(P.dataOffset-P.offset)),P=g.YV(P),W.push({trackData:P,O6:S+X*1E3});dLR(O,W,S);return W=W.filter(function(l){return!!l.trackData})},dLR=function(N,p,S){var O=g.eR(N,0,1836476516),P=9E4;
O&&(P=g.CC(O)||9E4);O=0;for(var W=g.Zg(N,1836019558),X=0;X<W.length;X++){var l=W[X];X<p.length&&(l=g.eR(N,l.dataOffset,1953653094))&&(l=g.eR(N,l.dataOffset,1952867444))&&(l=g.IW(l)/P*1E3,X===0&&(O=l),p[X].O6=l-O+S||S*X*1E3)}},C9G=function(N){var p={};
if(N=g.hy(N))p.lang=N,g.JRC.test(N)&&(p.o0=1);return p},wL=function(N){g.dg.call(this,N);
var p=this;this.D=N;this.Qd=[];this.py={};this.Np={};this.Y=!1;this.G="NONE";this.B=this.T=this.W=this.u_=this.jS=this.WP=null;this.aj=this.D.J();this.videoData=this.D.getVideoData();this.Vd=this.D.cP();var S;this.Ly=(S=this.D.getVideoData(1))==null?void 0:g.oi(S);this.X={k6:{}};this.N={k6:{}};g.hp(this.videoData)?this.G="OFFLINE":MeQ(this.videoData,this.D)?this.G="SABR_LIVE":g.E7H(this.videoData,this.D)?this.G="LIVE":this.videoData.captionTracks.length?this.G="INNERTUBE":this.videoData.Se&&(this.G=
"TTS");this.vP=this.aj.controlsType==="3";this.Ij=new uk(this.D,this.aj);this.eS=new g.Ke(this);this.j=new g.R({S:"div",Z:"ytp-caption-window-container",V:{id:"ytp-caption-window-container"}});this.zk={top:0,right:0,bottom:0,left:0,width:1,height:1};S=null;var O=g.Mv("yt-html5-player-modules::subtitlesModuleData");O&&(S=new g.HF(O));this.storage=S;var P;this.wF=!((P=N.PD())==null||!P.nO());this.K=AdQ(this);this.xO=!this.K&&this.vP&&this.wF&&(this.G==="LIVE"||this.G==="SABR_LIVE");g.C(this,this.Ij);
this.K?this.rH=this.i_=null:(this.i_=new g.ZU(this.Dx,void 0,this),g.C(this,this.i_),this.rH=new g.k6(this.wDp,2E3,this),g.C(this,this.rH));g.C(this,this.eS);g.IB(this.player,this.j.element,4);g.C(this,this.j);this.K||this.eS.C(N,"resize",this.oi);(this.kR=g.Qk(this.aj)&&!g.VQ()&&!this.D.isFullscreen()&&!this.K&&!this.xO)&&this.eS.C(N,"resize",this.EOB);this.eS.C(N,"onPlaybackAudioChange",this.OyP);this.eS.C(N,g.f7("captions"),function(W){p.onCueRangeEnter(W)});
this.eS.C(N,g.ls("captions"),function(W){p.onCueRangeExit(W)});
this.Ly&&this.eS.C(N,"videodatachange",function(W,X){p.onVideoDataChange(W,X)});
tet(this,r6y()||{});this.player.vz("onCaptionsModuleAvailable")},RWl=function(N){if(N.aj.kR===1||N.videoData.Pv===1||g.$N(N.videoData,"yt:cc")==="alwayson")return!0;
if(N.videoData.captionTracks.length)var p=N.getAudioTrack().B;if(N.aj.kR===2){if(g.wN(N.aj))var S=uot(N);else if(N.storage)try{S=N.storage.get("module-enabled")}catch(P){N.storage.remove("module-enabled")}else S=null;if(S!=null)return!!S}S=U1V(N.player.getAudioTrack(),g.wN(N.aj));var O=g.$N(N.videoData,"yt:cc");if(wEE(N)===void 0){if(S==="CAPTIONS_INITIAL_STATE_ON_RECOMMENDED")return O?O==="on":!0;if(S==="CAPTIONS_INITIAL_STATE_OFF_RECOMMENDED")return O==="on"}else return O==="on";return p==="ON"||
g.$N(N.videoData,"yt:cc")==="on"},Rc=function(N,p){if(N.B&&(p===void 0||!p)||!N.videoData.captionTracks.length)return!1;
N=N.getAudioTrack();return!!N.T||N.B==="FORCED_ON"},wEE=function(N){var p=void 0,S=g.ek(g.dp(),65);
if(g.wN(N.aj)&&S!=null){if(uot(N)!=null)return!1;p=!S}return p},IMs=function(N){var p;
N.G==="OFFLINE"?p=new KS(N.player,N.videoData,N.getAudioTrack()):N.G==="SABR_LIVE"?p=new gYt(N.videoData.T,N.player):N.G==="LIVE"?p=new yu(N.videoData.T,N.player):N.G==="INNERTUBE"?p=new g.Am(N.player,N.videoData,N.getAudioTrack()):p=new g.uv(N.player,N.videoData.Se,N.videoData.videoId,g.vO5(N.videoData),N.videoData.BV,N.videoData.eventId);return p},DF=function(N,p){if(!N.T)return null;
if(N.W&&N.W.G)return N.W.G;p=DLf(N,p);p=g.iv(N.T.T,p);var S=null;if(HBy(N.aj)){var O=N.D.isInline()?void 0:g.n1("yt-player-caption-sticky-language");for(var P=[O,N.videoData.captionsLanguagePreference,N.aj.captionsLanguagePreference,g.$N(N.videoData,"yt:cc_default_lang")],W=!1,X=0;X<P.length;X++){var l=P[X];if(l){W=!0;for(var b=0;b<p.length;b++)if(g.hy(p[b])===l)return p[b];for(b=0;b<p.length;b++)if(g.hy(p[b]).split("-")[0]===l.split("-")[0])return p[b]}}if(W&&N.T&&(P=N.T.K,P.length))for(P=g.z(P),
W=P.next();!W.done;W=P.next())if(W=W.value,W.languageCode===O){S=W;break}}else for(O=[N.videoData.captionsLanguagePreference,N.aj.captionsLanguagePreference,g.$N(N.videoData,"yt:cc_default_lang")],P=0;P<O.length;P++)for(W=0;W<p.length;W++)if(g.hy(p[W])===O[P])return p[W];O=null;N.W&&N.W.X&&(O=N.W.X);O||(O=p.find(function(h){return h.isDefault})||null);
O||(O=p[0]||Ic(N));O&&S&&g.hy(O).split("-")[0]!==S.languageCode.split("-")[0]&&(O=iBd(O,S));return O},Ic=function(N){return N.W&&N.W.T},ZF=function(N){var p=Ic(N);
return!!p&&N.B===p},ZWd=function(N){var p=U1V(N.player.getAudioTrack(),g.wN(N.aj));
var S=p==="CAPTIONS_INITIAL_STATE_ON_REQUIRED"?DF(N,N.Y):p==="CAPTIONS_INITIAL_STATE_OFF_REQUIRED"&&Rc(N)?Ic(N):wEE(N)||N.Y||RWl(N)?DF(N,N.Y):Rc(N)?Ic(N):null;if(N.K||N.xO){var O=g.iv(N.T.T,!0);p=[];for(var P=0;P<O.length;P++){var W=O[P],X=g.Xo("TRACK");X.setAttribute("kind","subtitles");X.setAttribute("label",g.jD(W));X.setAttribute("srclang",g.hy(W));X.setAttribute("id",W.toString());N.xO||X.setAttribute("src",N.T.o1(W,"vtt"));W===S&&X.setAttribute("default","1");p.push(X)}S=N.D.PD();S.HJ(p);p=
S.fI();N.wF&&N.eS.C(p.textTracks,"change",N.Qck)}else!N.B&&S&&kF(N,S),N.player.vz("onCaptionsTrackListChanged"),N.player.Ms("onApiChange")},kbq=function(N,p){var S=N.D.PD().fI().textTracks;
N=N.B.toString();for(var O=0;O<S.length;O++){var P=S[O];P.id===N&&(p?P.mode!=="showing"&&(P.mode="showing"):P.mode==="showing"&&(P.mode="disabled"))}},kF=function(N,p,S){N.loaded&&N.unload();
S!=null&&(N.Y=S,N.Y&&(g.wN(N.aj)?qM(N,!!p):N3(N,!!p)));N.aj.U("html5_report_caption_format_change")&&qiG(N,N.B,p,N.Y,!1);N.B=p;Rc(N)&&(p=Ic(N),N.aj.U("html5_report_caption_format_change")&&qiG(N,N.B,p,N.Y,!0),N.B=p);var O;N4B(N,(O=N.B)!=null?O:void 0);N.load()},o8G=function(N,p){if(p instanceof H3){var S=N.py[p.id];
S&&S.B!==p&&(S.dispose(),delete N.py[p.id],S=null);S||(S=pkB(N,p))&&(N.py[p.id]=S)}else S=p.windowId,N.Np[S]||(N.Np[S]=[]),N.Np[S].push(p)},pkB=function(N,p){var S=SwB(N);
if(!S)return null;var O=N.B?g.hy(N.B):null;O&&g.JRC.test(O)&&(p.params.o0=1);var P=N.Vd.getPlayerSize();O=P.height*N.zk.height;P=P.width*N.zk.width;N.aj.playerStyle!=="google-live"||N.X.isDefault||Object.assign(p.params,N.X);switch(p.params.wr!=null?p.params.wr:p.T.length>1?1:0){case 1:return new YF(p,N.X,N.N,S.width,S.height,P,O,N.aj.experiments,N.CV.bind(N),N.D);case 2:return new AA(p,N.X,N.N,S.width,S.height,P,O,N.aj.experiments,N.CV.bind(N),N.D);default:return new Vu(p,N.X,N.N,S.width,S.height,
P,O,N.aj.experiments,N.CV.bind(N),N.D)}},tet=function(N,p,S){S=S===void 0?!1:S;
var O=pj.k6;N.X={};Object.assign(N.X,pj);N.X.k6={};Object.assign(N.X.k6,O);N.N={k6:{}};var P=p.backgroundOverride?N.N:N.X,W=p.background||O.background;FO.test(W);P.k6.background=W;P=p.colorOverride?N.N:N.X;W=p.color||O.color;FO.test(W);P.k6.color=W;P=p.windowColorOverride?N.N:N.X;W=p.windowColor||pj.windowColor;FO.test(W);P.windowColor=W;P=p.backgroundOpacityOverride?N.N:N.X;W=p.backgroundOpacity;W==null&&(W=O.backgroundOpacity);P.k6.backgroundOpacity=W;P=p.fontSizeIncrementOverride?N.N:N.X;W=p.fontSizeIncrement;
W==null&&(W=O.fontSizeIncrement);P.k6.fontSizeIncrement=W;W=p.fontStyleOverride?N.N:N.X;P=p.fontStyle;P==null&&(P=O.bold&&O.italic?3:O.bold?1:O.italic?2:0);W=W.k6;switch(P){case 1:W.bold=!0;delete W.italic;break;case 2:delete W.bold;W.italic=!0;break;case 3:W.bold=!0;W.italic=!0;break;default:delete W.bold,delete W.italic}P=p.textOpacityOverride?N.N:N.X;W=p.textOpacity;W==null&&(W=O.textOpacity);P.k6.textOpacity=W;P=p.windowOpacityOverride?N.N:N.X;W=p.windowOpacity;W==null&&(W=pj.windowOpacity);P.windowOpacity=
W;P=p.charEdgeStyleOverride?N.N:N.X;W=p.charEdgeStyle;W==null&&(W=O.charEdgeStyle);P.k6.charEdgeStyle=W;P=p.fontFamilyOverride?N.N:N.X;W=p.fontFamily;W==null&&(W=O.fontFamily);P.k6.fontFamily=W;N.loaded&&N.oi();S&&g.FV("yt-player-caption-display-settings",p,2592E3)},Oxf=function(N,p){if(!N.T)return{};
if(p){N.aj.U("html5_report_caption_format_intent")&&!g.rD(p)&&N.h3(p.vss_id,"m");if(N.K||!g.Cs(p))return;if(g.rD(p)){kF(N,null,!0);return}for(var S,O=g.iv(N.T.T,!0),P=0;P<O.length;P++){var W=O[P];W.languageCode!==p.languageCode||S&&(W.languageName!==p.languageName||(W.captionId||"")!==(p.captionId||"")||g.jD(W)!==p.displayName)||(S=p.translationLanguage?iBd(W,p.translationLanguage):W)}N.Hs(p.position);!S||S===N.B&&N.loaded||(p=g.d$(),O=g.hy(S),p.length&&O===p[p.length-1]||(p.push(O),g.FV("yt-player-caption-language-preferences",
p)),HBy(N.aj)&&!N.D.isInline()&&g.FV("yt-player-caption-sticky-language",O,2592E3),kF(N,S,!0))}else return N.loaded&&N.B&&!ZF(N)?g.so(N.B):{};return""},WwC=function(N,p,S){p&&!N.u_?(p=zWC({o0:0,
lang:"en"}),N.u_=[p,new mG(p.start,p.end-p.start,0,p.id,S!=null?S:"Captions look like this")],N.player.cD(N.u_)):!p&&N.u_&&(P1G(N,N.u_),N.u_=null)},P1G=function(N,p){N.player.nE(p);
p=g.z(p);for(var S=p.next();!S.done;S=p.next())g.I0(N.Qd,S.value);hA(N.i_)},N4B=function(N,p){N.aj.U("html5_modify_caption_vss_logging")&&(N.videoData.lr=p)},SwB=function(N){var p=N.Vd.getVideoContentRect(!0).height,S=N.Vd.getVideoContentRect(!0).width;
if(!p||!S)return null;p*=N.zk.height;S*=N.zk.width;return{width:S,height:p}},N3=function(N,p){if(N.storage)try{N.storage.set("module-enabled",p)}catch(S){}},qM=function(N,p){N.D.isInline()||g.FV("yt-player-sticky-caption",p,2592E3)},uot=function(N){if(!N.D.isInline())return g.n1("yt-player-sticky-caption")},AdQ=function(N){var p,S=!((p=N.D.PD())==null||!p.Z9());
return N.vP&&S&&N.G!=="LIVE"&&N.G!=="SABR_LIVE"},DLf=function(N,p){g.Pe(N.videoData)&&(p=!0);
p||(p=N.G==="TTS"?!1:N.G==="INNERTUBE"?!1:!0);return p||N.aj.U("web_deprecate_always_includes_asr_setting")&&g.wN(N.aj)?!0:!!g.ek(g.dp(),66)},qiG=function(N,p,S,O,P){P?N.Wq(S,!0,"g"):O?p?N.Wq(S,!!S,"m"):S&&N.Wq(S,!0,"m"):!p&&S&&N.Wq(S,!0,"s")};
g.CG.prototype.aI=g.SA(55,function(){return!1});
g.CG.prototype.cN=g.SA(54,function(){});
g.Am.prototype.cN=g.SA(53,function(N,p,S){var O=this;this.wH();p=this.o1(N,p);var P=this.Dm.J().U("html5_report_captions_ctmp_qoe"),W=(0,g.Hm)();this.m6();m1Q(this,p,{format:"RAW",onSuccess:function(X){O.B=null;if(P){var l=(X.responseText.length/1024).toFixed(),b=(0,g.Hm)();O.videoData.Tk("capresp",{ms:b-W,kb:l})}S(X.responseText,N)},
onError:P?function(X){var l;X=(l=X==null?void 0:X.status)!=null?l:0;O.videoData.Tk("capfail",{status:X})}:void 0,
withCredentials:!0})});
g.uv.prototype.cN=g.SA(52,function(N,p,S){var O=this;this.wH();p=this.o1(N,p);this.m6();this.B=g.m3(p,{format:"RAW",onSuccess:function(P){O.B=null;S(P.responseText,N)},
withCredentials:!0})});
g.zc.prototype.yj=g.SA(51,function(){for(var N=g.NL(document,"track",void 0,this.T),p=0;p<N.length;p++)g.si(N[p])});
g.Ir.prototype.yj=g.SA(50,function(){this.mediaElement.yj()});
g.zc.prototype.nO=g.SA(49,function(){return!(!this.T.textTracks||!this.T.textTracks.addEventListener)});
g.Ir.prototype.nO=g.SA(48,function(){return this.mediaElement.nO()});
g.zc.prototype.Z9=g.SA(47,function(){return!!this.T.textTracks});
g.Ir.prototype.Z9=g.SA(46,function(){return this.mediaElement.Z9()});
g.zc.prototype.HJ=g.SA(45,function(N){for(var p=0;p<N.length;p++)this.T.appendChild(N[p])});
g.Ir.prototype.HJ=g.SA(44,function(N){this.mediaElement.HJ(N)});
g.TE.prototype.ES=g.SA(40,function(N,p,S){this.Pz.ES(N,p,S)});
g.Ob.prototype.ES=g.SA(39,function(N,p,S){this.i_.set(N,{gB:p,oh:S})});
g.TE.prototype.SA=g.SA(38,function(N){return this.Pz.SA(N)});
g.Ob.prototype.SA=g.SA(37,function(N){var p=2;this.N.has(N)?p=0:g.PZG(this,N)&&(p=1);return p});
g.sA.prototype.T=g.SA(36,function(N){g.vm8.apply(null,[6,this.tag,N].concat(g.J(g.U_.apply(1,arguments))))});
g.d3.prototype.h3=g.SA(34,function(N,p){var S=g.ce(this.app);S&&S.h3(N,p)});
g.M0.prototype.h3=g.SA(33,function(N,p){N=[N,p];g.rn(this,g.E4(this.provider),"cfi",N)});
g.Z$.prototype.h3=g.SA(32,function(N,p){this.qoe&&this.qoe.h3(N,p)});
g.J_.prototype.h3=g.SA(31,function(N,p){this.o4().h3(N,p)});
g.d3.prototype.Wq=g.SA(30,function(N,p,S){var O=g.ce(this.app);O&&O.Wq(N,p,S)});
g.M0.prototype.Wq=g.SA(29,function(N,p,S){if(this.rH!==N||this.J5!==p)p=p==="rawcc"?"":p,S=[N,p,this.rH,S],g.rn(this,g.E4(this.provider),"cfs",S),this.rH=N,this.J5=p});
g.Z$.prototype.Wq=g.SA(28,function(N,p,S){this.qoe&&this.qoe.Wq(N,p,S)});
g.J_.prototype.Wq=g.SA(27,function(N,p,S){this.o4().Wq(N,p,S)});
g.s$.prototype.JD=g.SA(18,function(){return this.j});
g.H5.prototype.JD=g.SA(17,function(){var N;return((N=g.ce(this))==null?void 0:N.S6())||null});
g.d3.prototype.S6=g.SA(16,function(){return this.app.JD()});
g.J_.prototype.S6=g.SA(15,function(){var N;return((N=this.kO)==null?void 0:N.JD())||null});
g.HR.prototype.BR=g.SA(1,function(N){return(N=this.oK(N))?N.T:0});
g.Nh.prototype.BR=g.SA(0,function(){return 0});
var c6t=/#(.)(.)(.)/,gBl=/^#(?:[0-9a-f]{3}){1,2}$/i,d1s={aa:"Afar",ab:"Abkhazian",ace:"Acehnese",ach:"Acoli",ada:"Adangme",ady:"Adyghe",ae:"Avestan",aeb:"Tunisian Arabic",af:"Afrikaans",afh:"Afrihili",agq:"Aghem",ain:"Ainu",ak:"Akan",akk:"Akkadian",akz:"Alabama",ale:"Aleut",aln:"Gheg Albanian",alt:"Southern Altai",am:"Amharic",an:"Aragonese",ang:"Old English",anp:"Angika",ar:"Arabic",ar_001:"Arabic (world)",arc:"Aramaic",arn:"Mapuche",aro:"Araona",arp:"Arapaho",arq:"Algerian Arabic",ars:"Najdi Arabic",
arw:"Arawak",ary:"Moroccan Arabic",arz:"Egyptian Arabic",as:"Assamese",asa:"Asu",ase:"American Sign Language",ast:"Asturian",av:"Avaric",avk:"Kotava",awa:"Awadhi",ay:"Aymara",az:"Azerbaijani",az_Cyrl:"Azerbaijani (Cyrillic)",az_Latn:"Azerbaijani (Latin)",ba:"Bashkir",bal:"Baluchi",ban:"Balinese",bar:"Bavarian",bas:"Basaa",bax:"Bamun",bbc:"Batak Toba",bbj:"Ghomala",be:"Belarusian",bej:"Beja",bem:"Bemba",bew:"Betawi",bez:"Bena",bfd:"Bafut",bfq:"Badaga",bg:"Bulgarian",bgc:"Haryanvi",bgn:"Western Balochi",
bho:"Bhojpuri",bi:"Bislama",bik:"Bikol",bin:"Bini",bjn:"Banjar",bkm:"Kom",bla:"Siksik\u00e1",blo:"Anii",bm:"Bambara",bn:"Bangla",bo:"Tibetan",bpy:"Bishnupriya",bqi:"Bakhtiari",br:"Breton",bra:"Braj",brh:"Brahui",brx:"Bodo",bs:"Bosnian",bs_Cyrl:"Bosnian (Cyrillic)",bs_Latn:"Bosnian (Latin)",bss:"Akoose",bua:"Buriat",bug:"Buginese",bum:"Bulu",byn:"Blin",byv:"Medumba",ca:"Catalan",cad:"Caddo",car:"Carib",cay:"Cayuga",cch:"Atsam",ccp:"Chakma",ce:"Chechen",ceb:"Cebuano",cgg:"Chiga",ch:"Chamorro",chb:"Chibcha",
chg:"Chagatai",chk:"Chuukese",chm:"Mari",chn:"Chinook Jargon",cho:"Choctaw",chp:"Chipewyan",chr:"Cherokee",chy:"Cheyenne",ckb:"Central Kurdish",co:"Corsican",cop:"Coptic",cps:"Capiznon",cr:"Cree",crh:"Crimean Tatar",cs:"Czech",csb:"Kashubian",csw:"Swampy Cree",cu:"Church Slavic",cv:"Chuvash",cy:"Welsh",da:"Danish",dak:"Dakota",dar:"Dargwa",dav:"Taita",de:"German",de_AT:"German (Austria)",de_CH:"German (Switzerland)",del:"Delaware",den:"Slave",dgr:"Dogrib",din:"Dinka",dje:"Zarma",doi:"Dogri",dsb:"Lower Sorbian",
dua:"Duala",dum:"Middle Dutch",dv:"Divehi",dyo:"Jola-Fonyi",dyu:"Dyula",dz:"Dzongkha",dzg:"Dazaga",ebu:"Embu",ee:"Ewe",efi:"Efik",egy:"Ancient Egyptian",eka:"Ekajuk",el:"Greek",elx:"Elamite",en:"English",en_AU:"English (Australia)",en_CA:"English (Canada)",en_GB:"English (United Kingdom)",en_US:"English (United States)",enm:"Middle English",eo:"Esperanto",es:"Spanish",es_419:"Spanish (Latin America)",es_ES:"Spanish (Spain)",es_MX:"Spanish (Mexico)",et:"Estonian",eu:"Basque",ewo:"Ewondo",fa:"Persian",
fa_AF:"Persian (Afghanistan)",fan:"Fang",fat:"Fanti",ff:"Fula",ff_Adlm:"Fula (Adlam)",ff_Latn:"Fula (Latin)",fi:"Finnish",fil:"Filipino",fj:"Fijian",fo:"Faroese",fon:"Fon",fr:"French",fr_CA:"French (Canada)",fr_CH:"French (Switzerland)",frm:"Middle French",fro:"Old French",frr:"Northern Frisian",frs:"Eastern Frisian",fur:"Friulian",fy:"Western Frisian",ga:"Irish",gaa:"Ga",gay:"Gayo",gba:"Gbaya",gd:"Scottish Gaelic",gez:"Geez",gil:"Gilbertese",gl:"Galician",gmh:"Middle High German",gn:"Guarani",goh:"Old High German",
gon:"Gondi",gor:"Gorontalo",got:"Gothic",grb:"Grebo",grc:"Ancient Greek",gsw:"Swiss German",gu:"Gujarati",guz:"Gusii",gv:"Manx",gwi:"Gwich\u02bcin",ha:"Hausa",hai:"Haida",haw:"Hawaiian",he:"Hebrew",hi:"Hindi",hi_Latn:"Hindi (Latin)",hil:"Hiligaynon",hit:"Hittite",hmn:"Hmong",ho:"Hiri Motu",hr:"Croatian",hsb:"Upper Sorbian",ht:"Haitian Creole",hu:"Hungarian",hup:"Hupa",hy:"Armenian",hz:"Herero",ia:"Interlingua",iba:"Iban",ibb:"Ibibio",id:"Indonesian",ie:"Interlingue",ig:"Igbo",ii:"Sichuan Yi",ik:"Inupiaq",
ilo:"Iloko","in":"Indonesian",inh:"Ingush",io:"Ido",is:"Icelandic",it:"Italian",iu:"Inuktitut",iw:"Hebrew",ja:"Japanese",jbo:"Lojban",jgo:"Ngomba",jmc:"Machame",jpr:"Judeo-Persian",jrb:"Judeo-Arabic",jv:"Javanese",ka:"Georgian",kaa:"Kara-Kalpak",kab:"Kabyle",kac:"Kachin",kaj:"Jju",kam:"Kamba",kaw:"Kawi",kbd:"Kabardian",kbl:"Kanembu",kcg:"Tyap",kde:"Makonde",kea:"Kabuverdianu",kfo:"Koro",kg:"Kongo",kgp:"Kaingang",kha:"Khasi",kho:"Khotanese",khq:"Koyra Chiini",ki:"Kikuyu",kj:"Kuanyama",kk:"Kazakh",
kk_Cyrl:"Kazakh (Cyrillic)",kkj:"Kako",kl:"Kalaallisut",kln:"Kalenjin",km:"Khmer",kmb:"Kimbundu",kn:"Kannada",ko:"Korean",kok:"Konkani",kok_Deva:"Konkani (Devanagari)",kok_Latn:"Konkani (Latin)",kos:"Kosraean",kpe:"Kpelle",kr:"Kanuri",krc:"Karachay-Balkar",krl:"Karelian",kru:"Kurukh",ks:"Kashmiri",ks_Arab:"Kashmiri (Arabic)",ks_Deva:"Kashmiri (Devanagari)",ksb:"Shambala",ksf:"Bafia",ksh:"Colognian",ku:"Kurdish",kum:"Kumyk",kut:"Kutenai",kv:"Komi",kw:"Cornish",kxv:"Kuvi",kxv_Deva:"Kuvi (Devanagari)",
kxv_Latn:"Kuvi (Latin)",kxv_Orya:"Kuvi (Odia)",kxv_Telu:"Kuvi (Telugu)",ky:"Kyrgyz",la:"Latin",lad:"Ladino",lag:"Langi",lah:"Western Panjabi",lam:"Lamba",lb:"Luxembourgish",lez:"Lezghian",lg:"Ganda",li:"Limburgish",lij:"Ligurian",lkt:"Lakota",lmo:"Lombard",ln:"Lingala",lo:"Lao",lol:"Mongo",loz:"Lozi",lrc:"Northern Luri",lt:"Lithuanian",lu:"Luba-Katanga",lua:"Luba-Lulua",lui:"Luiseno",lun:"Lunda",luo:"Luo",lus:"Mizo",luy:"Luyia",lv:"Latvian",mad:"Madurese",maf:"Mafa",mag:"Magahi",mai:"Maithili",mak:"Makasar",
man:"Mandingo",mas:"Masai",mde:"Maba",mdf:"Moksha",mdr:"Mandar",men:"Mende",mer:"Meru",mfe:"Morisyen",mg:"Malagasy",mga:"Middle Irish",mgh:"Makhuwa-Meetto",mgo:"Meta\u02bc",mh:"Marshallese",mi:"M\u0101ori",mic:"Mi'kmaw",min:"Minangkabau",mk:"Macedonian",ml:"Malayalam",mn:"Mongolian",mnc:"Manchu",mni:"Manipuri",mni_Beng:"Manipuri (Bangla)",mo:"Romanian",moh:"Mohawk",mos:"Mossi",mr:"Marathi",ms:"Malay",mt:"Maltese",mua:"Mundang",mul:"Multiple languages",mus:"Muscogee",mwl:"Mirandese",mwr:"Marwari",
my:"Burmese",mye:"Myene",myv:"Erzya",mzn:"Mazanderani",na:"Nauru",nap:"Neapolitan",naq:"Nama",nb:"Norwegian Bokm\u00e5l",nd:"North Ndebele",nds:"Low German",nds_NL:"Low German (Netherlands)",ne:"Nepali","new":"Newari",ng:"Ndonga",nia:"Nias",niu:"Niuean",nl:"Dutch",nl_BE:"Dutch (Belgium)",nmg:"Kwasio",nn:"Norwegian Nynorsk",nnh:"Ngiemboon",no:"Norwegian",nog:"Nogai",non:"Old Norse",nqo:"N\u2019Ko",nr:"South Ndebele",nso:"Northern Sotho",nus:"Nuer",nv:"Navajo",nwc:"Classical Newari",ny:"Nyanja",nym:"Nyamwezi",
nyn:"Nyankole",nyo:"Nyoro",nzi:"Nzima",oc:"Occitan",oj:"Ojibwa",om:"Oromo",or:"Odia",os:"Ossetic",osa:"Osage",ota:"Ottoman Turkish",pa:"Punjabi",pa_Arab:"Punjabi (Arabic)",pa_Guru:"Punjabi (Gurmukhi)",pag:"Pangasinan",pal:"Pahlavi",pam:"Pampanga",pap:"Papiamento",pau:"Palauan",pcm:"Nigerian Pidgin",peo:"Old Persian",phn:"Phoenician",pi:"Pali",pl:"Polish",pon:"Pohnpeian",prg:"Prussian",pro:"Old Proven\u00e7al",ps:"Pashto",pt:"Portuguese",pt_BR:"Portuguese (Brazil)",pt_PT:"Portuguese (Portugal)",qu:"Quechua",
raj:"Rajasthani",rap:"Rapanui",rar:"Rarotongan",rm:"Romansh",rn:"Rundi",ro:"Romanian",ro_MD:"Romanian (Moldova)",rof:"Rombo",rom:"Romany",ru:"Russian",rup:"Aromanian",rw:"Kinyarwanda",rwk:"Rwa",sa:"Sanskrit",sad:"Sandawe",sah:"Yakut",sam:"Samaritan Aramaic",saq:"Samburu",sas:"Sasak",sat:"Santali",sat_Olck:"Santali (Ol Chiki)",sba:"Ngambay",sbp:"Sangu",sc:"Sardinian",scn:"Sicilian",sco:"Scots",sd:"Sindhi",sd_Arab:"Sindhi (Arabic)",sd_Deva:"Sindhi (Devanagari)",se:"Northern Sami",see:"Seneca",seh:"Sena",
sel:"Selkup",ses:"Koyraboro Senni",sg:"Sango",sga:"Old Irish",sh:"Serbo-Croatian",shi:"Tachelhit",shi_Latn:"Tachelhit (Latin)",shi_Tfng:"Tachelhit (Tifinagh)",shn:"Shan",shu:"Chadian Arabic",si:"Sinhala",sid:"Sidamo",sk:"Slovak",sl:"Slovenian",sm:"Samoan",sma:"Southern Sami",smj:"Lule Sami",smn:"Inari Sami",sms:"Skolt Sami",sn:"Shona",snk:"Soninke",so:"Somali",sog:"Sogdien",sq:"Albanian",sr:"Serbian",sr_Cyrl:"Serbian (Cyrillic)",sr_Latn:"Serbian (Latin)",srn:"Sranan Tongo",srr:"Serer",ss:"Swati",
ssy:"Saho",st:"Southern Sotho",su:"Sundanese",su_Latn:"Sundanese (Latin)",suk:"Sukuma",sus:"Susu",sux:"Sumerian",sv:"Swedish",sw:"Swahili",sw_CD:"Swahili (Congo - Kinshasa)",swb:"Comorian",syc:"Classical Syriac",syr:"Syriac",szl:"Silesian",ta:"Tamil",te:"Telugu",tem:"Timne",teo:"Teso",ter:"Tereno",tet:"Tetum",tg:"Tajik",th:"Thai",ti:"Tigrinya",tig:"Tigre",tiv:"Tiv",tk:"Turkmen",tkl:"Tokelau",tl:"Tagalog",tlh:"Klingon",tli:"Tlingit",tmh:"Tamashek",tn:"Tswana",to:"Tongan",tog:"Nyasa Tonga",tok:"Toki Pona",
tpi:"Tok Pisin",tr:"Turkish",trv:"Taroko",ts:"Tsonga",tsi:"Tsimshian",tt:"Tatar",tum:"Tumbuka",tvl:"Tuvalu",tw:"Twi",twq:"Tasawaq",ty:"Tahitian",tyv:"Tuvinian",tzm:"Central Atlas Tamazight",udm:"Udmurt",ug:"Uyghur",uga:"Ugaritic",uk:"Ukrainian",umb:"Umbundu",ur:"Urdu",uz:"Uzbek",uz_Arab:"Uzbek (Arabic)",uz_Cyrl:"Uzbek (Cyrillic)",uz_Latn:"Uzbek (Latin)",vai:"Vai",vai_Latn:"Vai (Latin)",vai_Vaii:"Vai (Vai)",ve:"Venda",vec:"Venetian",vi:"Vietnamese",vmw:"Makhuwa",vo:"Volap\u00fck",vot:"Votic",vun:"Vunjo",
wa:"Walloon",wae:"Walser",wal:"Wolaytta",war:"Waray",was:"Washo",wo:"Wolof",xal:"Kalmyk",xh:"Xhosa",xnr:"Kangri",xog:"Soga",yao:"Yao",yap:"Yapese",yav:"Yangben",ybb:"Yemba",yi:"Yiddish",yo:"Yoruba",yrl:"Nheengatu",yue:"Cantonese",yue_Hans:"Cantonese (Simplified)",yue_Hant:"Cantonese (Traditional)",za:"Zhuang",zap:"Zapotec",zbl:"Blissymbols",zen:"Zenaga",zgh:"Standard Moroccan Tamazight",zh:"Chinese",zh_Hans:"Chinese (Simplified)",zh_Hant:"Chinese (Traditional)",zh_TW:"Chinese (Taiwan)",zu:"Zulu",
zun:"Zuni",zxx:"No linguistic content",zza:"Zaza"};xF.prototype.contains=function(N){N=g.SI(this.segments,N);return N>=0||N<0&&(-N-1)%2===1};
xF.prototype.length=function(){return this.segments.length/2};
g.B(KR0,g.e);g.f=KR0.prototype;g.f.BP=function(){g.e.prototype.BP.call(this);this.X&&this.X.cancel()};
g.f.N$=function(){this.seekTo(this.player.getCurrentTime())};
g.f.seekTo=function(N){N-=this.player.ac();var p=this.T;this.T=g.Cq(this.u_.hB(N).Eb);p!==this.T&&this.W&&this.W()};
g.f.reset=function(){this.G=new xF;this.N=-1;this.X&&(this.X.cancel(),this.X=null)};
g.f.YC=function(){this.wH();var N;if(N=this.T!=null)N=this.T,N=N.T.Eh(N);if(N&&!this.X&&!(this.T&&this.T.startTime-this.player.getCurrentTime()>30)){N=this.T;N=N.T.wQ(N);var p=N.Eb[0],S;if((S=this.player.getVideoData())==null?0:S.enableServerStitchedDai)if(S=this.player.S6()){var O=p.T.info.id,P=p.Mp,W=N.Eb[0].a5;if(this.policy.i_){if(S=S.p5(W,P,O,3))N.G=S}else if(O=S.fH(W,P,O,3))if(S=S.SA(P),S===0)O&&(N.T=new g.vR(O));else if(S===2){this.j.start();Ym0(this)&&this.seekTo(this.player.getCurrentTime());
return}}p.T.index.Cl(p.Mp)?(this.G.contains(N.Eb[0].Mp)||GqE(this,N),this.T=g.Cq(N.Eb)):Ym0(this)&&this.seekTo(this.player.getCurrentTime())}this.j.start()};
g.B(yu,g.CG);g.f=yu.prototype;g.f.cN=function(N,p,S){var O=this;this.m6();p=C2C(this,N.getId());p||(p=N.languageCode,p=this.B.isManifestless?A6Y(this,p,"386"):A6Y(this,p));if(p){var P=(p.index.BR(p.index.qh())-p.index.getStartTime(p.index.qh()))*1E3,W=this.D.J(),X=new g.Qi5(W),l=function(){O.X&&O.X.reset();O.N=!0};
W.U("html5_keep_caption_data_after_seek")&&(l=null);this.X=new KR0(X,this.D,p,function(b,h){S(b,N,h,P)},this.j||g.k9(p.info),l)}};
g.f.aI=function(){var N=this.N;this.N=!1;return N};
g.f.Cu=function(N){var p=this.j?[new g.bx({id:"rawcc",languageCode:"rawcc",languageName:"CC1",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"}),new g.bx({id:"rawcc",languageCode:"rawcc",languageName:"CC3",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"})]:this.B.isManifestless?evq(this,"386"):evq(this);p=g.z(p);for(var S=p.next();!S.done;S=p.next())g.eo(this.T,S.value);N()};
g.f.m6=function(){this.X&&(this.X.dispose(),this.X=null)};
g.f.o1=function(){return""};
g.f.Uq=function(){this.X&&(this.X.reset(),this.D.WD("captions"))};
var FO=/^#(?:[0-9a-f]{3}){1,2}$/i;var wxt=["left","right","center","justify"];g.B(Vu,g.R);g.f=Vu.prototype;g.f.jN=function(N,p){this.Ij=N;this.Ly=p;var S=g.HH(this.element,this.element.parentElement);this.WP=N-S.x;this.Vd=p-S.y};
g.f.Nf=function(N,p){if(N!==this.Ij||p!==this.Ly){g.PF(this.element,"ytp-dragging")||g.WF(this.element,"ytp-dragging");var S=g.aS(this.element);N=N-this.WP-.02*this.playerWidth;var O=p-this.Vd-.02*this.playerHeight,P=(N+S.width/2)/this.maxWidth*3;P=Math.floor(g.LB(P,0,2));var W=(O+S.height/2)/this.maxHeight*3;W=Math.floor(g.LB(W,0,2));p=P+W*3;N=(N+P/2*S.width)/this.maxWidth;N=g.LB(N,0,1)*100;S=(O+W/2*S.height)/this.maxHeight;S=g.LB(S,0,1)*100;this.B.params.gy=p;this.B.params.QF=S;this.B.params.Qr=
N;this.B.params.isDefault=!1;this.T.gy=p;this.T.QF=S;this.T.Qr=N;this.T.isDefault=!1;this.zk.gy=p;this.zk.QF=S;this.zk.Qr=N;this.zk.isDefault=!1;this.AT()}};
g.f.bC=function(){g.fE(this.element,"ytp-dragging")};
g.f.AT=function(){this.MV(this.j)};
g.f.getType=function(){return this.type};
g.f.MV=function(N){var p=this.kR?0:Math.min(this.LL(),this.maxWidth),S=this.Yu(),O=this.kR;if(O){var P=getComputedStyle(this.G.parentNode);P=LS(P.borderLeftWidth)+LS(P.borderRightWidth)+LS(P.paddingLeft)+LS(P.paddingRight)}else P=0;var W=P;P="";this.B.params.o0===3&&(P="rotate(180deg)");var X=O?"calc(96% - "+W+"px)":"96%";g.TP(this.element,{top:0,left:0,right:"",bottom:"",width:p?p+"px":"",height:S?S+"px":"","max-width":X,"max-height":X,margin:"",transform:""});this.YZ(N);P={transform:P,top:"",left:"",
width:p?p+"px":"",height:S?S+"px":"","max-width":"","max-height":""};var l=this.T.Qr*.96+2;X=this.T.gy;switch(X){case 0:case 3:case 6:(O=this.T.k6.fontSizeIncrement)&&O>0&&this.T.o0!==2&&this.T.o0!==3&&(l=Math.max(l/(1+O*2),2));P.left=l+"%";break;case 1:case 4:case 7:P.left=l+"%";l=this.G.offsetWidth;p||l?(p=p||l+1,P.width=p+"px",P["margin-left"]=O?p/-2-W/2+"px":p/-2+"px"):P.transform+=" translateX(-50%)";break;case 2:case 5:case 8:P.right=100-l+"%"}O=this.T.QF*.96+2;switch(X){case 0:case 1:case 2:P.top=
O+"%";break;case 3:case 4:case 5:P.top=O+"%";(S=S||this.element.clientHeight)?(P.height=S+"px",P["margin-top"]=S/-2+"px"):P.transform+=" translateY(-50%)";break;case 6:case 7:case 8:P.bottom=100-O+"%"}g.TP(this.element,P);if(this.K){S=this.G.offsetHeight;O=1;for(p=0;p<N.length;p++)P=N[p],typeof P.text==="string"&&(O+=P.text.split("\n").length-1,P.append||p===0||O++);S/=O;this.K.style.height=S+"px";this.K.style.width=S+"px";this.element.style.paddingLeft=S+5+"px";this.element.style.paddingRight=S+
5+"px";N=Number(this.element.style.marginLeft.replace("px",""))-S-5;S=Number(this.element.style.marginRight.replace("px",""))-S-5;this.element.style.marginLeft=N+"px";this.element.style.marginRight=S+"px"}};
g.f.YZ=function(N){var p;for(p=0;p<N.length&&N[p]===this.j[p];p++);if(this.xO||this.j.length>p)p=0,this.xO=!1,this.j=[],this.Y=this.i_=this.Qd=null,g.b9(this.G);for(;p<N.length;p++)kqE(this,N[p])};
g.f.LL=function(){return 0};
g.f.Yu=function(){return 0};
g.f.toString=function(){return g.R.prototype.toString.call(this)};NhC.prototype.clear=function(){this.X=this.time=this.mode=0;this.T=[];this.reset()};
NhC.prototype.reset=function(){this.mode=0;this.G.reset(0);this.K.reset(1)};
var pE0=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,
12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255];TF.prototype.set=function(N){this.type=N};
TF.prototype.get=function(){return this.type};
v3.prototype.clear=function(){this.state=0};
v3.prototype.update=function(){this.state=this.state===2?1:0};
v3.prototype.Uy=function(){return this.state!==0};
v3.prototype.matches=function(N,p){return this.Uy()&&N===this.j7&&p===this.T0};
Wsd.prototype.reset=function(){this.timestamp=this.T=0};
B3.prototype.updateTime=function(N){for(var p=1;p<=15;++p)for(var S=1;S<=32;++S)this.X[p][S].timestamp=N};
B3.prototype.debugString=function(){for(var N="\n",p=1;p<=15;++p){for(var S=1;S<=32;++S){var O=this.X[p][S];N=O.T===0?N+"_":N+String.fromCharCode(O.T)}N+="\n"}return N};
B3.prototype.reset=function(N){for(var p=0;p<=15;p++)for(var S=0;S<=32;S++)this.X[p][S].reset();this.G=N;this.T=0;this.B=this.row=1};
var XEf=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],fMC=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],lMQ=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,199,200,202,203,235,
206,207,239,212,217,249,219,171,187],bWt=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499];xLq.prototype.reset=function(N,p){this.K=p;this.style.set(2);this.B=this.N;this.G=this.j;this.T=this.B;var S=(N<<2)+(p<<1);this.N.reset(S);this.j.reset(S);this.text.reset((N<<2)+(p<<1)+1)};
qmY.prototype.reset=function(N){this.K=N;this.B.clear();this.G=this.X;this.X.reset(N,0);this.N.reset(N,1)};ThR.prototype.G=function(){};g.B(mG,g.WY);mG.prototype.toString=function(){return g.WY.prototype.toString.call(this)};g.B(UV,g.e);UV.prototype.B_=function(){return[]};
UV.prototype.reset=function(){};g.B(H3,g.WY);H3.prototype.toString=function(){return g.WY.prototype.toString.call(this)};
var ik=0;g.B(ac,UV);ac.prototype.reset=function(){this.N={};this.B=this.T=null;this.K=!0};
ac.prototype.B_=function(N,p){N=N.firstChild;N.getAttribute("format");p=p||0;Number.isFinite(p);N=Array.from(N.childNodes);N=g.z(N);for(var S=N.next();!S.done;S=N.next())if(S=S.value,S.nodeType===1)switch(S.tagName){case "head":var O=S;break;case "body":var P=S}if(O)for(O=Array.from(O.childNodes),O=g.z(O),N=O.next();!N.done;N=O.next())if(N=N.value,N.nodeType===1)switch(N.tagName){case "pen":S=N.getAttribute("id");var W=this.pens,X={},l=N.getAttribute("p");l&&Object.assign(X,this.pens[l]);l=gL(N,"b");
l!=null&&(X.bold=l);l=gL(N,"i");l!=null&&(X.italic=l);l=gL(N,"u");l!=null&&(X.underline=l);l=c3(N,"et");l!=null&&(X.charEdgeStyle=l);l=c3(N,"of");l!=null&&(X.offset=l);l=nS(N,"bc");l!=null&&(X.background=l);l=nS(N,"ec");l!=null&&(X.e5=l);l=nS(N,"fc");l!=null&&(X.color=l);l=c3(N,"fs");l!=null&&l!==0&&(X.fontFamily=l);l=Qu(N,"sz");l!==void 0&&(X.fontSizeIncrement=l/100-1);l=Qu(N,"bo");l!==void 0&&(X.backgroundOpacity=l/255);l=Qu(N,"fo");l!==void 0&&(X.textOpacity=l/255);l=c3(N,"rb");l!=null&&l!==10&&
l!==0&&(X.pg=l>10?l-1:l);N=c3(N,"hg");N!=null&&(X.ET=N);W[S]=X;break;case "ws":S=N.getAttribute("id");this.Y[S]=EYC(this,N);break;case "wp":S=N.getAttribute("id"),this.j[S]=$L0(this,N)}if(P){O=[];P=Array.from(P.childNodes);P=g.z(P);for(N=P.next();!N.done;N=P.next())if(N=N.value,N.nodeType===1)switch(N.tagName){case "w":this.T=Jdf(this,N,p,!1);(N=this.N[this.T.id])&&N.end>this.T.start&&(N.end=this.T.start);this.N[this.T.id]=this.T;O.push(this.T);break;case "p":var b=N;l=p;S=[];W=b.getAttribute("w")||
this.G;X=!!gL(b,"a");l=(Qu(b,"t")||0)+l;var h=Qu(b,"d")||5E3;X||(!this.K&&this.B&&this.B.windowId===W&&this.B.end>l&&(this.B.end=l),this.B&&this.B.text==="\n"&&(this.B.text=""));var x=X?6:5,y=b.getAttribute("p");y=y?this.pens[y]:null;var V=Array.from(b.childNodes);V.length&&(this.K=b.getAttribute("d")!=null);for(b=0;b<V.length;b++){var L=V[b],T=void 0;b>0&&(X=!0);var E=void 0;L.nodeType===1&&(E=L);if(E&&E.tagName==="s"){if((L=(L=E.getAttribute("p"))?this.pens[L]:null)&&L.pg&&(L.pg===1?(L=V.slice(b,
b+4),L.length===4&&(T=BhB(l,h,W,X,x,L,this.pens),b+=3)):T=BhB(l,h,W,X,x,[E],this.pens)),!T){var m=E;T=l;E=h;L=W;var H=X,Q=x,n=m.textContent?m.textContent:"",K=m.getAttribute("p");K=K?this.pens[K]:null;m=Qu(m,"t")||0;T=new mG(T+m,E-m,Q,L,n,H,K)}}else T=new mG(l,h,x,W,L.textContent||"",X,y);S.push(T);this.B=T}if(S.length>0)for(S[0].windowId===this.G&&(this.T=Jdf(this,N,p,!0),O.push(this.T)),N=g.z(S),S=N.next();!S.done;S=N.next())S=S.value,S.windowId=this.T.id,this.T.T.push(S),O.push(S)}p=O}else p=[];
return p};var Xkf=new Map([[9,1],[10,1],[11,2],[12,3],[13,4],[14,5]]);g.B(rL,UV);rL.prototype.reset=function(){this.B.clear()};
rL.prototype.B_=function(N,p){var S=JSON.parse(N);if(!S)return[];if(S.pens){N=0;for(var O=g.z(S.pens),P=O.next();!P.done;P=O.next()){P=P.value;var W={},X=P.pParentId;X&&Object.assign(W,this.T.get(X));P.bAttr&&(W.bold=!0);P.iAttr&&(W.italic=!0);P.uAttr&&(W.underline=!0);X=P.ofOffset;X!=null&&(W.offset=X);P.szPenSize!==void 0&&(W.fontSizeIncrement=P.szPenSize/100-1);X=P.etEdgeType;X!=null&&(W.charEdgeStyle=X);P.ecEdgeColor!==void 0&&(W.e5=MM(P.ecEdgeColor));X=P.fsFontStyle;X!=null&&X!==0&&(W.fontFamily=
X);P.fcForeColor!==void 0&&(W.color=MM(P.fcForeColor));P.foForeAlpha!==void 0&&(W.textOpacity=P.foForeAlpha/255);P.bcBackColor!==void 0&&(W.background=MM(P.bcBackColor));P.boBackAlpha!==void 0&&(W.backgroundOpacity=P.boBackAlpha/255);(X=P.rbRuby)&&X!==10&&(W.pg=X>10?X-1:X,W.G_=Xkf.get(W.pg));P.hgHorizGroup&&(W.ET=P.hgHorizGroup);this.T.set(N++,W)}}if(S.wsWinStyles)for(N=0,O=g.z(S.wsWinStyles),P=O.next();!P.done;P=O.next())P=P.value,W={},(X=P.wsParentId)?Object.assign(W,this.G.get(X)):Object.assign(W,
this.K),P.mhModeHint!==void 0&&(W.wr=P.mhModeHint),P.juJustifCode!==void 0&&(W.textAlign=P.juJustifCode),P.pdPrintDir!==void 0&&(W.o0=P.pdPrintDir),P.sdScrollDir!==void 0&&(W.Xx=P.sdScrollDir),P.wfcWinFillColor!==void 0&&(W.windowColor=MM(P.wfcWinFillColor)),P.wfoWinFillAlpha!==void 0&&(W.windowOpacity=P.wfoWinFillAlpha/255),this.G.set(N++,W);if(S.wpWinPositions)for(N=0,O=g.z(S.wpWinPositions),P=O.next();!P.done;P=O.next())P=P.value,W={},(X=P.wpParentId)&&Object.assign(W,this.X.get(X)),P.ahHorPos!==
void 0&&(W.Qr=P.ahHorPos),P.apPoint!==void 0&&(W.gy=P.apPoint),P.avVerPos!==void 0&&(W.QF=P.avVerPos),P.ccCols!==void 0&&(W.kQ=P.ccCols),P.rcRows!==void 0&&(W.K0=P.rcRows),this.X.set(N++,W);if(S.events){N=[];S=g.z(S.events);for(O=S.next();!O.done;O=S.next()){var l=O.value;P=(l.tStartMs||0)+p;W=l.dDurationMs||0;if(l.id)X=String(l.id),O=mLs(this,l,P,W,X),N.push(O),this.B.set(X,O);else{l.wWinId?X=l.wWinId.toString():(X="_"+ik++,O=mLs(this,l,P,W,X),N.push(O),this.B.set(X,O));O=N;var b=l;W===0&&(W=5E3);
l=this.B.get(X);var h=!!b.aAppend,x=h?6:5,y=b.segs,V=null;b.pPenId&&(V=this.T.get(b.pPenId));for(b=0;b<y.length;b++){var L=y[b],T=L.utf8;if(T){var E=L.tOffsetMs||0,m=null;L.pPenId&&(m=this.T.get(L.pPenId));if((l.params.wr!=null?l.params.wr:l.T.length>1?1:0)===2&&h&&T==="\n")continue;L=null;var H=[],Q;if(Q=m&&m.pg===1){Q=y;var n=b;if(n+3>=Q.length||!Q[n+1].pPenId||!Q[n+2].pPenId||!Q[n+3].pPenId)Q=!1;else{var K=Q[n+1].pPenId;(K=this.T.get(K))&&K.pg&&K.pg===2?(K=Q[n+2].pPenId,K=this.T.get(K),!K||!K.pg||
K.pg<3?Q=!1:(K=Q[n+3].pPenId,Q=(K=this.T.get(K))&&K.pg&&K.pg===2?!0:!1)):Q=!1}}if(Q)E=y[b+1].utf8,L=y[b+3].utf8,Q=y[b+2].utf8,n=this.T.get(y[b+2].pPenId),T=vYY(T,E,Q,L,n),L=new mG(P,W,x,X,T,h,m),b+=3;else{if(T.indexOf("<")>-1){var d=void 0;H=m;Q=V;n=P;K=W;var D=E,u=x,oH=h,bX=[],I=g.pX("<html>"+T+"</html>");if(!I.getElementsByTagName("parsererror").length&&((d=I.firstChild)==null?0:d.childNodes.length))for(d=g.z(I.firstChild.childNodes),I=d.next();!I.done;I=d.next()){I=I.value;var A=void 0,k=void 0,
v=(k=(A=I.textContent)==null?void 0:A.replace(/\n/g,""))!=null?k:"";if(I.nodeType!==3||v&&v.match(/^ *$/)==null){A={};Object.assign(A,H||Q);k=void 0;switch((k=I)==null?void 0:k.tagName){case "b":A.bold=!0;break;case "i":A.italic=!0;break;case "u":A.underline=!0}bX.push(new mG(n+D,K-D,u,l.id,v,oH,A))}}H=bX}H.length||(H=[new mG(P+E,W-E,x,l.id,T,h,m||V)])}if(H.length)for(h=g.z(H),m=h.next();!m.done;m=h.next())m=m.value,O.push(m),l.T.push(m);else L&&(O.push(L),l.T.push(L))}h=!0}}}p=N}else p=[];return p};g.B(KS,g.CG);KS.prototype.cN=function(N,p,S){QYE(this.videoData.videoId,N.vssId,S)};
KS.prototype.Cu=function(N){if(this.audioTrack)for(var p=g.z(this.audioTrack.captionTracks),S=p.next();!S.done;S=p.next())g.eo(this.T,S.value);N()};g.B(YF,Vu);YF.prototype.YZ=function(N){var p=this.B.T;Vu.prototype.YZ.call(this,N);for(N=N.length;N<p.length;N++){var S=p[N];if(W&&S.T===P)var O=W;else{O={};Object.assign(O,S.T);Object.assign(O,f7G);var P=S.T;var W=O}kqE(this,S,O)}};
var f7G={jL:!0};g.B(GF,ThR);GF.prototype.G=function(N,p,S,O,P){if(S<O){var W="_"+ik++;S=S/1E3-this.N;O=O/1E3-this.N;N=new H3(S,O-S,5,W,{textAlign:0,gy:0,Qr:p*2.5,QF:N*5.33});P=new mG(S,O-S,5,W,P);this.B.push(N);this.B.push(P)}};
g.B(CS,UV);CS.prototype.B_=function(N){N=new GF(N,N.byteLength,this.B);if(ULs(N)){for(;N.byteOffset<N.T.byteLength;)for(N.version===0?N.X=eO(N)*(1E3/45):N.version===1&&(N.X=eO(N)*4294967296+eO(N)),N.K=dL(N);N.K>0;N.K--){var p=dL(N),S=dL(N),O=dL(N);p&4&&(p&3)===this.track&&(this.track===0||this.track===1)&&(p=this.T,p.T.push({time:N.X,type:this.track,Je:S,yM:O,order:p.T.length}))}P9Q(this.T,N);return N.B}return[]};
CS.prototype.reset=function(){this.T.clear()};g.B(AA,Vu);g.f=AA.prototype;g.f.AT=function(){g.Nv(this.Np)};
g.f.ZIP=function(){g.fE(this.element,"ytp-rollup-mode");this.MV(this.Nt,!0)};
g.f.Yu=function(){return this.X?this.u_:this.W};
g.f.LL=function(){return this.X?this.W:this.u_};
g.f.MV=function(N,p){this.Nt=N;if(this.B.params.K0){for(var S=0,O=0;O<this.j.length&&S<N.length;O++)this.j[O]===N[S]&&S++;S>0&&S<N.length&&(N=this.j.concat(N.slice(S)));this.KI=this.u_;this.W=this.u_=0;Vu.prototype.MV.call(this,N);QCV(this,p)}Vu.prototype.MV.call(this,N)};g.B(gYt,g.CG);g.f=gYt.prototype;g.f.cN=function(N,p,S){var O=this;this.m6();p=nY0(this,N.getId());p||(p=N.languageCode,p=this.B.isManifestless?rdl(this,p,"386"):rdl(this,p));p&&(this.N=N,this.j=p,this.X=function(P,W){cdG(O,P,S,W)},this.D.addEventListener("sabrCaptionsDataLoaded",this.X),this.D.publish("sabrCaptionsTrackChanged",g.N2(p.info,this.B.Ua)))};
g.f.Cu=function(N){var p=this.B.isManifestless?FsB(this,"386"):FsB(this);p=g.z(p);for(var S=p.next();!S.done;S=p.next())g.eo(this.T,S.value);N()};
g.f.m6=function(){this.X!=null&&(this.D.removeEventListener("sabrCaptionsDataLoaded",this.X),this.X=null);this.N=this.j=null;this.D.publish("sabrCaptionsTrackChanged",null)};
g.f.o1=function(){return""};
g.f.Uq=function(){this.D.WD("captions")};g.B(tA,UV);
tA.prototype.B_=function(N,p){var S=[];N=N.split(l7l);for(var O=1;O<N.length;O++){var P=N[O],W=p;if(P!==""&&!bxd.test(P)){var X=j7Y.exec(P);if(X&&X.length>=4){var l=YiY(X[1]),b=YiY(X[2])-l;l+=W;var h=(X=X[3])?X.split(" "):[];X={};var x=null;var y="";var V=null,L="";h=g.z(h);for(var T=h.next();!T.done;T=h.next())if(T=T.value.split(":"),T.length===2){var E=T[1];switch(T[0]){case "line":T=E.split(",");T[0].endsWith("%")&&(x=T[0],X.QF=Number.parseInt(x,10),T.length===2&&(y=T[1].trim()));break;case "position":T=
E.split(",");V=T[0];X.Qr=Number.parseInt(V,10);T.length===2&&(L=T[1].trim());break;case "align":switch(E){case "start":X.textAlign=0;break;case "middle":X.textAlign=2;break;case "end":X.textAlign=1}}}x||y||(y="end");if(!V)switch(X.textAlign){case 0:X.Qr=0;break;case 1:X.Qr=100;break;case 2:X.Qr=50}if(X.textAlign!=null){x=0;switch(y){case "center":x+=3;break;case "end":x+=6;break;default:x+=0}switch(L){case "line-left":x+=0;break;case "center":x+=1;break;case "line-right":x+=2;break;default:switch(X.textAlign){case 0:x+=
0;break;case 2:x+=1;break;case 1:x+=2}}y=x<0||x>8?7:x;X.gy=y}P=P.substring(j7Y.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");L=X;X=P;P={};if(X.indexOf("<")<0&&X.indexOf("&")<0)W=GbR(l,b,5,L),b=new mG(l,b,5,W.id,X,!1,g.rD(P)?void 0:P),S.push(W),S.push(b),W.T.push(b);else for(y=X.split(s7l),y.length===1?(X=5,L=GbR(l,b,X,L)):(x=X=6,L=Object.assign({kQ:32},L),L=new H3(l,b,x,"_"+ik++,L)),S.push(L),x=l,V=0;V<y.length;V++)h=y[V],V%2===0?(T=g.pX("<html>"+h+"</html>"),T.getElementsByTagName("parsererror").length?
(E=T.createElement("span"),E.appendChild(T.createTextNode(h))):E=T.firstChild,Ksf(this,x,b-(x-l),X,L,V>0,E,P,S)):x=YiY(h)+W}j7Y.lastIndex=0}}return S};
var bxd=/^NOTE/,l7l=/(?:\r\n|\r|\n){2,}/,j7Y=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})(?:[\\t ]*)(.*)(?:\\r\\n|\\r|\\n)","gm"),s7l=RegExp("<((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})>");g.Dc.UX(tA,{B_:"wvppt"});g.B(uk,g.e);
uk.prototype.B_=function(N,p,S,O){O=O||0;S=eWy(this,N,S||0);N=[];try{for(var P=g.z(S),W=P.next();!W.done;W=P.next()){var X=W.value,l=X.trackData,b=X.O6;if(typeof l!=="string"){S=N;var h=S.concat,x=p,y=l,V=b,L=O;if(!HWq(y))throw Error("Invalid binary caption track data");this.T||(this.T=new CS(L,x));var T=this.T.B_(y,V);var E=h.call(S,T)}else{if(l.substring(0,6)==="WEBVTT"){S=N;var m=S.concat;this.T||(this.T=new tA);var H=this.T.B_(l,b);Math.random()<.01&&g.rO(Error("Deprecated subtitles format in web player: WebVTT"));var Q=
m.call(S,H)}else{S=N;var n=S.concat;a:{x=p;if(l[0]==="{")try{this.T||(this.T=new rL(C9G(x)));var K=this.T.B_(l,b);break a}catch(I){g.nK(I);K=[];break a}var d=g.pX(l);if(!d||!d.firstChild){var D=Error("Invalid caption track data");D.params=l;throw D;}if(d.firstChild.tagName==="timedtext"){if(Number(d.firstChild.getAttribute("format"))===3){y=d;this.T||(this.T=new ac(C9G(x),this.aj));K=this.T.B_(y,b);break a}var u=Error("Unsupported subtitles format in web player (Format2)");u.params=l;throw u;}if(d.firstChild.tagName===
"transcript"){var oH=Error("Unsupported subtitles format in web player (Format1)");oH.params=l;throw oH;}var bX=Error("Invalid caption track data");bX.params=l;throw bX;}Q=n.call(S,K)}E=Q}N=E}return N}catch(I){return this.logger.T(187101178,"Captions parsing failed: "+I.message+". "),this.clear(),[]}};
uk.prototype.clear=function(){this.T&&this.T.dispose();this.T=null};
uk.prototype.reset=function(){this.T&&this.T.reset()};
uk.prototype.BP=function(){g.e.prototype.BP.call(this);this.clear()};var pj={windowColor:"#080808",windowOpacity:0,textAlign:2,gy:7,Qr:50,QF:100,isDefault:!0,k6:{background:"#080808",backgroundOpacity:.75,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}};g.B(wL,g.dg);g.f=wL.prototype;g.f.BP=function(){if(this.K||this.xO){var N=this.D.PD();N&&!N.wH()&&N.yj()}else WwC(this,!1);g.dg.prototype.BP.call(this)};
g.f.LC=function(){return this.aj.U("html5_honor_caption_availabilities_in_audio_track")&&this.G!=="LIVE"&&this.G!=="SABR_LIVE"};
g.f.bI=function(){if(this.vP)return this.K||this.xO;var N=this.getAudioTrack();if(this.LC()){if(!N.captionTracks.length)return!1;if(!this.T)return!0}N=U1V(N,g.wN(this.aj));return N==="CAPTIONS_INITIAL_STATE_ON_REQUIRED"?!0:N==="CAPTIONS_INITIAL_STATE_OFF_REQUIRED"?Rc(this):wEE(this)||Rc(this)?!0:RWl(this)};
g.f.load=function(){var N=this;g.dg.prototype.load.call(this);this.W=this.getAudioTrack();this.T?this.B&&(this.Ij.clear(),this.K?kbq(this,!0):this.player.getPresentingPlayerType()!==3&&this.T.cN(this.B,"json3",function(p,S,O,P){if(p){var W;N4B(N,(W=N.B)!=null?W:void 0);N.T.aI()&&(N.Qd=[],N.D.WD("captions"),hA(N.i_),N.Ij.reset());if(N.videoData.kW){var X;O=((X=O)!=null?X:0)+N.videoData.kW}p=N.Ij.B_(p,S,O,P);if(N.Ly)for(S=g.z(p),P=S.next();!P.done;P=S.next())P=P.value,P.X=N.videoData.clientPlaybackNonce,
P.qB=N.videoData.kW;S=!N.aj.U("html5_keep_caption_data_after_seek")&&(N.G==="LIVE"||N.G==="SABR_LIVE");N.player.cD(p,void 0,S);!N.Y||N.xO||ZF(N)||!N.aj.z7||g.aN(N.aj)||g.cP(N.aj)||g.eM(N.aj)||N.aj.Qd==="shortspage"||N.player.isInline()||(g.pE(N.rH),p=zWC({gy:0,Qr:5,QF:5,K0:2,textAlign:0,o0:0,lang:"en"}),N.jS=[p],S=["Click "," for settings"],N.WP||(P=new g.sU(g.g5()),g.C(N,P),N.WP=P.element),P=p.end-p.start,(W=g.jD(N.B))&&N.jS.push(new mG(p.start,P,0,p.id,W)),N.jS.push(new mG(p.start,P,0,p.id,S[0]),
new mG(p.start,P,0,p.id,N.WP,!0),new mG(p.start,P,0,p.id,S[1],!0)),N.player.cD(N.jS),g.q7(N.rH));!N.Y||N.xO||ZF(N)||(g.wN(N.aj)?qM(N,!0):N3(N,!0),N.W&&(N.W.G=N.B),N.player.rD());N.Y=!1}}),this.K||this.xO||ZF(this)||this.player.vz("captionschanged",g.so(this.B))):(this.T=IMs(this),g.C(this,this.T),this.T.Cu(function(){ZWd(N)}))};
g.f.unload=function(){this.K&&this.B?kbq(this,!1):(this.rH&&g.pE(this.rH),this.player.WD("captions"),this.Qd=[],this.T&&this.T.m6(),this.Ij.clear(),this.u_&&this.player.cD(this.u_),this.oi());g.dg.prototype.unload.call(this);this.player.rD();this.player.vz("captionschanged",{})};
g.f.create=function(){this.bI()&&this.load();var N;a:{var p,S,O;if(this.aj.U("web_player_nitrate_promo_tooltip")&&((p=this.videoData.getPlayerResponse())==null?0:(S=p.captions)==null?0:(O=S.playerCaptionsTracklistRenderer)==null?0:O.enableTouchCaptionsNitrate)){var P,W;if(p=(N=this.videoData.getPlayerResponse())==null?void 0:(P=N.captions)==null?void 0:(W=P.playerCaptionsTracklistRenderer)==null?void 0:W.captionTracks)for(N=g.z(p),P=N.next();!P.done;P=N.next())if(P=P.value,P.kind==="asr"&&P.languageCode===
"en"){N=!0;break a}}N=!1}N&&this.D.publish("showpromotooltip",this.j.element)};
g.f.Qck=function(){for(var N=this.D.PD().fI().textTracks,p=null,S=0;S<N.length;S++)if(N[S].mode==="showing")a:{p=g.iv(this.T.T,!0);for(var O=0;O<p.length;O++)if(p[O].toString()===N[S].id){p=p[O];break a}p=null}(this.loaded?this.B:null)!==p&&kF(this,p,!0)};
g.f.Veb=function(){!this.B&&this.K||this.unload()};
g.f.onCueRangeEnter=function(N){this.Qd.push(N);hA(this.i_)};
g.f.onCueRangeExit=function(N){g.I0(this.Qd,N);this.T instanceof yu&&this.T.j&&this.player.nE([N]);hA(this.i_)};
g.f.getCaptionWindowContainerId=function(){return this.j.element.id};
g.f.wDp=function(){P1G(this,this.jS);this.jS=null};
g.f.Dx=function(){var N=this;if(!this.kR||!this.K){this.i_.stop();g.q3g(this.Np);this.Qd.sort(g.X4);var p=this.Qd;if(this.u_){var S=g.sz(p,function(W){return this.u_.indexOf(W)===-1},this);
S.length&&(p=S)}p=g.z(p);for(S=p.next();!S.done;S=p.next())o8G(this,S.value);p=g.z(Object.entries(this.py));var O=p.next();for(S={};!O.done;S={CH:void 0,Yf:void 0},O=p.next()){var P=g.z(O.value);O=P.next().value;P=P.next().value;S.CH=O;S.Yf=P;this.Np[S.CH]?(S.Yf.element.parentNode||(S.Yf instanceof AA||S.Yf instanceof YF||g.i2(this.py,function(W){return function(X,l){l!==W.CH&&X.B.params.gy===W.Yf.B.params.gy&&X.B.params.Qr===W.Yf.B.params.Qr&&X.B.params.QF===W.Yf.B.params.QF&&(X.dispose(),delete N.py[l]);
return l===W.CH}}(S),this),this.j.element.appendChild(S.Yf.element)),S.Yf.MV(this.Np[S.CH])):(S.Yf.dispose(),delete this.py[S.CH])}}};
g.f.P4C=function(){tet(this,{},!0);this.player.vz("captionssettingschanged")};
g.f.Cm=function(){var N=pj.k6;N={background:N.background,backgroundOpacity:N.backgroundOpacity,charEdgeStyle:N.charEdgeStyle,color:N.color,fontFamily:N.fontFamily,fontSizeIncrement:N.fontSizeIncrement,fontStyle:N.bold&&N.italic?3:N.bold?1:N.italic?2:0,textOpacity:N.textOpacity,windowColor:pj.windowColor,windowOpacity:pj.windowOpacity};var p=r6y()||{};p.background!=null&&(N.background=p.background);p.backgroundOverride!=null&&(N.backgroundOverride=p.backgroundOverride);p.backgroundOpacity!=null&&(N.backgroundOpacity=
p.backgroundOpacity);p.backgroundOpacityOverride!=null&&(N.backgroundOpacityOverride=p.backgroundOpacityOverride);p.charEdgeStyle!=null&&(N.charEdgeStyle=p.charEdgeStyle);p.charEdgeStyleOverride!=null&&(N.charEdgeStyleOverride=p.charEdgeStyleOverride);p.color!=null&&(N.color=p.color);p.colorOverride!=null&&(N.colorOverride=p.colorOverride);p.fontFamily!=null&&(N.fontFamily=p.fontFamily);p.fontFamilyOverride!=null&&(N.fontFamilyOverride=p.fontFamilyOverride);p.fontSizeIncrement!=null&&(N.fontSizeIncrement=
p.fontSizeIncrement);p.fontSizeIncrementOverride!=null&&(N.fontSizeIncrementOverride=p.fontSizeIncrementOverride);p.fontStyle!=null&&(N.fontStyle=p.fontStyle);p.fontStyleOverride!=null&&(N.fontStyleOverride=p.fontStyleOverride);p.textOpacity!=null&&(N.textOpacity=p.textOpacity);p.textOpacityOverride!=null&&(N.textOpacityOverride=p.textOpacityOverride);p.windowColor!=null&&(N.windowColor=p.windowColor);p.windowColorOverride!=null&&(N.windowColorOverride=p.windowColorOverride);p.windowOpacity!=null&&
(N.windowOpacity=p.windowOpacity);p.windowOpacityOverride!=null&&(N.windowOpacityOverride=p.windowOpacityOverride);return N};
g.f.Hb=function(N,p){var S={};Object.assign(S,r6y());Object.assign(S,N);tet(this,S,p);this.player.vz("captionssettingschanged")};
g.f.oi=function(){!this.K&&this.loaded&&(g.mR(this.py,function(N,p){N.dispose();delete this.py[p]},this),this.Dx())};
g.f.E$=function(N,p){switch(N){case "fontSize":if(isNaN(p))break;N=g.LB(p,-2,4);this.Hb({fontSizeIncrement:N});return N;case "reload":p&&!this.K&&kF(this,this.B,!0);break;case "stickyLoading":p!==void 0&&this.aj.j&&(g.wN(this.aj)?qM(this,!!p):N3(this,!!p));break;case "track":return Oxf(this,p);case "tracklist":return this.T?g.a2(g.iv(this.T.T,!(!p||!p.includeAsr)),function(S){return g.so(S)}):[];
case "translationLanguages":return this.T?this.T.K.map(function(S){return Object.assign({},S)}):[];
case "sampleSubtitles":this.K||p===void 0||WwC(this,!!p);break;case "sampleSubtitlesCustomized":this.K||WwC(this,!!p,p);break;case "recommendedTranslationLanguages":return g.d$();case "defaultTranslationSourceTrackIndices":return this.T?this.T.Y:[]}};
g.f.getOptions=function(){var N="reload fontSize track tracklist translationLanguages sampleSubtitle".split(" ");this.aj.j&&N.push("stickyLoading");return N};
g.f.Z_=function(){var N=this.B;if(this.D.G2("captions")){if(this.aj.U("html5_modify_caption_vss_logging")){var p;return(N=(p=this.videoData.lr)!=null?p:null)?{cc:g.ikg(N)}:{}}if(N)return p=N.vssId,N.translationLanguage&&p&&(p="t"+p+"."+g.hy(N)),{cc:p}}return{}};
g.f.Z1d=function(){this.isSubtitlesOn()?(g.wN(this.aj)?qM(this,!1):N3(this,!1),N4B(this),this.aj.U("html5_report_caption_format_change")?kF(this,null,!0):(this.unload(),Rc(this,!0)&&kF(this,Ic(this),!1))):this.FW()};
g.f.FW=function(){var N=ZF(this)||!this.B?DF(this,!0):this.B;this.aj.U("html5_report_caption_format_intent")&&N&&this.h3(N.vssId,"m");this.isSubtitlesOn()||kF(this,ZF(this)||!this.B?DF(this,!0):this.B,!0)};
g.f.isSubtitlesOn=function(){return!!this.loaded&&!!this.B&&!ZF(this)};
g.f.OyP=function(){var N=ZF(this);Rc(this,N)?kF(this,this.getAudioTrack().T,!1):this.videoData.captionTracks.length&&(this.loaded&&this.unload(),this.LC()&&(this.Y=!1,this.B=null,this.T&&(this.T.dispose(),this.T=null)),this.bI()&&(N?kF(this,DF(this,!1),!1):this.load()))};
g.f.Hs=function(N){N&&(this.zk={top:N.top,right:N.right,bottom:N.bottom,left:N.left,width:1-N.left-N.right,height:1-N.top-N.bottom},this.j.element.style.top=this.zk.top*100+"%",this.j.element.style.left=this.zk.left*100+"%",this.j.element.style.width=this.zk.width*100+"%",this.j.element.style.height=this.zk.height*100+"%",this.j.element.style.position="absolute",N=SwB(this))&&(this.j.element.style.width=N.width+"px",this.j.element.style.height=N.height+"px")};
g.f.onVideoDataChange=function(N,p){N==="newdata"&&(this.videoData=p,this.loaded&&this.unload(),this.Y=!1,this.B=null,this.T&&(this.T.dispose(),this.T=null,this.player.vz("captionschanged",{})),this.bI()&&this.load())};
g.f.getAudioTrack=function(){return this.Ly&&this.player.getPresentingPlayerType()===2?this.videoData.dn:this.player.getAudioTrack()};
g.f.EOB=function(){var N=this.D.PD();N&&!N.wH()&&N.yj();this.D.isFullscreen()?(this.K=this.vP=!0,this.loaded&&ZWd(this)):(this.vP=this.aj.controlsType==="3",this.K=AdQ(this));kF(this,this.B)};
g.f.CV=function(){var N,p,S,O=(N=this.videoData.getPlayerResponse())==null?void 0:(p=N.captions)==null?void 0:(S=p.playerCaptionsTracklistRenderer)==null?void 0:S.openTranscriptCommand;O&&this.player.YO("innertubeCommand",O)};
g.f.Wq=function(N,p,S){var O=/&|,|:|;|(\n)|(\s)|(\/)|(\\)/gm,P="";N&&(P=N.vssId,P=P.replace(O,""));var W="";N&&N.getId()&&(W=N.getId()||"");N&&N.getXtags()&&(N=N.getXtags(),N=N.replace(O,""),W=W.concat(";"+N));this.D.Wq(p?P:"",p?W:"",S)};
g.f.h3=function(N,p){N=(N||"").replace(/&|,|:|;|(\n)|(\s)|(\/)|(\\)/gm,"");N.length>0&&this.D.h3(N,p)};
g.f.Uq=function(){this.T&&this.T.Uq()};
g.Dc.UX(wL,{Dx:"smucd"});g.Gc("captions",wL);})(_yt_player);
