(function(g){var window=this;'use strict';var Kwy=function(N,p){N.YO("onAutonavCoundownStarted",p)},b6=function(N,p,S){g.bS(N.element,"ytp-suggestion-set",!!p.videoId);
var O=p.playlistId;S=p.f7(S?S:"mqdefault.jpg");var P=null,W=null;p instanceof g.zo&&(p.lengthText?(P=p.lengthText||null,W=p.Zn||null):p.lengthSeconds&&(P=g.H4(p.lengthSeconds),W=g.H4(p.lengthSeconds,!0)));var X=!!O;O=X&&g.v7(O).type==="RD";var l=p instanceof g.zo?p.isLivePlayback:null,b=p instanceof g.zo?p.isUpcoming:null,h=p.author,x=p.shortViewCount,y=p.publishedTimeText,V=[],L=[];h&&V.push(h);x&&(V.push(x),L.push(x));y&&L.push(y);S={title:p.title,author:h,author_and_views:V.join(" \u2022 "),aria_label:p.ariaLabel||
g.vY("Watch $TITLE",{TITLE:p.title}),duration:P,timestamp:W,url:p.m2(),is_live:l,is_upcoming:b,is_list:X,is_mix:O,background:S?"background-image: url("+S+")":"",views_and_publish_time:L.join(" \u2022 "),autoplayAlternativeHeader:p.Fz};p instanceof g.B7&&(S.playlist_length=p.playlistLength);N.update(S)},j6=function(N){var p=N.J(),S=p.G;
g.R.call(this,{S:"a",Z:"ytp-autonav-suggestion-card",V:{href:"{{url}}",target:S?p.W:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},L:[{S:"div",Ky:["ytp-autonav-endscreen-upnext-thumbnail","ytp-autonav-thumbnail-small"],V:{style:"{{background}}"},L:[{S:"div",V:{"aria-label":"{{timestamp}}"},Ky:["ytp-autonav-timestamp"],l_:"{{duration}}"},{S:"div",Ky:["ytp-autonav-live-stamp"],l_:"Live"},{S:"div",
Ky:["ytp-autonav-upcoming-stamp"],l_:"Upcoming"},{S:"div",Z:"ytp-autonav-list-overlay",L:[{S:"div",Z:"ytp-autonav-mix-text",l_:"Mix"},{S:"div",Z:"ytp-autonav-mix-icon"}]}]},{S:"div",Ky:["ytp-autonav-endscreen-upnext-title","ytp-autonav-title-card"],l_:"{{title}}"},{S:"div",Ky:["ytp-autonav-endscreen-upnext-author","ytp-autonav-author-card"],l_:"{{author}}"},{S:"div",Ky:["ytp-autonav-endscreen-upnext-author","ytp-autonav-view-and-date-card"],l_:"{{views_and_publish_time}}"}]});this.D=N;this.suggestion=
null;this.T=S;this.listen("click",this.onClick);this.listen("keypress",this.onKeyPress)},sT=function(N,p){p=p===void 0?!1:p;
g.R.call(this,{S:"div",Z:"ytp-autonav-endscreen-countdown-overlay"});var S=this;this.j=p;this.cancelCommand=this.K=void 0;this.X=0;this.container=new g.R({S:"div",Z:"ytp-autonav-endscreen-countdown-container"});g.C(this,this.container);this.container.Rj(this.element);p=N.J();var O=p.G;this.D=N;this.suggestion=null;this.onVideoDataChange("newdata",this.D.getVideoData());this.C(N,"videodatachange",this.onVideoDataChange);this.T=new g.R({S:"div",Z:"ytp-autonav-endscreen-upnext-container",V:{"aria-label":"{{aria_label}}",
"data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},L:[{S:"div",Z:"ytp-autonav-endscreen-upnext-header"},{S:"div",Z:"ytp-autonav-endscreen-upnext-alternative-header",l_:"{{autoplayAlternativeHeader}}"},{S:"a",Z:"ytp-autonav-endscreen-link-container",V:{href:"{{url}}",target:O?p.W:""},L:[{S:"div",Z:"ytp-autonav-endscreen-upnext-thumbnail",V:{style:"{{background}}"},L:[{S:"div",V:{"aria-label":"{{timestamp}}"},Ky:["ytp-autonav-timestamp"],
l_:"{{duration}}"},{S:"div",Ky:["ytp-autonav-live-stamp"],l_:"Live"},{S:"div",Ky:["ytp-autonav-upcoming-stamp"],l_:"Upcoming"}]},{S:"div",Z:"ytp-autonav-endscreen-video-info",L:[{S:"div",Z:"ytp-autonav-endscreen-premium-badge"},{S:"div",Z:"ytp-autonav-endscreen-upnext-title",l_:"{{title}}"},{S:"div",Z:"ytp-autonav-endscreen-upnext-author",l_:"{{author}}"},{S:"div",Z:"ytp-autonav-view-and-date",l_:"{{views_and_publish_time}}"},{S:"div",Z:"ytp-autonav-author-and-view",l_:"{{author_and_views}}"}]}]}]});
g.C(this,this.T);this.T.Rj(this.container.element);O||this.C(this.T.gH("ytp-autonav-endscreen-link-container"),"click",this.lj);this.D.createClientVe(this.container.element,this,115127);this.D.createClientVe(this.T.gH("ytp-autonav-endscreen-link-container"),this,115128);this.overlay=new g.R({S:"div",Z:"ytp-autonav-overlay"});g.C(this,this.overlay);this.overlay.Rj(this.container.element);this.B=new g.R({S:"div",Z:"ytp-autonav-endscreen-button-container"});g.C(this,this.B);this.B.Rj(this.container.element);
this.cancelButton=new g.R({S:"button",Ky:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-cancel-button",p.U("web_modern_buttons")?"ytp-autonav-endscreen-upnext-button-rounded":""],V:{"aria-label":"Cancel autoplay"},l_:"Cancel"});g.C(this,this.cancelButton);this.cancelButton.Rj(this.B.element);this.cancelButton.listen("click",this.vS,this);this.D.createClientVe(this.cancelButton.element,this,115129);this.playButton=new g.R({S:"a",Ky:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-play-button",
p.U("web_modern_buttons")?"ytp-autonav-endscreen-upnext-button-rounded":""],V:{href:"{{url}}",role:"button","aria-label":"Play next video"},l_:"Play Now"});g.C(this,this.playButton);this.playButton.Rj(this.B.element);this.playButton.listen("click",this.lj,this);this.D.U("web_player_autonav_next_button_renderer")?(this.D.createServerVe(this.playButton.element,this.playButton,!0),(p=this.D.getVideoData())&&YwV(this,p)):this.D.createClientVe(this.playButton.element,this,115130);this.G=new g.k6(function(){GTd(S)},
500);
g.C(this,this.G);this.Ba();this.C(N,"autonavvisibility",this.Ba);this.D.U("web_autonav_color_transition")&&(this.C(N,"autonavchange",this.nX),this.C(N,"onAutonavCoundownStarted",this.pPd))},hi=function(N){var p=N.D.Me(!0,N.D.isFullscreen());
g.bS(N.container.element,"ytp-autonav-endscreen-small-mode",N.Wl(p));g.bS(N.container.element,"ytp-autonav-endscreen-is-premium",!!N.suggestion&&!!N.suggestion.pGm);g.bS(N.D.getRootNode(),"ytp-autonav-endscreen-cancelled-state",!N.D.I5());g.bS(N.D.getRootNode(),"countdown-running",N.DC());g.bS(N.container.element,"ytp-player-content",N.D.I5());g.TP(N.overlay.element,{width:p.width+"px"});if(!N.DC()){N.D.I5()?dwq(N,Math.round(eCQ(N)/1E3)):dwq(N);p=!!N.suggestion&&!!N.suggestion.Fz;var S=N.D.I5()||
!p;g.bS(N.container.element,"ytp-autonav-endscreen-upnext-alternative-header-only",!S&&p);g.bS(N.container.element,"ytp-autonav-endscreen-upnext-no-alternative-header",S&&!p);N.B.Ea(N.D.I5());g.bS(N.element,"ytp-enable-w2w-color-transitions",C1t(N))}},GTd=function(N){var p=eCQ(N),S=Math,O=S.min;
var P=N.X?Date.now()-N.X:0;S=O.call(S,P,p);dwq(N,Math.ceil((p-S)/1E3));p-S<=500&&N.DC()?N.select(!0):N.DC()&&N.G.start()},eCQ=function(N){if(N.D.isFullscreen()){var p;
N=(p=N.D.getVideoData())==null?void 0:p.LP;return N===-1||N===void 0?8E3:N}return N.D.Q5()>=0?N.D.Q5():g.yo(N.D.J().experiments,"autoplay_time")||1E4},YwV=function(N,p){N.D.U("web_player_autonav_next_button_renderer");
p=p.Mf;N.K=p==null?void 0:p.navigationEndpoint;p=p==null?void 0:p.trackingParams;N.playButton&&p&&N.D.setTrackingParams(N.playButton.element,p)},C1t=function(N){var p;
return!((p=N.D.getVideoData())==null||!p.watchToWatchTransitionRenderer)},dwq=function(N,p){p=p===void 0?-1:p;
N=N.T.gH("ytp-autonav-endscreen-upnext-header");g.b9(N);if(p>=0){p=String(p);var S="Up next in $SECONDS".match(RegExp("\\$SECONDS","gi"))[0],O="Up next in $SECONDS".indexOf(S);if(O>=0){N.appendChild(g.fW("Up next in $SECONDS".slice(0,O)));var P=g.Xo("span");g.OO(P,"ytp-autonav-endscreen-upnext-header-countdown-number");g.xY(P,p);N.appendChild(P);N.appendChild(g.fW("Up next in $SECONDS".slice(O+S.length)));return}}g.xY(N,"Up next")},xX=function(N,p){g.R.call(this,{S:"div",
Ky:["html5-endscreen","ytp-player-content",p||"base-endscreen"]});this.created=!1;this.player=N},yE=function(N){g.R.call(this,{S:"div",
Ky:["ytp-upnext","ytp-player-content"],V:{"aria-label":"{{aria_label}}"},L:[{S:"div",Z:"ytp-cued-thumbnail-overlay-image",V:{style:"{{background}}"}},{S:"span",Z:"ytp-upnext-top",L:[{S:"span",Z:"ytp-upnext-header",l_:"Up Next"},{S:"span",Z:"ytp-upnext-title",l_:"{{title}}"},{S:"span",Z:"ytp-upnext-author",l_:"{{author}}"}]},{S:"a",Z:"ytp-upnext-autoplay-icon",V:{role:"button",href:"{{url}}","aria-label":"Play next video"},L:[{S:"svg",V:{height:"100%",version:"1.1",viewBox:"0 0 72 72",width:"100%"},
L:[{S:"circle",Z:"ytp-svg-autoplay-circle",V:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{S:"circle",Z:"ytp-svg-autoplay-ring",V:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{S:"path",Z:"ytp-svg-fill",V:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{S:"span",Z:"ytp-upnext-bottom",L:[{S:"span",Z:"ytp-upnext-cancel"},{S:"span",Z:"ytp-upnext-paused",
l_:"Autoplay is paused"}]}]});this.api=N;this.cancelButton=null;this.K=this.gH("ytp-svg-autoplay-ring");this.X=this.notification=this.T=this.suggestion=null;this.G=new g.k6(this.k8,5E3,this);this.B=0;var p=this.gH("ytp-upnext-cancel");this.cancelButton=new g.R({S:"button",Ky:["ytp-upnext-cancel-button","ytp-button"],V:{tabindex:"0","aria-label":"Cancel autoplay"},l_:"Cancel"});g.C(this,this.cancelButton);this.cancelButton.listen("click",this.Iy,this);this.cancelButton.Rj(p);this.cancelButton&&this.api.createClientVe(this.cancelButton.element,
this,115129);g.C(this,this.G);this.api.createClientVe(this.element,this,18788);p=this.gH("ytp-upnext-autoplay-icon");this.C(p,"click",this.CX);this.api.createClientVe(p,this,115130);this.Os();this.C(N,"autonavvisibility",this.Os);this.C(N,"mdxnowautoplaying",this.coP);this.C(N,"mdxautoplaycanceled",this.VSB);g.bS(this.element,"ytp-upnext-mobile",this.api.J().B)},ABf=function(N,p){if(p)return p;
if(N.api.isFullscreen()){var S;N=(S=N.api.getVideoData())==null?void 0:S.LP;return N===-1||N===void 0?8E3:N}return N.api.Q5()>=0?N.api.Q5():g.yo(N.api.J().experiments,"autoplay_time")||1E4},tVE=function(N,p){p=ABf(N,p);
var S=Math,O=S.min;var P=(0,g.Hm)()-N.B;S=O.call(S,P,p);p=p===0?1:Math.min(S/p,1);N.K.setAttribute("stroke-dashoffset",""+-211*(p+1));p>=1&&N.DC()&&N.api.getPresentingPlayerType()!==3?N.select(!0):N.DC()&&N.T.start()},VE=function(N){xX.call(this,N,"autonav-endscreen");
this.overlay=this.videoData=null;this.table=new g.R({S:"div",Z:"ytp-suggestion-panel",L:[{S:"div",Ky:["ytp-autonav-endscreen-upnext-header","ytp-autonav-endscreen-more-videos"],l_:"More videos"}]});this.Y=new g.R({S:"div",Z:"ytp-suggestions-container"});this.videos=[];this.X=null;this.K=this.j=!1;this.B=new sT(this.player);g.C(this,this.B);this.B.Rj(this.element);N.getVideoData().aR?this.T=this.B:(this.T=new yE(N),g.IB(this.player,this.T.element,4),g.C(this,this.T));this.overlay=new g.R({S:"div",
Z:"ytp-autonav-overlay-cancelled-state"});g.C(this,this.overlay);this.overlay.Rj(this.element);this.G=new g.Ke(this);g.C(this,this.G);g.C(this,this.table);this.table.Rj(this.element);this.table.show();g.C(this,this.Y);this.Y.Rj(this.table.element);this.hide()},Lj=function(N){var p=N.I5();
p!==N.K&&(N.K=p,N.player.publish("autonavvisibility"),N.K?(N.B!==N.T&&N.B.hide(),N.table.hide()):(N.B!==N.T&&N.B.show(),N.table.show()))},T1=function(N,p){g.R.call(this,{S:"button",
Ky:["ytp-watch-on-youtube-button","ytp-button"],l_:"{{content}}"});this.D=N;this.buttonType=this.buttonType=p;this.QI();this.buttonType===2&&g.WF(this.element,"ytp-continue-watching-button");this.listen("click",this.onClick);this.listen("videodatachange",this.QI);this.Ea(!0)},v1=function(N,p){xX.call(this,N,"embeds-lite-endscreen");
this.D=N;this.T=p;this.D.createClientVe(this.element,this,156943);this.watchButton=new T1(N,2);g.C(this,this.watchButton);this.watchButton.Rj(this.element);this.hide()},udt=function(N){xX.call(this,N,"subscribecard-endscreen");
this.T=new g.R({S:"div",Z:"ytp-subscribe-card",L:[{S:"img",Z:"ytp-author-image",V:{src:"{{profilePicture}}"}},{S:"div",Z:"ytp-subscribe-card-right",L:[{S:"div",Z:"ytp-author-name",l_:"{{author}}"},{S:"div",Z:"html5-subscribe-button-container"}]}]});g.C(this,this.T);this.T.Rj(this.element);var p=N.getVideoData();this.subscribeButton=new g.zG("Subscribe",null,"Unsubscribe",null,!0,!1,p.cU,p.subscribed,"trailer-endscreen",null,N,!1);g.C(this,this.subscribeButton);this.subscribeButton.Rj(this.T.gH("html5-subscribe-button-container"));
this.C(N,"videodatachange",this.b_);this.b_();this.hide()},B1=function(N){var p=N.J(),S=g.Fc||g.$p?{style:"will-change: opacity"}:void 0,O=p.G,P=["ytp-videowall-still"];
p.B&&P.push("ytp-videowall-show-text");g.R.call(this,{S:"a",Ky:P,V:{href:"{{url}}",target:O?p.W:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},L:[{S:"div",Z:"ytp-videowall-still-image",V:{style:"{{background}}"}},{S:"span",Z:"ytp-videowall-still-info",V:{"aria-hidden":"true"},L:[{S:"span",Z:"ytp-videowall-still-info-bg",L:[{S:"span",Z:"ytp-videowall-still-info-content",V:S,L:[{S:"span",Z:"ytp-videowall-still-info-title",l_:"{{title}}"},
{S:"span",Z:"ytp-videowall-still-info-author",l_:"{{author_and_views}}"},{S:"span",Z:"ytp-videowall-still-info-live",l_:"Live"},{S:"span",Z:"ytp-videowall-still-info-duration",l_:"{{duration}}"}]}]}]},{S:"span",Ky:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],V:{"aria-hidden":"true"},L:[{S:"span",Z:"ytp-videowall-still-listlabel-icon"},"Playlist",{S:"span",Z:"ytp-videowall-still-listlabel-length",L:[" (",{S:"span",l_:"{{playlist_length}}"},")"]}]},{S:"span",Ky:["ytp-videowall-still-listlabel-mix",
"ytp-videowall-still-listlabel"],V:{"aria-hidden":"true"},L:[{S:"span",Z:"ytp-videowall-still-listlabel-mix-icon"},"Mix",{S:"span",Z:"ytp-videowall-still-listlabel-length",l_:" (50+)"}]}]});this.suggestion=null;this.B=O;this.api=N;this.T=new g.Ke(this);g.C(this,this.T);this.listen("click",this.onClick);this.listen("keypress",this.onKeyPress);this.T.C(N,"videodatachange",this.onVideoDataChange);N.createServerVe(this.element,this);this.onVideoDataChange()},z1=function(N){xX.call(this,N,"videowall-endscreen");
var p=this;this.D=N;this.X=0;this.stills=[];this.G=this.videoData=null;this.K=this.Y=!1;this.W=null;this.B=new g.Ke(this);g.C(this,this.B);this.j=new g.k6(function(){g.WF(p.element,"ytp-show-tiles")},0);
g.C(this,this.j);var S=new g.R({S:"button",Ky:["ytp-button","ytp-endscreen-previous"],V:{"aria-label":"Previous"},L:[g.EU()]});g.C(this,S);S.Rj(this.element);S.listen("click",this.LX,this);this.table=new g.sU({S:"div",Z:"ytp-endscreen-content"});g.C(this,this.table);this.table.Rj(this.element);S=new g.R({S:"button",Ky:["ytp-button","ytp-endscreen-next"],V:{"aria-label":"Next"},L:[g.$y()]});g.C(this,S);S.Rj(this.element);S.listen("click",this.Y2,this);N.getVideoData().aR?this.T=new sT(N,!0):this.T=
new yE(N);g.C(this,this.T);g.IB(this.player,this.T.element,4);N.createClientVe(this.element,this,158789);this.hide()},ET=function(N){return g.DI(N.player)&&N.Dr()&&!N.G},$X=function(N){var p=N.I5();
p!==N.Y&&(N.Y=p,N.player.publish("autonavvisibility"))},Ji=function(N){xX.call(this,N,"watch-again-on-youtube-endscreen");
this.watchButton=new T1(N,1);g.C(this,this.watchButton);this.watchButton.Rj(this.element);g.Krd(N)&&(this.T=new g.SN(N),g.C(this,this.T),this.B=new g.R({S:"div",Ky:["ytp-watch-again-on-youtube-endscreen-more-videos-container"],V:{tabIndex:"-1"},L:[this.T]}),g.C(this,this.B),this.T.Rj(this.B.element),this.B.Rj(this.element));N.createClientVe(this.element,this,156914);this.hide()},DwQ=function(N){g.dg.call(this,N);
var p=this;this.endScreen=null;this.B=this.T=this.X=this.G=!1;this.listeners=new g.Ke(this);g.C(this,this.listeners);var S=N.J(),O=N.getVideoData();O=O&&O.limitedPlaybackDurationInSeconds!==0;g.ln(g.nD(S))&&O&&!g.tp(N)?(this.B=!0,this.endScreen=new v1(N,g.aB(N))):N.t4()?this.endScreen=new Ji(N):wkq(N)?(this.G=!0,RCQ(this),this.T?this.endScreen=new VE(N):this.endScreen=new z1(N)):S.l1?this.endScreen=new udt(N):this.endScreen=new xX(N);g.C(this,this.endScreen);g.IB(N,this.endScreen.element,4);I7s(this);
this.listeners.C(N,"videodatachange",this.onVideoDataChange,this);this.listeners.C(N,g.f7("endscreen"),function(P){p.onCueRangeEnter(P)});
this.listeners.C(N,g.ls("endscreen"),function(P){p.onCueRangeExit(P)})},RCQ=function(N){var p=N.player.getVideoData();
if(!p||N.T===p.TP&&N.X===p.aR)return!1;N.T=p.TP;N.X=p.aR;return!0},wkq=function(N){N=N.J();
return N.LG&&!N.l1},I7s=function(N){N.player.WD("endscreen");
var p=N.player.getVideoData();p=new g.WY(Math.max((p.lengthSeconds-10)*1E3,0),0x8000000000000,{id:"preload",namespace:"endscreen"});var S=new g.WY(0x8000000000000,0x8000000000000,{id:"load",priority:8,namespace:"endscreen"});N.player.cD([p,S])};
g.d3.prototype.Q5=g.SA(14,function(){return this.app.Q5()});
g.H5.prototype.Q5=g.SA(13,function(){return this.getVideoData().MF});
g.MW.prototype.Ho=g.SA(12,function(N){this.m7().Ho(N)});
g.KA.prototype.Ho=g.SA(11,function(N){this.T!==N&&(this.T=N,this.b_())});
g.tr.prototype.Ho=g.SA(10,function(N){this.overflowButton&&this.overflowButton.Ho(N)});
g.MW.prototype.MN=g.SA(9,function(N){this.m7().MN(N)});
g.CA.prototype.MN=g.SA(8,function(N){this.B!==N&&(this.B=N,this.b_())});
g.tr.prototype.MN=g.SA(7,function(N){this.shareButton&&this.shareButton.MN(N)});
g.MW.prototype.wE=g.SA(6,function(N){this.m7().wE(N)});
g.xC.prototype.wE=g.SA(5,function(N){this.qr!==N&&(this.qr=N,this.BN())});
g.MW.prototype.mV=g.SA(4,function(N){this.m7().mV(N)});
g.tr.prototype.mV=g.SA(3,function(N){this.jj!==N&&(this.jj=N,this.kd())});g.B(j6,g.R);j6.prototype.select=function(){this.D.P_(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.lO||void 0)&&this.D.logClick(this.element)};
j6.prototype.onClick=function(N){g.vL(N,this.D,this.T,this.suggestion.sessionData||void 0)&&this.select()};
j6.prototype.onKeyPress=function(N){switch(N.keyCode){case 13:case 32:N.defaultPrevented||(this.select(),N.preventDefault())}};g.B(sT,g.R);g.f=sT.prototype;g.f.x3=function(N){this.suggestion!==N&&(this.suggestion=N,b6(this.T,N),this.playButton.updateValue("url",this.suggestion.m2()),hi(this))};
g.f.DC=function(){return this.X>0};
g.f.oH=function(){this.DC()||(this.X=Date.now(),GTd(this),Kwy(this.D,eCQ(this)),g.bS(this.D.getRootNode(),"countdown-running",this.DC()))};
g.f.fU=function(){this.Vt();GTd(this);var N=this.T.gH("ytp-autonav-endscreen-upnext-header");N&&g.xY(N,"Up next")};
g.f.Vt=function(){this.DC()&&(this.G.stop(),this.X=0)};
g.f.select=function(N){this.D.nextVideo(!1,N===void 0?!1:N);this.Vt()};
g.f.lj=function(N){g.vL(N,this.D)&&(N.currentTarget===this.playButton.element?this.D.logClick(this.playButton.element):N.currentTarget===this.T.gH("ytp-autonav-endscreen-link-container")&&(N=this.T.gH("ytp-autonav-endscreen-link-container"),this.D.logVisibility(N,!0),this.D.logClick(N)),this.D.U("web_player_autonav_next_button_renderer")&&this.K?(this.D.YO("innertubeCommand",this.K),this.Vt()):this.select())};
g.f.vS=function(){this.D.logClick(this.cancelButton.element);g.Cv(this.D,!0);this.cancelCommand&&this.D.YO("innertubeCommand",this.cancelCommand)};
g.f.onVideoDataChange=function(N,p){this.D.U("web_player_autonav_next_button_renderer")&&YwV(this,p);var S;this.cancelCommand=(S=p.Qx)==null?void 0:S.command};
g.f.pPd=function(N){if(C1t(this)){var p=this.D.getVideoData().watchToWatchTransitionRenderer,S=p==null?void 0:p.fromColorPaletteDark;p=p==null?void 0:p.toColorPaletteDark;if(S&&p){var O=this.element;O.style.setProperty("--w2w-start-background-color",g.Au(S.surgeColor));O.style.setProperty("--w2w-start-primary-text-color",g.Au(S.primaryTitleColor));O.style.setProperty("--w2w-start-secondary-text-color",g.Au(S.secondaryTitleColor));O.style.setProperty("--w2w-end-background-color",g.Au(p.surgeColor));
O.style.setProperty("--w2w-end-primary-text-color",g.Au(p.primaryTitleColor));O.style.setProperty("--w2w-end-secondary-text-color",g.Au(p.secondaryTitleColor));O.style.setProperty("--w2w-animation-duration",N+"ms")}g.bS(this.element,"ytp-w2w-animate",!0)}};
g.f.nX=function(N){this.D.U("web_autonav_color_transition")&&N!==2&&g.bS(this.element,"ytp-w2w-animate",!1)};
g.f.Ba=function(){var N=this.D.I5();this.j&&this.Oa!==N&&this.Ea(N);hi(this);this.D.logVisibility(this.container.element,N);this.D.logVisibility(this.cancelButton.element,N);this.D.logVisibility(this.T.gH("ytp-autonav-endscreen-link-container"),N);this.D.logVisibility(this.playButton.element,N)};
g.f.Wl=function(N){return N.width<400||N.height<459};g.B(xX,g.R);g.f=xX.prototype;g.f.create=function(){this.created=!0};
g.f.destroy=function(){this.created=!1};
g.f.Dr=function(){return!1};
g.f.I5=function(){return!1};
g.f.Mu=function(){return!1};g.B(yE,g.R);g.f=yE.prototype;g.f.k8=function(){this.notification&&(this.G.stop(),this.xK(this.X),this.X=null,this.notification.close(),this.notification=null)};
g.f.x3=function(N){this.suggestion=N;b6(this,N,"hqdefault.jpg")};
g.f.Os=function(){this.Ea(this.api.I5());this.api.logVisibility(this.element,this.api.I5());this.api.logVisibility(this.gH("ytp-upnext-autoplay-icon"),this.api.I5());this.cancelButton&&this.api.logVisibility(this.cancelButton.element,this.api.I5())};
g.f.kBB=function(){window.focus();this.k8()};
g.f.oH=function(N){var p=this;this.DC()||(g.jB("a11y-announce","Up Next "+this.suggestion.title),this.B=(0,g.Hm)(),this.T=new g.k6(function(){tVE(p,N)},25),tVE(this,N),Kwy(this.api,ABf(this,N)));
g.fE(this.element,"ytp-upnext-autoplay-paused")};
g.f.hide=function(){g.R.prototype.hide.call(this)};
g.f.DC=function(){return!!this.T};
g.f.fU=function(){this.Vt();this.B=(0,g.Hm)();tVE(this);g.WF(this.element,"ytp-upnext-autoplay-paused")};
g.f.Vt=function(){this.DC()&&(this.T.dispose(),this.T=null)};
g.f.select=function(N){N=N===void 0?!1:N;if(this.api.J().U("autonav_notifications")&&N&&window.Notification&&typeof document.hasFocus==="function"){var p=Notification.permission;p==="default"?Notification.requestPermission():p!=="granted"||document.hasFocus()||(this.k8(),this.notification=new Notification("Up Next",{body:this.suggestion.title,icon:this.suggestion.f7()}),this.X=this.C(this.notification,"click",this.kBB),this.G.start())}this.Vt();this.api.nextVideo(!1,N)};
g.f.CX=function(N){!g.hd(this.cancelButton.element,N.target)&&g.vL(N,this.api)&&(this.api.I5()&&this.api.logClick(this.gH("ytp-upnext-autoplay-icon")),this.select())};
g.f.Iy=function(){this.api.I5()&&this.cancelButton&&this.api.logClick(this.cancelButton.element);g.Cv(this.api,!0)};
g.f.coP=function(N){this.api.getPresentingPlayerType();this.show();this.oH(N)};
g.f.VSB=function(){this.api.getPresentingPlayerType();this.Vt();this.hide()};
g.f.BP=function(){this.Vt();this.k8();g.R.prototype.BP.call(this)};g.B(VE,xX);g.f=VE.prototype;g.f.create=function(){xX.prototype.create.call(this);this.G.C(this.player,"appresize",this.pP);this.G.C(this.player,"onVideoAreaChange",this.pP);this.G.C(this.player,"videodatachange",this.onVideoDataChange);this.G.C(this.player,"autonavchange",this.p_);this.G.C(this.player,"onAutonavCancelled",this.Jl);this.onVideoDataChange()};
g.f.show=function(){xX.prototype.show.call(this);(this.j||this.X&&this.X!==this.videoData.clientPlaybackNonce)&&g.Cv(this.player,!1);g.DI(this.player)&&this.Dr()&&!this.X?(Lj(this),this.videoData.autonavState===2?this.player.getVisibilityState()===3?this.T.select(!0):this.T.oH():this.videoData.autonavState===3&&this.T.fU()):(g.Cv(this.player,!0),Lj(this));this.pP()};
g.f.hide=function(){xX.prototype.hide.call(this);this.T.fU();Lj(this)};
g.f.pP=function(){var N=this.player.Me(!0,this.player.isFullscreen());Lj(this);hi(this.B);g.bS(this.element,"ytp-autonav-cancelled-small-mode",this.Wl(N));g.bS(this.element,"ytp-autonav-cancelled-tiny-mode",this.ZP(N));g.bS(this.element,"ytp-autonav-cancelled-mini-mode",N.width<=400||N.height<=360);this.overlay&&g.TP(this.overlay.element,{width:N.width+"px"});if(!this.K)for(N=0;N<this.videos.length;N++)g.bS(this.videos[N].element,"ytp-suggestion-card-with-margin",N%2===1)};
g.f.onVideoDataChange=function(){var N=this.player.getVideoData();if(this.videoData!==N&&N){this.videoData=N;if((N=this.videoData.suggestions)&&N.length||this.player.U("web_player_autonav_empty_suggestions_fix")){var p=g.WC(this.videoData);p&&(this.T.x3(p),this.T!==this.B&&this.B.x3(p))}if(N&&N.length)for(p=0;p<ZxY.length;++p){var S=ZxY[p];if(N&&N[S]){this.videos[p]=new j6(this.player);var O=this.videos[p];S=N[S];O.suggestion!==S&&(O.suggestion=S,b6(O,S));g.C(this,this.videos[p]);this.videos[p].Rj(this.Y.element)}}this.pP()}};
g.f.p_=function(N){N===1?(this.j=!1,this.X=this.videoData.clientPlaybackNonce,this.T.Vt(),this.Oa&&this.pP()):(this.j=!0,this.I5()&&(N===2?this.T.oH():N===3&&this.T.fU()))};
g.f.Jl=function(N){N?this.p_(1):(this.X=null,this.j=!1)};
g.f.Dr=function(){return this.videoData.autonavState!==1};
g.f.Wl=function(N){return(N.width<910||N.height<459)&&!this.ZP(N)&&!(N.width<=400||N.height<=360)};
g.f.ZP=function(N){return N.width<800&&!(N.width<=400||N.height<=360)};
g.f.I5=function(){return this.Oa&&g.DI(this.player)&&this.Dr()&&!this.X};
var ZxY=[1,3,2,4];g.B(T1,g.R);g.f=T1.prototype;g.f.QI=function(){switch(this.buttonType){case 1:var N="Watch again on YouTube";var p=156915;break;case 2:N="Continue watching on YouTube";p=156942;break;default:N="Continue watching on YouTube",p=156942}this.update({content:N});this.D.hasVe(this.element)&&this.D.destroyVe(this.element);this.D.createClientVe(this.element,this,p)};
g.f.onClick=function(N){this.D.U("web_player_log_click_before_generating_ve_conversion_params")&&this.D.logClick(this.element);g.BL(this.getVideoUrl(),this.D,N);this.D.U("web_player_log_click_before_generating_ve_conversion_params")||this.D.logClick(this.element)};
g.f.getVideoUrl=function(){var N=!0;switch(this.buttonType){case 1:N=!0;break;case 2:N=!1}N=this.D.getVideoUrl(N,!1,!1,!0);var p=this.D.J();if(g.mk(p)){var S={};g.mk(p)&&g.Jp(this.D,"addEmbedsConversionTrackingParams",[S]);N=g.k8(N,S)}return N};
g.f.logVisibility=function(){this.D.logVisibility(this.element,this.Oa&&this.N)};
g.f.show=function(){g.R.prototype.show.call(this);this.logVisibility()};
g.f.hide=function(){g.R.prototype.hide.call(this);this.logVisibility()};
g.f.bB=function(N){g.R.prototype.bB.call(this,N);this.logVisibility()};g.B(v1,xX);v1.prototype.show=function(){this.player.getPlayerState()!==3&&(xX.prototype.show.call(this),this.T.mV(!0),this.T.MN(!0),this.D.J().FS||this.T.Ho(!0),this.D.logVisibility(this.element,!0),this.watchButton.bB(!0))};
v1.prototype.hide=function(){xX.prototype.hide.call(this);this.T.mV(!1);this.T.MN(!1);this.T.Ho(!1);this.D.logVisibility(this.element,!1);this.watchButton.bB(!1)};g.B(udt,xX);udt.prototype.b_=function(){var N=this.player.getVideoData();this.T.update({profilePicture:N.profilePicture,author:N.author});this.subscribeButton.channelId=N.cU;var p=this.subscribeButton;N.subscribed?p.T():p.B()};g.B(B1,g.R);B1.prototype.select=function(){this.api.P_(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.lO||void 0)&&this.api.logClick(this.element)};
B1.prototype.onClick=function(N){if(g.mk(this.api.J())&&this.api.U("web_player_log_click_before_generating_ve_conversion_params")){this.api.logClick(this.element);var p=this.suggestion.m2(),S={};g.uM(this.api,S);p=g.k8(p,S);g.BL(p,this.api,N)}else g.vL(N,this.api,this.B,this.suggestion.sessionData||void 0)&&this.select()};
B1.prototype.onKeyPress=function(N){switch(N.keyCode){case 13:case 32:N.defaultPrevented||(this.select(),N.preventDefault())}};
B1.prototype.onVideoDataChange=function(){var N=this.api.getVideoData(),p=this.api.J();this.B=N.JF?!1:p.G};g.B(z1,xX);g.f=z1.prototype;g.f.create=function(){xX.prototype.create.call(this);var N=this.player.getVideoData();N&&(this.videoData=N);this.fQ();this.B.C(this.player,"appresize",this.fQ);this.B.C(this.player,"onVideoAreaChange",this.fQ);this.B.C(this.player,"videodatachange",this.onVideoDataChange);this.B.C(this.player,"autonavchange",this.y7);this.B.C(this.player,"onAutonavCancelled",this.yx);N=this.videoData.autonavState;N!==this.W&&this.y7(N);this.B.C(this.element,"transitionend",this.mRH)};
g.f.destroy=function(){g.aR(this.B);g.Wt(this.stills);this.stills=[];xX.prototype.destroy.call(this);g.fE(this.element,"ytp-show-tiles");this.j.stop();this.W=this.videoData.autonavState};
g.f.Dr=function(){return this.videoData.autonavState!==1};
g.f.show=function(){var N=this.Oa;xX.prototype.show.call(this);g.fE(this.element,"ytp-show-tiles");this.player.J().B?g.Nv(this.j):this.j.start();(this.K||this.G&&this.G!==this.videoData.clientPlaybackNonce)&&g.Cv(this.player,!1);ET(this)?($X(this),this.videoData.autonavState===2?this.player.getVisibilityState()===3?this.T.select(!0):this.T.oH():this.videoData.autonavState===3&&this.T.fU()):(g.Cv(this.player,!0),$X(this));N!==this.Oa&&this.player.logVisibility(this.element,!0)};
g.f.hide=function(){var N=this.Oa;xX.prototype.hide.call(this);this.T.fU();$X(this);N!==this.Oa&&this.player.logVisibility(this.element,!1)};
g.f.mRH=function(N){N.target===this.element&&this.fQ()};
g.f.fQ=function(){var N,p,S,O;var P=((N=this.videoData)==null?0:(p=N.suggestions)==null?0:p.length)?(S=this.videoData)==null?void 0:S.suggestions:[(O=this.videoData)==null?void 0:g.WC(O)];if(P.length){g.WF(this.element,"ytp-endscreen-paginate");var W=this.D.Me(!0,this.D.isFullscreen());if(N=g.aB(this.D))N=N.tE()?48:32,W.width-=N*2;var X=W.width/W.height;O=96/54;p=N=2;var l=Math.max(W.width/96,2),b=Math.max(W.height/54,2);S=P.length;var h=S*4;for(h-=4;h>0&&(N<l||p<b);){var x=N/2,y=p/2,V=N<=l-2&&h>=
y*4,L=p<=b-2&&h>=x*4;if((x+1)/y*O/X>X/(x/(y+1)*O)&&L)h-=x*4,p+=2;else if(V)h-=y*4,N+=2;else if(L)h-=x*4,p+=2;else break}O=!1;h>=12&&S*4-h<=6&&(p>=4||N>=4)&&(O=!0);h=N*96;l=p*54;X=h/l<X?W.height/l:W.width/h;X=Math.min(X,2);h=Math.floor(Math.min(W.width,h*X));l=Math.floor(Math.min(W.height,l*X));W=this.table.element;W.ariaLive="polite";g.iR(W,h,l);g.TP(W,{marginLeft:h/-2+"px",marginTop:l/-2+"px"});this.T.x3(g.WC(this.videoData));this.T instanceof sT&&hi(this.T);g.bS(this.element,"ytp-endscreen-takeover",
ET(this));$X(this);h+=4;l+=4;X=0;W.ariaBusy="true";for(b=0;b<N;b++)for(x=0;x<p;x++)if(y=X,L=0,O&&b>=N-2&&x>=p-2?L=1:x%2===0&&b%2===0&&(x<2&&b<2?x===0&&b===0&&(L=2):L=2),y=g.Tq(y+this.X,S),L!==0){V=this.stills[X];V||(V=new B1(this.player),this.stills[X]=V,W.appendChild(V.element));var T=Math.floor(l*x/p),E=Math.floor(h*b/N),m=Math.floor(l*(x+L)/p)-T-4,H=Math.floor(h*(b+L)/N)-E-4;g.JE(V.element,E,T);g.iR(V.element,H,m);g.TP(V.element,"transitionDelay",(x+b)/20+"s");g.bS(V.element,"ytp-videowall-still-mini",
L===1);g.bS(V.element,"ytp-videowall-still-large",L>2);L=Math.max(H,m);g.bS(V.element,"ytp-videowall-still-round-large",L>=256);g.bS(V.element,"ytp-videowall-still-round-medium",L>96&&L<256);g.bS(V.element,"ytp-videowall-still-round-small",L<=96);y=P[y];V.suggestion!==y&&(V.suggestion=y,L=V.api.J(),T=g.PF(V.element,"ytp-videowall-still-large")?"hqdefault.jpg":"mqdefault.jpg",b6(V,y,T),g.mk(L)&&!V.api.U("web_player_log_click_before_generating_ve_conversion_params")&&(L=y.m2(),T={},g.Jp(V.api,"addEmbedsConversionTrackingParams",
[T]),L=g.k8(L,T),V.updateValue("url",L)),(y=(y=y.sessionData)&&y.itct)&&V.api.setTrackingParams(V.element,y));X++}W.ariaBusy="false";g.bS(this.element,"ytp-endscreen-paginate",X<S);for(P=this.stills.length-1;P>=X;P--)N=this.stills[P],g.si(N.element),g.Pt(N);this.stills.length=X}};
g.f.onVideoDataChange=function(){var N=this.player.getVideoData(1);this.videoData!==N&&(N!=null&&g.WC(N)?(this.X=0,this.videoData=N,this.fQ()):this.player.Tk("missg",{vid:(N==null?void 0:N.videoId)||"",cpn:(N==null?void 0:N.clientPlaybackNonce)||""}))};
g.f.Y2=function(){this.X+=this.stills.length;this.fQ()};
g.f.LX=function(){this.X-=this.stills.length;this.fQ()};
g.f.Mu=function(){return this.T.DC()};
g.f.y7=function(N){N===1?(this.K=!1,this.G=this.videoData.clientPlaybackNonce,this.T.Vt(),this.Oa&&this.fQ()):(this.K=!0,this.Oa&&ET(this)&&(N===2?this.T.oH():N===3&&this.T.fU()))};
g.f.yx=function(N){if(N){for(N=0;N<this.stills.length;N++)this.D.logVisibility(this.stills[N].element,!0);this.y7(1)}else this.G=null,this.K=!1;this.fQ()};
g.f.I5=function(){return this.Oa&&ET(this)};g.B(Ji,xX);Ji.prototype.hasSuggestions=function(){var N;return(N=this.T)==null?void 0:N.hasSuggestions()};
Ji.prototype.show=function(){if(this.player.getPlayerState()!==3){xX.prototype.show.call(this);var N=this.B;if(N){var p=this.T.hasSuggestions();g.bS(this.element,"ytp-shorts-branded-ui",p);p?N.show():N.hide()}var S;(S=g.aB(this.player))==null||S.wE(!0);this.player.logVisibility(this.element,!0);this.watchButton.bB(!0)}};
Ji.prototype.hide=function(){xX.prototype.hide.call(this);var N;(N=g.aB(this.player))==null||N.wE(!1);this.player.logVisibility(this.element,!1);this.watchButton.bB(!1)};g.B(DwQ,g.dg);g.f=DwQ.prototype;g.f.bI=function(){var N=this.player.getVideoData(),p=N.U("embeds_enable_full_length_inline_muted_autoplay")?N.mutedAutoplay&&(N.limitedPlaybackDurationInSeconds>0||N.endSeconds>0):N.mutedAutoplay;if((this.player.t4()||this.B)&&!p)return!0;var S;var O=!!((N==null?0:g.WC(N))||(N==null?0:(S=N.suggestions)==null?0:S.length));O=!wkq(this.player)||O;N=N.tK;S=this.player.wp();return O&&!N&&!S&&!p};
g.f.I5=function(){return this.endScreen.I5()};
g.f.yy=function(){return this.I5()?this.endScreen.Mu():!1};
g.f.BP=function(){this.player.WD("endscreen");g.dg.prototype.BP.call(this)};
g.f.load=function(){var N=this.player.getVideoData();var p=N.transitionEndpointAtEndOfStream;if(p&&p.videoId){var S=this.player.zB().Ey.get("heartbeat"),O=g.WC(N);!O||p.videoId!==O.videoId||N.AC?(this.player.P_(p.videoId,void 0,void 0,!0,!0,p),S&&S.AO("HEARTBEAT_ACTION_TRIGGER_AT_STREAM_END","HEARTBEAT_ACTION_TRANSITION_REASON_HAS_NEW_STREAM_TRANSITION_ENDPOINT"),N=!0):N=!1}else N=!1;N||(g.dg.prototype.load.call(this),this.endScreen.show())};
g.f.unload=function(){g.dg.prototype.unload.call(this);this.endScreen.hide();this.endScreen.destroy()};
g.f.onCueRangeEnter=function(N){this.bI()&&(this.endScreen.created||this.endScreen.create(),N.getId()==="load"&&this.load())};
g.f.onCueRangeExit=function(N){N.getId()==="load"&&this.loaded&&this.unload()};
g.f.onVideoDataChange=function(){I7s(this);this.G&&RCQ(this)&&(this.endScreen&&(this.endScreen.hide(),this.endScreen.created&&this.endScreen.destroy(),this.endScreen.dispose()),this.T?this.endScreen=new VE(this.player):this.endScreen=new z1(this.player),g.C(this,this.endScreen),g.IB(this.player,this.endScreen.element,4))};g.Gc("endscreen",DwQ);})(_yt_player);
