(function(g){var window=this;'use strict';var YX=function(N,p){g.R.call(this,{S:"button",Ky:["ytp-miniplayer-expand-watch-page-button","ytp-button","ytp-miniplayer-button-top-left"],V:{title:"{{title}}","data-tooltip-target-id":"ytp-miniplayer-expand-watch-page-button","aria-keyshortcuts":"i","data-title-no-tooltip":"{{data-title-no-tooltip}}"},L:[{S:"svg",V:{height:"24px",version:"1.1",viewBox:"0 0 24 24",width:"24px"},L:[{S:"g",V:{fill:"none","fill-rule":"evenodd",stroke:"none","stroke-width":"1"},L:[{S:"g",V:{transform:"translate(12.000000, 12.000000) scale(-1, 1) translate(-12.000000, -12.000000) "},
L:[{S:"path",V:{d:"M19,19 L5,19 L5,5 L12,5 L12,3 L5,3 C3.89,3 3,3.9 3,5 L3,19 C3,20.1 3.89,21 5,21 L19,21 C20.1,21 21,20.1 21,19 L21,12 L19,12 L19,19 Z M14,3 L14,5 L17.59,5 L7.76,14.83 L9.17,16.24 L19,6.41 L19,10 L21,10 L21,3 L14,3 Z",fill:"#fff","fill-rule":"nonzero"}}]}]}]}]});this.D=N;this.listen("click",this.onClick,this);this.updateValue("title",g.GZ(N,"Expand","i"));this.update({"data-title-no-tooltip":"Expand"});this.addOnDisposeCallback(g.Kv(p.lz(),this.element))},IqY=function(N){g.R.call(this,
{S:"div",
Z:"ytp-miniplayer-ui"});this.Y=this.K=!1;this.player=N;this.C(N,"minimized",this.wZ);this.C(N,"onStateChange",this.KTp);this.C(N,"documentpictureinpicturechange",this.P_o)},Drt=function(N,p){g.bS(N.player.getRootNode(),"ytp-player-minimized",p);
N.player.U("web_cairo_modern_miniplayer")&&g.bS(N.player.getRootNode(),"ytp-modern-miniplayer",p);N.player.U("web_cairo_modern_miniplayer_inset_progress_bar")&&g.bS(N.player.getRootNode(),"ytp-miniplayer-alternate-ui",p)},ZZl=function(N){var p=N.player.cP().getPlayerSize().width,S=0,O=p;
if(N.player.U("web_cairo_modern_miniplayer")&&!N.Y&&!N.player.U("web_cairo_modern_miniplayer_infobar")||N.player.U("web_cairo_modern_miniplayer_inset_progress_bar"))S=12,O=p-24;g.WG8(N.progressBar,S,O,!1);g.f9(N.progressBar)},k3l=function(N){g.dg.call(this,N);
this.B=new g.Ke(this);this.T=new IqY(this.player);this.T.hide();g.IB(this.player,this.T.element,4);N.isMinimized()&&(this.load(),g.bS(N.getRootNode(),"ytp-player-minimized",!0))};
g.B(YX,g.R);YX.prototype.onClick=function(){this.D.YO("onExpandMiniplayer")};g.B(IqY,g.R);g.f=IqY.prototype;
g.f.show=function(){this.T=new g.ZU(this.Al,null,this);this.T.start();if(!this.K){this.tooltip=new g.Ar(this.player,this);g.C(this,this.tooltip);g.IB(this.player,this.tooltip.element,4);this.tooltip.scale=.6;this.S9=new g.LA(this.player);g.C(this,this.S9);this.progressBar=new g.Xf(this.player,this);g.C(this,this.progressBar);g.IB(this.player,this.progressBar.element,4);this.player.U("web_cairo_modern_miniplayer_infobar")&&g.WF(this.player.getRootNode(),"ytp-always-showing-infobar");this.B=new g.R({S:"div",
Z:"ytp-miniplayer-scrim"});g.C(this,this.B);this.B.Rj(this.element);this.C(this.B.element,"click",this.zc);var N=new g.R({S:"button",Ky:["ytp-miniplayer-close-button","ytp-button"],V:{"aria-label":"Close"},L:[g.J$()]});g.C(this,N);N.Rj(this.B.element);this.C(N.element,"click",this.eE);N=new YX(this.player,this);g.C(this,N);N.Rj(this.B.element);this.X=new g.R({S:"div",Z:"ytp-miniplayer-controls"});g.C(this,this.X);this.X.Rj(this.B.element);this.player.U("web_cairo_modern_miniplayer")||this.C(this.X.element,
"click",this.zc);var p=new g.R({S:"div",Z:"ytp-miniplayer-button-container"});g.C(this,p);p.Rj(this.X.element);N=new g.R({S:"div",Z:"ytp-miniplayer-play-button-container"});g.C(this,N);N.Rj(this.X.element);var S=new g.R({S:"div",Z:"ytp-miniplayer-button-container"});g.C(this,S);S.Rj(this.X.element);this.W=new g.or(this.player,this,!1);g.C(this,this.W);this.W.Rj(p.element);p=new g.p9(this.player,this);g.C(this,p);p.Rj(N.element);this.nextButton=new g.or(this.player,this,!0);g.C(this,this.nextButton);
this.nextButton.Rj(S.element);this.j=this.player.U("web_cairo_modern_miniplayer")?new g.MY(this.player,this,0):new g.MY(this.player,this);g.C(this,this.j);this.j.Rj(this.B.element);this.G=new g.R({S:"div",Z:"ytp-miniplayer-buttons"});g.C(this,this.G);g.IB(this.player,this.G.element,4);N=new g.R({S:"button",Ky:["ytp-miniplayer-close-button","ytp-button"],V:{"aria-label":"Close"},L:[g.J$()]});g.C(this,N);N.Rj(this.G.element);this.C(N.element,"click",this.eE);N=new g.R({S:"button",Ky:["ytp-miniplayer-replay-button",
"ytp-button"],V:{"aria-label":"Close"},L:[g.Qr()]});g.C(this,N);N.Rj(this.G.element);this.C(N.element,"click",this.NFS);this.player.U("web_cairo_modern_miniplayer")&&(N=new YX(this.player,this),g.C(this,N),N.Rj(this.G.element));this.C(this.player,"presentingplayerstatechange",this.WS);this.C(this.player,"appresize",this.I4);this.C(this.player,"fullscreentoggled",this.I4);this.player.U("web_cairo_modern_miniplayer")&&this.C(this.player,"onPlaylistUpdate",this.X9);this.I4();this.K=!0}this.player.getPlayerState()!==
0&&g.R.prototype.show.call(this);this.progressBar.show();this.player.unloadModule("annotations_module")};
g.f.hide=function(){this.T&&(this.T.dispose(),this.T=void 0);g.R.prototype.hide.call(this);this.player.isMinimized()||(this.K&&this.progressBar.hide(),this.player.loadModule("annotations_module"))};
g.f.BP=function(){this.T&&(this.T.dispose(),this.T=void 0);g.R.prototype.BP.call(this)};
g.f.eE=function(){this.player.U("kevlar_watch_while_v2")||this.player.stopVideo();this.player.YO("onCloseMiniplayer")};
g.f.NFS=function(){this.player.playVideo()};
g.f.zc=function(N){if(N.target===this.B.element||N.target===this.X.element)this.player.getPlayerStateObject().isOrWillBePlaying()?this.player.pauseVideo():this.player.playVideo()};
g.f.wZ=function(){Drt(this,this.player.isMinimized());this.player.U("web_cairo_modern_miniplayer")&&this.X9()};
g.f.P_o=function(){Drt(this,this.player.dR());this.player.U("web_cairo_modern_miniplayer")&&this.X9();g.bS(this.player.getRootNode(),"ytp-player-document-picture-in-picture",this.player.dR())};
g.f.oR=function(){this.progressBar.Qz();this.j.Qz()};
g.f.Al=function(){this.oR();this.T&&this.T.start()};
g.f.WS=function(N){g.Z(N.state,32)&&this.tooltip.hide()};
g.f.X9=function(){this.Y=(this.player.isMinimized()||this.player.dR())&&!!this.player.getPlaylist();g.bS(this.player.getRootNode(),"ytp-has-playlist-data",this.Y);ZZl(this)};
g.f.I4=function(){ZZl(this)};
g.f.KTp=function(N){this.player.isMinimized()&&(N===0?this.hide():this.show())};
g.f.lz=function(){return this.tooltip};
g.f.GX=function(N,p,S,O,P){var W=0,X=0,l=0,b=g.aS(N);O=p&&(g.PF(p,"ytp-prev-button")||g.PF(p,"ytp-next-button"));if(p){S=g.PF(p,"ytp-play-button");var h=g.PF(p,"ytp-miniplayer-expand-watch-page-button");O?W=l=12:S?(p=g.HH(p,this.element),l=p.x,W=p.y-12):h&&(l=g.PF(p,"ytp-miniplayer-button-top-left"),W=g.HH(p,this.element),p=g.aS(p),l?(l=8,W=W.y+40):(l=W.x-b.width+p.width,W=W.y-20))}else l=S-b.width/2,X=25+(P||0);p=this.player.cP().getPlayerSize();P=W+(P||0);b=g.LB(l,0,p.width-b.width-12);P?(N.style.top=
P+"px",N.style.bottom=""):(N.style.top="",N.style.bottom=X+"px");N.style.left=b+"px";this.player.U("web_cairo_modern_miniplayer")&&(X=g.PF(N,"ytp-preview"),N.style.visibility=O&&X&&p.height<225?"hidden":"")};g.B(k3l,g.dg);g.f=k3l.prototype;g.f.onVideoDataChange=function(){if(this.player.getVideoData()){var N=this.player.getVideoAspectRatio(),p=16/9;N=N>p+.1||N<p-.1;g.bS(this.player.getRootNode(),"ytp-rounded-miniplayer-not-regular-wide-video",N)}};
g.f.create=function(){g.dg.prototype.create.call(this);this.B.C(this.player,"videodatachange",this.onVideoDataChange);this.onVideoDataChange()};
g.f.Vp=function(){return!1};
g.f.load=function(){this.player.hideControls();this.T.show()};
g.f.unload=function(){this.player.showControls();this.T.hide()};g.Gc("miniplayer",k3l);})(_yt_player);
